import type{DbReadPortUid,DbErrorUid}from'./dbRuntimeContract';
export type DbProjectionItem={ref:string;label:string;meta?:Record<string,unknown>};
export type DbNormalizedProjection={page_state:string;values:Record<string,unknown>;lists:Record<string,DbProjectionItem[]>;tables:Record<string,unknown[]>;gates:Record<string,boolean>;filters:Record<string,DbProjectionItem[]>;graph:unknown;trace:unknown;audit:unknown;source_sync:string|null;};
export type DbReadInput={scope?:unknown;query?:unknown};
export type DbClientResult={ok:true;projection:DbNormalizedProjection;correlation_id:string}|{ok:false;error_uid:DbErrorUid;reason_code:string;correlation_id:string};
export type DbClientBindings={readProjection:()=>Promise<DbClientResult>;read:(port_uid:DbReadPortUid,input:DbReadInput)=>Promise<DbClientResult>;resolveSystemLifecycle:()=>Promise<{ok:true;href:string}|{ok:false;reason_code:string}>};
let binding:DbClientBindings|null=null;
export function configureDbClientRuntime(next:DbClientBindings){binding=next;}
function controlledClientMode(){return process.env.NEXT_PUBLIC_ACPOS_RUNTIME_MODE==="CONTROLLED_TEST";}
export function isDbClientRuntimeBound(){return binding!==null||controlledClientMode();}
function rec(v:unknown):Record<string,unknown>|null{return typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:null;}
function items(v:unknown):DbProjectionItem[]{return Array.isArray(v)?v.flatMap(x=>{const r=rec(x);return r&&typeof r.ref==="string"?[{ref:r.ref,label:typeof r.label==="string"?r.label:r.ref,meta:rec(r.meta)??undefined}]:[]}):[];}
const STATES=new Set(["LOADING","READY","EMPTY","ERROR","POLICY_BLOCKED","VERSION_CONFLICT","READ_ONLY","ARCHIVED"]);
export function normalizeDbProjection(raw:unknown):DbNormalizedProjection{let root=rec(raw)??{};const nested=rec(root.value);if(nested&&("page_state"in nested||"values"in nested))root=nested;const page_state=typeof root.page_state==="string"&&STATES.has(root.page_state)?root.page_state:null;if(!page_state)throw new Error("DB_PROJECTION_PAGE_STATE_INVALID");const values=rec(root.values)??{},g=rec(root.gates)??{},filtersRaw=rec(root.filters)??{},listsRaw=rec(root.lists)??{},tablesRaw=rec(root.tables)??{};const gates:Record<string,boolean>={},lists:Record<string,DbProjectionItem[]>={},filters:Record<string,DbProjectionItem[]>={},tables:Record<string,unknown[]>={};for(const[k,v]of Object.entries(g))if(typeof v==="boolean")gates[k]=v;for(const[k,v]of Object.entries(listsRaw))lists[k]=items(v);for(const[k,v]of Object.entries(filtersRaw))filters[k]=items(v);for(const[k,v]of Object.entries(tablesRaw))if(Array.isArray(v))tables[k]=v;return{page_state,values:{...values},lists,tables,gates,filters,graph:root.graph??null,trace:root.trace??null,audit:root.audit??null,source_sync:typeof root.source_sync==="string"?root.source_sync:null};}
function errorForStatus(status:number):DbErrorUid{return status===403?'DB-01-ERR-PERM-001':status===409?'DB-01-ERR-VERSION-001':'DB-01-ERR-CONTEXT-001';}
async function fetchProjection():Promise<DbClientResult>{let response:Response;try{response=await fetch('/v1/ui-projections/admin%3ADB-01',{method:'GET',cache:'no-store'});}catch{return{ok:false,error_uid:'DB-01-ERR-CONTEXT-001',reason_code:'DB_PROJECTION_REQUEST_FAILED',correlation_id:'unresolved'}}const correlation_id=response.headers.get('x-correlation-id')??'unresolved',raw:unknown=await response.json().catch(()=>null);if(!response.ok){const body=rec(raw),reason_code=typeof body?.reason_code==='string'?body.reason_code:'DB_PROJECTION_READ_FAILED';return{ok:false,error_uid:errorForStatus(response.status),reason_code,correlation_id:typeof body?.correlation_id==='string'?body.correlation_id:correlation_id}}try{return{ok:true,projection:normalizeDbProjection(raw),correlation_id}}catch{return{ok:false,error_uid:'DB-01-ERR-CONTEXT-001',reason_code:'DB_PROJECTION_CONTRACT_REJECTED',correlation_id}}}
export async function readDbProjection():Promise<DbClientResult>{if(binding){try{return await binding.readProjection();}catch{return{ok:false,error_uid:'DB-01-ERR-CONTEXT-001',reason_code:'DB_PROJECTION_READ_FAILED',correlation_id:'unresolved'}}}return fetchProjection();}
export async function invokeDbRead(port_uid:DbReadPortUid,input:DbReadInput):Promise<DbClientResult>{if(binding){try{return await binding.read(port_uid,input);}catch{return{ok:false,error_uid:'DB-01-ERR-CONTEXT-001',reason_code:'DB_READ_MODEL_QUERY_FAILED',correlation_id:'unresolved'}}}if(controlledClientMode())return fetchProjection();return{ok:false,error_uid:'DB-01-ERR-CONTEXT-001',reason_code:'DB_READ_MODEL_RUNTIME_NOT_BOUND',correlation_id:'unresolved'};}
export async function openDbSystemLifecycle(){if(binding){try{return await binding.resolveSystemLifecycle();}catch{return{ok:false as const,reason_code:'SYSTEM_LIFECYCLE_ROUTE_RESOLUTION_FAILED'};}}return{ok:true as const,href:'/admin/system'};}
