import type{DbReadPortUid,DbErrorUid}from'./dbRuntimeContract';
export type DbProjectionItem={ref:string;label:string;meta?:Record<string,unknown>};
export type DbNormalizedProjection={page_state:string;values:Record<string,unknown>;lists:Record<string,DbProjectionItem[]>;tables:Record<string,unknown[]>;gates:Record<string,boolean>;filters:Record<string,DbProjectionItem[]>;graph:unknown;trace:unknown;audit:unknown;source_sync:string|null;};
export type DbReadInput={scope?:unknown;query?:unknown};
export type DbClientResult={ok:true;projection:DbNormalizedProjection;correlation_id:string}|{ok:false;error_uid:DbErrorUid;reason_code:string;correlation_id:string};
export type DbClientBindings={readProjection:()=>Promise<DbClientResult>;read:(port_uid:DbReadPortUid,input:DbReadInput)=>Promise<DbClientResult>;resolveSystemLifecycle:()=>Promise<{ok:true;href:string}|{ok:false;reason_code:string}>};
let overrideBinding:DbClientBindings|null=null;
export function configureDbClientRuntime(next:DbClientBindings){overrideBinding=next;}
function cid(){return typeof crypto!=="undefined"&&typeof crypto.randomUUID==="function"?crypto.randomUUID():`db-${Date.now()}`;}
function object(v:unknown):v is Record<string,unknown>{return Boolean(v)&&typeof v==="object"&&!Array.isArray(v);}
function normalize(v:unknown):DbNormalizedProjection|null{const candidate=object(v)&&object(v.projection)?v.projection:v;if(!object(candidate)||typeof candidate.page_state!=="string"||!object(candidate.values)||!object(candidate.lists)||!object(candidate.tables)||!object(candidate.gates)||!object(candidate.filters))return null;return candidate as DbNormalizedProjection;}
function bodyError(v:unknown,fallback:DbErrorUid,reason:string,correlation_id:string):DbClientResult{const o=object(v)?v:{};return{ok:false,error_uid:String(o.error_uid??fallback)as DbErrorUid,reason_code:String(o.reason_code??reason),correlation_id:String(o.correlation_id??correlation_id)};}
function errorFor(port_uid:DbReadPortUid):DbErrorUid{return port_uid==="DB-01-PORT-ENTITY-LIST"?"DB-01-ERR-ENTITY-001":port_uid==="DB-01-PORT-SCHEMA"?"DB-01-ERR-SCHEMA-001":port_uid==="DB-01-PORT-TRACE"?"DB-01-ERR-TRACE-001":port_uid==="DB-01-PORT-MIGRATION"?"DB-01-ERR-MIGRATION-001":port_uid==="DB-01-PORT-INTEGRITY"?"DB-01-ERR-INTEGRITY-001":"DB-01-ERR-AUDIT-001";}
async function httpProjection():Promise<DbClientResult>{const correlation_id=cid();let r:Response;try{r=await fetch("/v1/ui-projections/DB-01",{method:"GET",headers:{accept:"application/json","x-correlation-id":correlation_id},cache:"no-store"});}catch{return{ok:false,error_uid:"DB-01-ERR-CONTEXT-001",reason_code:"DB_PROJECTION_REQUEST_FAILED",correlation_id};}let body:unknown=null;try{body=await r.json();}catch{}const resolved=r.headers.get("x-correlation-id")??correlation_id;if(!r.ok)return bodyError(body,"DB-01-ERR-CONTEXT-001",`HTTP_${r.status}`,resolved);const projection=normalize(body);return projection?{ok:true,projection,correlation_id:resolved}:{ok:false,error_uid:"DB-01-ERR-CONTEXT-001",reason_code:"INVALID_DB_PROJECTION",correlation_id:resolved};}
async function httpRead(port_uid:DbReadPortUid,input:DbReadInput):Promise<DbClientResult>{const correlation_id=cid();let r:Response;try{r=await fetch("/v1/database/read-model",{method:"POST",headers:{"content-type":"application/json",accept:"application/json","x-correlation-id":correlation_id},body:JSON.stringify({port_uid,scope:input.scope,query:input.query}),cache:"no-store"});}catch{return{ok:false,error_uid:errorFor(port_uid),reason_code:"DB_READ_MODEL_REQUEST_FAILED",correlation_id};}let body:unknown=null;try{body=await r.json();}catch{}const resolved=r.headers.get("x-correlation-id")??correlation_id;if(!r.ok)return bodyError(body,errorFor(port_uid),`HTTP_${r.status}`,resolved);const projection=normalize(body);return projection?{ok:true,projection,correlation_id:resolved}:{ok:false,error_uid:errorFor(port_uid),reason_code:"INVALID_DB_READ_MODEL_PROJECTION",correlation_id:resolved};}
const httpBinding:DbClientBindings={readProjection:httpProjection,read:httpRead,resolveSystemLifecycle:async()=>({ok:true,href:"/admin/system"})};
function active(){return overrideBinding??httpBinding;}
export function isDbClientRuntimeBound(){return true;}
export async function readDbProjection():Promise<DbClientResult>{try{return await active().readProjection();}catch{return{ok:false,error_uid:'DB-01-ERR-CONTEXT-001',reason_code:'DB_PROJECTION_READ_FAILED',correlation_id:'unresolved'};}}
export async function invokeDbRead(port_uid:DbReadPortUid,input:DbReadInput):Promise<DbClientResult>{try{return await active().read(port_uid,input);}catch{return{ok:false,error_uid:errorFor(port_uid),reason_code:'DB_READ_MODEL_QUERY_FAILED',correlation_id:'unresolved'};}}
export async function openDbSystemLifecycle(){try{return await active().resolveSystemLifecycle();}catch{return{ok:false as const,reason_code:'SYSTEM_LIFECYCLE_ROUTE_RESOLUTION_FAILED'};}}
