import{NextRequest,NextResponse}from"next/server";
import{executeDepartmentOperation,type DepartmentOperationId}from"./departmentOperationRuntime";
import{ASSET_ACTION_PORT,ASSET_ACTION_UIDS,type AssetActionUid,type AssetPortUid}from"@/domain/asset/assetRuntimeContract";import{executeAssetPort}from"@/server/asset/assetRuntime";
import{VIDEO_ACTION_PORT,VIDEO_ACTION_UIDS,type VideoActionUid,type VideoPortUid}from"@/domain/video/videoRuntimeContract";import{executeVideoPort}from"@/server/video/videoRuntime";
import{EDIT_CONTROL_BINDINGS}from"@/domain/edit/editControlBindings";import{executeControlledEditDepartmentOperation,isControlledEditServerTestMode}from"@/server/testing/controlledEditTestRuntime";
import{QA_ACTION_REGISTRY}from"@/domain/qa/qaControlBindings";import{executeControlledQaDepartmentOperation,isControlledQaServerTestMode}from"@/server/testing/controlledQaTestRuntime";
type Ctx={params:Promise<Record<string,string>>};function cid(r:NextRequest){const v=r.headers.get("x-correlation-id");return v&&v.trim()?v:crypto.randomUUID();}function error(correlation_id:string,status:number,reason_code:string,error_uid?:string){return NextResponse.json({reason_code,correlation_id,...(error_uid?{error_uid}:{})},{status,headers:{"x-correlation-id":correlation_id,"cache-control":"no-store"}});}
const ASSET_OPERATION_PORTS:Record<DepartmentOperationId,readonly AssetPortUid[]>={requestTaskExecution:["ASSET-01-PORT-EXECUTE"],retryTaskExecution:["ASSET-01-PORT-RETRY"],createFinding:["ASSET-01-PORT-FINDING"],createCorrectionRequest:["ASSET-01-PORT-CORRECTION"],decideOutputCandidate:["ASSET-01-PORT-DECISION"],submitScorecard:["ASSET-01-PORT-SCORECARD"],createDepartmentHandoff:["ASSET-01-PORT-IN-CORE-HANDOFF","ASSET-01-PORT-OUT-VIDEO"]};
const VIDEO_OPERATION_PORTS:Record<DepartmentOperationId,readonly VideoPortUid[]>={requestTaskExecution:["VIDEO-01-PORT-EXECUTE"],retryTaskExecution:["VIDEO-01-PORT-RETRY"],createFinding:["VIDEO-01-PORT-FINDING"],createCorrectionRequest:["VIDEO-01-PORT-CORRECTION"],decideOutputCandidate:["VIDEO-01-PORT-DECISION"],submitScorecard:["VIDEO-01-PORT-SCORECARD"],createDepartmentHandoff:["VIDEO-01-PORT-IN-ASSET-HANDOFF","VIDEO-01-PORT-OUT-EDIT"]};
async function assetDispatch(operation_id:DepartmentOperationId,r:NextRequest,path_params:Record<string,string>,payload:unknown,correlation_id:string){const raw=r.headers.get("x-asset-action-uid");if(!raw)return null;if(!ASSET_ACTION_UIDS.includes(raw as AssetActionUid))return{response:error(correlation_id,400,"UNKNOWN_ASSET_ACTION_UID","ASSET-01-ERR-CONTEXT-001")};const action_uid=raw as AssetActionUid,port_uid=ASSET_ACTION_PORT[action_uid];if(!port_uid||!ASSET_OPERATION_PORTS[operation_id].includes(port_uid))return{response:error(correlation_id,400,"ACTION_PORT_BINDING_MISMATCH","ASSET-01-ERR-CONTEXT-001")};const result=await executeAssetPort({port_uid,action_uid,correlation_id,path_params,payload});if(!result.ok)return{response:error(correlation_id,result.status,result.reason_code,result.error_uid)};return{response:NextResponse.json(result.value,{status:200,headers:{"x-correlation-id":correlation_id,"cache-control":"no-store"}})};}
async function videoDispatch(operation_id:DepartmentOperationId,r:NextRequest,path_params:Record<string,string>,payload:unknown,correlation_id:string){const raw=r.headers.get("x-video-action-uid");if(!raw)return null;if(!VIDEO_ACTION_UIDS.includes(raw as VideoActionUid))return{response:error(correlation_id,400,"UNKNOWN_VIDEO_ACTION_UID","VIDEO-01-ERR-CONTEXT-001")};const action_uid=raw as VideoActionUid,port_uid=VIDEO_ACTION_PORT[action_uid];if(!port_uid||!VIDEO_OPERATION_PORTS[operation_id].includes(port_uid))return{response:error(correlation_id,400,"ACTION_PORT_BINDING_MISMATCH","VIDEO-01-ERR-CONTEXT-001")};const result=await executeVideoPort({port_uid,action_uid,correlation_id,path_params,payload});if(!result.ok)return{response:error(correlation_id,result.status,result.reason_code,result.error_uid)};return{response:NextResponse.json(result.value,{status:200,headers:{"x-correlation-id":correlation_id,"cache-control":"no-store"}})};}
function editActionExists(action_uid:string){return Object.values(EDIT_CONTROL_BINDINGS).some(binding=>binding.action_uid===action_uid);}
async function editDispatch(operation_id:DepartmentOperationId,r:NextRequest,path_params:Record<string,string>,payload:unknown,correlation_id:string){const raw=r.headers.get("x-edit-action-uid");if(!raw)return null;if(!isControlledEditServerTestMode())return null;if(!editActionExists(raw))return{response:error(correlation_id,400,"UNKNOWN_EDIT_ACTION_UID","EDIT-01-ERR-CONTEXT-001")};const allowed=(operation_id==="decideOutputCandidate"&&raw==="EDIT-01-ACT-STAGE-CONFIRM")||(operation_id==="submitScorecard"&&(raw==="EDIT-01-ACT-EVAL-RECHECK-FULL"||raw==="EDIT-01-ACT-EVAL-RECHECK-SELECTED"))||(operation_id==="createDepartmentHandoff"&&raw==="EDIT-01-ACT-RETURN-BLUEPRINT");if(!allowed)return{response:error(correlation_id,400,"EDIT_ACTION_OPERATION_BINDING_MISMATCH","EDIT-01-ERR-CONTEXT-001")};const result=await executeControlledEditDepartmentOperation({operation_id,correlation_id,path_params,payload});if(!result.ok)return{response:error(correlation_id,result.status,result.reason_code,result.error_uid)};return{response:NextResponse.json(result.value,{status:200,headers:{"x-correlation-id":correlation_id,"cache-control":"no-store"}})};}
async function qaDispatch(operation_id:DepartmentOperationId,r:NextRequest,path_params:Record<string,string>,payload:unknown,correlation_id:string){const raw=r.headers.get("x-qa-action-uid");if(!raw)return null;if(!isControlledQaServerTestMode())return null;if(!(raw in QA_ACTION_REGISTRY))return{response:error(correlation_id,400,"UNKNOWN_QA_ACTION_UID","QA-01-ERR-UNDEFINED-001")};const allowed=(operation_id==="submitScorecard"&&raw==="QA-01-ACT-SCORECARD-SUBMIT")||(operation_id==="createFinding"&&raw==="QA-01-ACT-FINDING-CREATE")||(operation_id==="createCorrectionRequest"&&raw==="QA-01-ACT-CORRECTION-REQUEST");if(!allowed)return{response:error(correlation_id,400,"QA_ACTION_OPERATION_BINDING_MISMATCH","QA-01-ERR-UNDEFINED-001")};const result=await executeControlledQaDepartmentOperation({operation_id,correlation_id,path_params,payload});if(!result.ok)return{response:error(correlation_id,result.status,result.reason_code,result.error_uid)};return{response:NextResponse.json(result.value,{status:200,headers:{"x-correlation-id":correlation_id,"cache-control":"no-store"}})};}
export function departmentPost(operation_id:DepartmentOperationId){return async(r:NextRequest,c:Ctx)=>{const correlation_id=cid(r),path_params=await c.params;let payload:unknown;try{payload=await r.json();}catch{return error(correlation_id,400,"INVALID_JSON_PAYLOAD");}const asset=await assetDispatch(operation_id,r,path_params,payload,correlation_id);if(asset)return asset.response;const video=await videoDispatch(operation_id,r,path_params,payload,correlation_id);if(video)return video.response;const edit=await editDispatch(operation_id,r,path_params,payload,correlation_id);if(edit)return edit.response;const qa=await qaDispatch(operation_id,r,path_params,payload,correlation_id);if(qa)return qa.response;const result=await executeDepartmentOperation({operation_id,correlation_id,path_params,payload});if(!result.ok)return error(correlation_id,result.status,result.reason_code);return NextResponse.json(result.value,{status:200,headers:{"x-correlation-id":correlation_id,"cache-control":"no-store"}});};}
