import{executeCorePort}from"@/server/core/coreRuntime";
import{isControlledCoreServerTestMode}from"@/server/testing/controlledCoreTestRuntime";
import{isControlledAssetServerTestMode,readControlledAssetTestProjection}from"@/server/testing/controlledAssetTestRuntime";
import{isControlledVideoServerTestMode,readControlledVideoTestProjection}from"@/server/testing/controlledVideoTestRuntime";
import{isControlledEditServerTestMode,readControlledEditTestProjection}from"@/server/testing/controlledEditTestRuntime";
import{isControlledQaServerTestMode,readControlledQaTestProjection}from"@/server/testing/controlledQaTestRuntime";
import{isControlledQaCriteriaServerTestMode,readControlledQaCriteriaTestProjection}from"@/server/testing/controlledQaCriteriaTestRuntime";
import{isControlledKnowledgeServerTestMode,readControlledKnowledgeTestProjection}from"@/server/testing/controlledKnowledgeTestRuntime";
import{isControlledStrategyServerTestMode,readControlledStrategyTestProjection}from"@/server/testing/controlledStrategyTestRuntime";
import{isControlledAiApiServerTestMode,readControlledAiApiTestProjection}from"@/server/testing/controlledAiApiTestRuntime";
import{isControlledSocServerTestMode,readControlledSocTestProjection}from"@/server/testing/controlledSocTestRuntime";
import{isControlledErpServerTestMode,readControlledErpTestProjection}from"@/server/testing/controlledErpTestRuntime";
import{isControlledDbServerTestMode,readControlledDbTestProjection}from"@/server/testing/controlledDbTestRuntime";
import{isControlledStrategyWorkspaceServerTestMode,readControlledStrategyWorkspaceProjection}from"@/server/testing/controlledStrategyWorkspaceTestRuntime";
import{isControlledInfoServerTestMode,readControlledInfoTestProjection}from"@/server/testing/controlledInfoTestRuntime";
import{isControlledIamServerTestMode,readControlledIamTestProjection}from"@/server/testing/controlledIamTestRuntime";
export type UiProjectionRequest={page_uid:string;correlation_id:string};export type UiProjectionBindings={authorize:(request:UiProjectionRequest)=>Promise<{allowed:true}|{allowed:false;reason_code?:string}>;read:(request:UiProjectionRequest)=>Promise<unknown>;audit:(entry:UiProjectionRequest&{outcome:"ALLOWED"|"DENIED"|"SUCCESS"|"ERROR";reason_code?:string})=>Promise<void>};let bindings:UiProjectionBindings|null=null;export function configureUiProjectionRuntime(next:UiProjectionBindings){bindings=next;}async function audit(runtime:UiProjectionBindings,entry:Parameters<UiProjectionBindings["audit"]>[0]){try{await runtime.audit(entry);}catch{/* fail closed */}}
async function controlledCoreProjection(request:UiProjectionRequest){if(request.page_uid!=="CORE-01"||!isControlledCoreServerTestMode())return null;const result=await executeCorePort({port_uid:"CORE-01-PORT-PROJECTION",correlation_id:request.correlation_id,path_params:{pageUid:request.page_uid}});if(!result.ok)return{ok:false as const,status:result.status,reason_code:result.reason_code,correlation_id:request.correlation_id};return{ok:true as const,value:result.value,correlation_id:request.correlation_id};}
function controlledAssetProjection(request:UiProjectionRequest){if(request.page_uid!=="ASSET-01"||!isControlledAssetServerTestMode())return null;return{ok:true as const,value:readControlledAssetTestProjection(),correlation_id:request.correlation_id};}
function controlledVideoProjection(request:UiProjectionRequest){if(request.page_uid!=="VIDEO-01"||!isControlledVideoServerTestMode())return null;return{ok:true as const,value:readControlledVideoTestProjection(),correlation_id:request.correlation_id};}
function controlledEditProjection(request:UiProjectionRequest){if(request.page_uid!=="EDIT-01"||!isControlledEditServerTestMode())return null;return{ok:true as const,value:readControlledEditTestProjection(),correlation_id:request.correlation_id};}
function controlledQaProjection(request:UiProjectionRequest){if(request.page_uid!=="QA-01"||!isControlledQaServerTestMode())return null;return{ok:true as const,value:readControlledQaTestProjection(),correlation_id:request.correlation_id};}
function controlledQaCriteriaProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:SG-02"||!isControlledQaCriteriaServerTestMode())return null;return{ok:true as const,value:readControlledQaCriteriaTestProjection(),correlation_id:r.correlation_id};}
function controlledKnowledgeProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:KB-01"||!isControlledKnowledgeServerTestMode())return null;return{ok:true as const,value:readControlledKnowledgeTestProjection(),correlation_id:r.correlation_id};}
function controlledStrategyAdminProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:STR-01"||!isControlledStrategyServerTestMode())return null;return{ok:true as const,value:readControlledStrategyTestProjection(),correlation_id:r.correlation_id};}
function controlledAiApiProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:AIAPI-01"||!isControlledAiApiServerTestMode())return null;return{ok:true as const,value:readControlledAiApiTestProjection(),correlation_id:r.correlation_id};}
function controlledSocProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:SOC-01"||!isControlledSocServerTestMode())return null;return{ok:true as const,value:readControlledSocTestProjection(),correlation_id:r.correlation_id};}
function controlledErpProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:ERP-01"||!isControlledErpServerTestMode())return null;return{ok:true as const,value:readControlledErpTestProjection(),correlation_id:r.correlation_id};}
function controlledDbProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:DB-01"||!isControlledDbServerTestMode())return null;return{ok:true as const,value:readControlledDbTestProjection(),correlation_id:r.correlation_id};}
function controlledStrategyWorkspaceProjection(r:UiProjectionRequest){if(r.page_uid!=="workspace:STR-01"||!isControlledStrategyWorkspaceServerTestMode())return null;return{ok:true as const,value:readControlledStrategyWorkspaceProjection(),correlation_id:r.correlation_id};}
function controlledInfoProjection(r:UiProjectionRequest){if(r.page_uid!=="workspace:INFO-01"||!isControlledInfoServerTestMode())return null;return{ok:true as const,value:readControlledInfoTestProjection(),correlation_id:r.correlation_id};}
function controlledIamProjection(r:UiProjectionRequest){if(r.page_uid!=="admin:IAM-01"||!isControlledIamServerTestMode())return null;return{ok:true as const,value:readControlledIamTestProjection(),correlation_id:r.correlation_id};}
export async function getUiProjection(request:UiProjectionRequest){const runtime=bindings;if(!runtime){const coreProjection=await controlledCoreProjection(request);if(coreProjection)return coreProjection;const assetProjection=controlledAssetProjection(request);if(assetProjection)return assetProjection;const videoProjection=controlledVideoProjection(request);if(videoProjection)return videoProjection;const editProjection=controlledEditProjection(request);if(editProjection)return editProjection;const qaProjection=controlledQaProjection(request);if(qaProjection)return qaProjection;const sg=controlledQaCriteriaProjection(request);if(sg)return sg;const kb=controlledKnowledgeProjection(request);if(kb)return kb;const st=controlledStrategyAdminProjection(request);if(st)return st;const ai=controlledAiApiProjection(request);if(ai)return ai;const soc=controlledSocProjection(request);if(soc)return soc;const erp=controlledErpProjection(request);if(erp)return erp;const db=controlledDbProjection(request);if(db)return db;const strws=controlledStrategyWorkspaceProjection(request);if(strws)return strws;const info=controlledInfoProjection(request);if(info)return info;const iam=controlledIamProjection(request);if(iam)return iam;return{ok:false as const,status:503,reason_code:"UI_PROJECTION_RUNTIME_NOT_BOUND",correlation_id:request.correlation_id};}let decision:Awaited<ReturnType<UiProjectionBindings["authorize"]>>;try{decision=await runtime.authorize(request);}catch{return{ok:false as const,status:403,reason_code:"AUTHORIZATION_EVALUATION_FAILED",correlation_id:request.correlation_id};}if(!decision.allowed){const reason_code=decision.reason_code??"PERMISSION_OR_SCOPE_DENIED";await audit(runtime,{...request,outcome:"DENIED",reason_code});return{ok:false as const,status:403,reason_code,correlation_id:request.correlation_id};}await audit(runtime,{...request,outcome:"ALLOWED"});try{const value=await runtime.read(request);await audit(runtime,{...request,outcome:"SUCCESS"});return{ok:true as const,value,correlation_id:request.correlation_id};}catch{await audit(runtime,{...request,outcome:"ERROR",reason_code:"UI_PROJECTION_READ_FAILED"});return{ok:false as const,status:503,reason_code:"UI_PROJECTION_READ_FAILED",correlation_id:request.correlation_id};}}
