import{isControlledTestMode}from"@/domain/testing/controlledTestData";
import type{QaClientState,QaResolvedContext}from"./qaClientState";
import{QA_ACTION_REGISTRY,type QaActionUid}from"./qaControlBindings";
import{invokeQaIntegrationPort,type QaPortInvokeResult}from"./qaClientPort";
import{runQaAutoTopicServerAction,runQaManualReviewServerAction}from"@/app/qa/actions";
export type QaActionResult={ok:true;value:unknown;projection?:QaResolvedContext;correlation_id:string|null}|{ok:false;error_uid:string;reason_code:string;correlation_id:string|null;status?:number};
function projectionOf(v:unknown):QaResolvedContext|undefined{if(!v||typeof v!=="object")return;const p=(v as{projection?:unknown}).projection;return p&&typeof p==="object"?p as QaResolvedContext:undefined;}
function fromPort(r:QaPortInvokeResult):QaActionResult{return r.ok?{ok:true,value:r.value,projection:projectionOf(r.value),correlation_id:r.correlation_id}:{ok:false,error_uid:r.error_uid,reason_code:r.reason_code,correlation_id:r.correlation_id,status:r.status};}
function port(action_uid:QaActionUid,state:QaClientState,payload:Record<string,unknown>={}){const binding=QA_ACTION_REGISTRY[action_uid].runtime_binding;if(!("port_uid"in binding))return Promise.resolve<QaActionResult>({ok:false,error_uid:"QA-01-ERR-UNDEFINED-001",reason_code:"QA_ACTION_HAS_NO_SOURCE_PORT",correlation_id:null});return invokeQaIntegrationPort({port_uid:binding.port_uid,action_uid,payload:{...payload,qa_review_id:state.resolved.qa_review_ref,qa_task_ref:state.resolved.qa_task_ref,target_output_version_id:state.resolved.target_output_version_id}}).then(fromPort);}
async function scoreAndDispatch(state:QaClientState,projection:QaResolvedContext):Promise<QaActionResult>{const s={...state,resolved:projection};const score=await port("QA-01-ACT-SCORECARD-SUBMIT",s,{criteria_version_ref:projection.values["QA-01-FLD-CRITERIA-VERSION"],qa_validation_script_ref:projection.values["QA-01-FLD-QA-SCRIPT"],evidence_ref:projection.values["QA-01-FLD-EVIDENCE"],scorer:"SYSTEM_AI",provider_execution:"SIMULATED_EXTERNAL"});if(!score.ok)return score;const p=score.projection??projection;if(p.gate_state["QA-01-GATE-FAIL"]){return port("QA-01-ACT-GATE-FAIL",{...state,resolved:p},{scorecard_ref:p.scorecard_ref,system_dispatch:true});}if(p.gate_state["QA-01-GATE-PASS"]){return port("QA-01-ACT-GATE-PASS",{...state,resolved:p},{scorecard_ref:p.scorecard_ref,system_dispatch:true});}return{...score,projection:p};}
export async function invokeQaFormalAction(action_uid:QaActionUid,state:QaClientState):Promise<QaActionResult>{if(!(action_uid in QA_ACTION_REGISTRY))return{ok:false,error_uid:"QA-01-ERR-UNDEFINED-001",reason_code:"UNREGISTERED_QA_ACTION",correlation_id:null};
 if(action_uid==="QA-01-ACT-AUTO-START"){const topic=state.resolved.topic_id;if(!topic)return{ok:false,error_uid:"QA-01-ERR-AUTO-001",reason_code:"EXACT_TOPIC_REQUIRED",correlation_id:null};const r=await runQaAutoTopicServerAction(topic);return r.ok?{ok:true,value:r,projection:projectionOf(r),correlation_id:null}:{ok:false,error_uid:"QA-01-ERR-AUTO-001",reason_code:r.reason_code,correlation_id:null};}
 if(action_uid==="QA-01-ACT-MANUAL-MODIFY"||action_uid==="QA-01-ACT-MANUAL-PASS"){const c=state.resolved.manual_review_case_ref;if(!c)return{ok:false,error_uid:"QA-01-ERR-MANUAL-ACTION-001",reason_code:"MANUAL_REVIEW_CASE_REQUIRED",correlation_id:null};const op=action_uid==="QA-01-ACT-MANUAL-MODIFY"?"manualReview.modify":"manualReview.pass";const r=await runQaManualReviewServerAction(op,c,{qa_review_ref:state.resolved.qa_review_ref});if(!r.ok)return{ok:false,error_uid:r.error_uid,reason_code:r.reason_code,correlation_id:r.correlation_id};const p=projectionOf(r.value);return{ok:true,value:r.value,projection:p,correlation_id:r.correlation_id};}
 if(action_uid==="QA-01-ACT-START-REVIEW"){const r=await port(action_uid,state,{project_id:state.resolved.project_id,topic_id:state.resolved.topic_id,output_version_id:state.resolved.target_output_version_id,qa_profile_id:state.resolved.values["QA-01-FLD-CRITERIA-VERSION"]});if(!r.ok||!isControlledTestMode()||!r.projection)return r;return scoreAndDispatch(state,r.projection);}
 if(action_uid==="QA-01-ACT-CORRECTION-REQUEST")return port(action_uid,state,{finding_refs:state.resolved.lists["QA-01-LIST-FINDINGS"]?.map(x=>x.ref)??[],scorecard_refs:state.resolved.scorecard_ref?[state.resolved.scorecard_ref]:[],source_instruction_ref:state.resolved.values["QA-01-INP-CORR-INSTRUCTION"],failed_output_version_id:state.resolved.failed_output_version_id??state.resolved.target_output_version_id,affected_scope:state.correction_scope,root_cause:state.correction_root,required_action:state.correction_action,target_department:state.resolved.values["QA-01-INP-CORR-TARGET"],revalidation_scope:state.correction_revalidate});
 if(action_uid==="QA-01-ACT-RECHECK-START"){const r=await port(action_uid,state,{failed_output_version_id:state.resolved.failed_output_version_id,verified_new_output_version_id:state.resolved.verified_new_output_version_id});if(!r.ok||!isControlledTestMode()||!r.projection)return r;return scoreAndDispatch(state,r.projection);}
 if(action_uid==="QA-01-ACT-RELEASE-CREATE")return port(action_uid,state,{output_version_ids:[state.resolved.target_output_version_id],qa_gate_ref:state.resolved.values["QA-01-FLD-REL-QA-GATE"],rights_gate_ref:state.resolved.values["QA-01-FLD-REL-RIGHTS-GATE"],channel_policy_ref:state.resolved.values["QA-01-FLD-REL-CHANNEL"],candidate_only:true,publish:false});
 if(action_uid==="QA-01-ACT-FINDING-CREATE")return port(action_uid,state,{severity:state.finding_severity,category:state.finding_category,affected_scope:state.finding_scope,evidence_point:state.evidence_point,evidence_range:[state.evidence_range_in,state.evidence_range_out],output_version_id:state.resolved.target_output_version_id});
 if(action_uid==="QA-01-ACT-SCORECARD-SUBMIT"||action_uid==="QA-01-ACT-GATE-PASS"||action_uid==="QA-01-ACT-GATE-FAIL")return port(action_uid,state);
 return{ok:false,error_uid:"QA-01-ERR-UNDEFINED-001",reason_code:"QA_ACTION_NOT_FORMAL_RUNTIME_BOUND",correlation_id:null};}
