export type QaReviewMode="AUTO"|"MANUAL";
export type QaListItem={ref:string;label:string;meta?:Record<string,string|number|boolean|null>};
export type QaTestMetadata={data_classification:"TEST_ONLY";synthetic:true;test_dataset_id:string;test_run_id:string;created_for_validation:true;production_eligible:false};
export type QaResolvedContext={
  page_state_uid:string;current_stage_uid:string;project_id:string|null;topic_id:string|null;qa_task_ref:string|null;target_output_version_id:string|null;qa_review_ref:string|null;
  viewer_uri:string|null;failed_output_version_id:string|null;verified_new_output_version_id:string|null;manual_review_case_ref:string|null;scorecard_ref:string|null;release_package_ref:string|null;
  values:Record<string,string|number|boolean|null>;lists:Record<string,QaListItem[]>;gate_state:Record<string,boolean>;correlation_id:string|null;audit_ref:string|null;test_metadata?:QaTestMetadata;
};
export const EMPTY_QA_RESOLVED_CONTEXT:QaResolvedContext={page_state_uid:"QA-01-ST-NOT-STARTED",current_stage_uid:"QA-01-STAGE-01-RESOLVE",project_id:null,topic_id:null,qa_task_ref:null,target_output_version_id:null,qa_review_ref:null,viewer_uri:null,failed_output_version_id:null,verified_new_output_version_id:null,manual_review_case_ref:null,scorecard_ref:null,release_package_ref:null,values:{},lists:{},gate_state:{},correlation_id:null,audit_ref:null};
export type QaClientState={
  mode:QaReviewMode;queue_search:string;queue_state:string|null;queue_severity:string|null;queue_source_department:string|null;review_ref:string|null;playing:boolean;seek:number|null;muted:boolean;fullscreen:boolean;compare:boolean;current_timecode:number|null;evidence_point:number|null;evidence_range_in:number|null;evidence_range_out:number|null;finding_ref:string|null;manual_review_open:boolean;
  finding_severity:string;finding_category:string;finding_scope:string;correction_scope:string;correction_root:string;correction_action:string;correction_revalidate:string[];
  resolved:QaResolvedContext;busy_action:string|null;last_action_uid:string|null;last_action_result:string|null;runtime_error:string|null;active_view_action:string|null;
};
export const INITIAL_QA_CLIENT_STATE:QaClientState={mode:"AUTO",queue_search:"",queue_state:null,queue_severity:null,queue_source_department:null,review_ref:null,playing:false,seek:null,muted:false,fullscreen:false,compare:false,current_timecode:null,evidence_point:null,evidence_range_in:null,evidence_range_out:null,finding_ref:null,manual_review_open:false,finding_severity:"",finding_category:"",finding_scope:"",correction_scope:"",correction_root:"",correction_action:"",correction_revalidate:[],resolved:EMPTY_QA_RESOLVED_CONTEXT,busy_action:null,last_action_uid:null,last_action_result:null,runtime_error:null,active_view_action:null};
export type QaClientAction=
  |{type:"BIND_RESOLVED_CONTEXT";value:QaResolvedContext}|{type:"MODE";value:QaReviewMode}|{type:"QUEUE_SEARCH";value:string}|{type:"QUEUE_STATE";value:string|null}|{type:"QUEUE_SEVERITY";value:string|null}|{type:"QUEUE_SOURCE";value:string|null}|{type:"REVIEW_SELECT";value:string|null}
  |{type:"PLAY"}|{type:"SEEK";value:number}|{type:"MUTE"}|{type:"FULLSCREEN";value:boolean}|{type:"COMPARE"}|{type:"TIMECODE";value:number}|{type:"EVIDENCE_POINT";value:number|null}|{type:"EVIDENCE_IN";value:number|null}|{type:"EVIDENCE_OUT";value:number|null}|{type:"FINDING_SELECT";value:string|null}|{type:"MANUAL_VIEW";value:boolean}
  |{type:"FINDING_SEVERITY";value:string}|{type:"FINDING_CATEGORY";value:string}|{type:"FINDING_SCOPE";value:string}|{type:"CORRECTION_SCOPE";value:string}|{type:"CORRECTION_ROOT";value:string}|{type:"CORRECTION_ACTION";value:string}|{type:"CORRECTION_REVALIDATE";value:string[]}
  |{type:"BUSY";value:string|null}|{type:"RUNTIME_ERROR";value:string|null;correlation_id?:string|null}|{type:"RUNTIME_RESULT";action_uid:string;result:string}|{type:"VIEW_ACTION";action_uid:string};
export function reduceQaClientState(s:QaClientState,a:QaClientAction):QaClientState{switch(a.type){
  case"BIND_RESOLVED_CONTEXT":return{...s,resolved:a.value,review_ref:a.value.qa_review_ref??s.review_ref,correction_scope:String(a.value.values["QA-01-INP-CORR-SCOPE"]??s.correction_scope),correction_root:String(a.value.values["QA-01-INP-CORR-ROOT"]??s.correction_root),correction_revalidate:a.value.lists["QA-01-INP-CORR-REVALIDATE"]?.map(x=>x.ref)??s.correction_revalidate};
  case"MODE":return{...s,mode:a.value};case"QUEUE_SEARCH":return{...s,queue_search:a.value};case"QUEUE_STATE":return{...s,queue_state:a.value};case"QUEUE_SEVERITY":return{...s,queue_severity:a.value};case"QUEUE_SOURCE":return{...s,queue_source_department:a.value};case"REVIEW_SELECT":return{...s,review_ref:a.value,compare:false,evidence_point:null,evidence_range_in:null,evidence_range_out:null,finding_ref:null,manual_review_open:false};
  case"PLAY":return{...s,playing:!s.playing};case"SEEK":return{...s,seek:a.value,current_timecode:a.value};case"MUTE":return{...s,muted:!s.muted};case"FULLSCREEN":return{...s,fullscreen:a.value};case"COMPARE":return{...s,compare:!s.compare};case"TIMECODE":return{...s,current_timecode:a.value};case"EVIDENCE_POINT":return{...s,evidence_point:a.value};case"EVIDENCE_IN":return{...s,evidence_range_in:a.value};case"EVIDENCE_OUT":return{...s,evidence_range_out:a.value};case"FINDING_SELECT":return{...s,finding_ref:a.value};case"MANUAL_VIEW":return{...s,manual_review_open:a.value};
  case"FINDING_SEVERITY":return{...s,finding_severity:a.value};case"FINDING_CATEGORY":return{...s,finding_category:a.value};case"FINDING_SCOPE":return{...s,finding_scope:a.value};case"CORRECTION_SCOPE":return{...s,correction_scope:a.value};case"CORRECTION_ROOT":return{...s,correction_root:a.value};case"CORRECTION_ACTION":return{...s,correction_action:a.value};case"CORRECTION_REVALIDATE":return{...s,correction_revalidate:a.value};
  case"BUSY":return{...s,busy_action:a.value};case"RUNTIME_ERROR":return{...s,runtime_error:a.value,resolved:a.correlation_id===undefined?s.resolved:{...s.resolved,correlation_id:a.correlation_id}};case"RUNTIME_RESULT":return{...s,last_action_uid:a.action_uid,last_action_result:a.result};case"VIEW_ACTION":return{...s,active_view_action:a.action_uid,last_action_uid:a.action_uid,last_action_result:"VIEW_BOUND"};
}}
