export const ERP_SECTION_UIDS = [
  "ERP-01-SEC-01","ERP-01-SEC-02","ERP-01-SEC-03","ERP-01-SEC-04",
  "ERP-01-SEC-05","ERP-01-SEC-06","ERP-01-SEC-07","ERP-01-SEC-08",
] as const;

export const ERP_CONTROL_UIDS = [
  "ERP-01-FLD-SCOPE","ERP-01-FLD-SNAPSHOT","ERP-01-FLD-FRESHNESS",
  "ERP-01-BTN-TAB-FINANCE","ERP-01-BTN-TAB-CONNECTOR","ERP-01-BTN-TAB-SYNC",
  "ERP-01-FLD-FIN-COST","ERP-01-FLD-FIN-REVENUE","ERP-01-FLD-FIN-CASHFLOW","ERP-01-FLD-FIN-CAPACITY","ERP-01-FLD-FIN-FORECAST","ERP-01-FLD-FIN-GUARDRAILS","ERP-01-FLD-FIN-RECOMMENDATION-BOUNDARY",
  "ERP-01-BTN-FACTPACK","ERP-01-BTN-GUARDRAILS","ERP-01-BTN-FORECAST","ERP-01-BTN-EXPORT",
  "ERP-01-FLD-CONN-CONNECTOR-ID","ERP-01-FLD-CONN-PROVIDER-KEY","ERP-01-FLD-CONN-ADAPTER-KEY","ERP-01-FLD-CONN-SECRET-REFERENCE-ID","ERP-01-FLD-CONN-ENTITY-SCOPE","ERP-01-FLD-CONN-CONNECTION-STATUS","ERP-01-FLD-CONN-MAPPING-VERSION",
  "ERP-01-BTN-CONNECTOR-CREATE","ERP-01-BTN-CONNECTOR-UPDATE","ERP-01-BTN-CONNECTOR-VALIDATE","ERP-01-BTN-MAPPING-VALIDATE",
  "ERP-01-FLD-SYNC-SNAPSHOT-ID","ERP-01-FLD-SYNC-FRESHNESS-AT","ERP-01-FLD-SYNC-CURRENCY-TIMEZONE","ERP-01-FLD-SYNC-COMPLETENESS","ERP-01-FLD-SYNC-LAST-SYNC-STATUS","ERP-01-FLD-SYNC-FAILURE-ID",
  "ERP-01-BTN-SNAPSHOT-REFRESH","ERP-01-BTN-SYNC-CREATE","ERP-01-BTN-SYNC-STATUS","ERP-01-BTN-SYNC-RETRY","ERP-01-BTN-FAILURE-GET",
  "ERP-01-FLD-READINESS","ERP-01-FLD-AUDIT-REF","ERP-01-BTN-DETAIL",
] as const;

export const ERP_ACTION_UIDS = [
  "ERP-01-ACT-READ","ERP-01-ACT-READ-FINANCE","ERP-01-ACT-READ-CONNECTOR","ERP-01-ACT-READ-SYNC",
  "ERP-01-ACT-VIEW-FINANCE","ERP-01-ACT-VIEW-CONNECTOR","ERP-01-ACT-VIEW-SYNC",
  "ERP-01-ACT-FACTPACK","ERP-01-ACT-GUARDRAILS","ERP-01-ACT-FORECAST","ERP-01-ACT-EXPORT",
  "ERP-01-ACT-CONNECTOR-CREATE","ERP-01-ACT-CONNECTOR-UPDATE","ERP-01-ACT-CONNECTOR-VALIDATE","ERP-01-ACT-MAPPING-VALIDATE",
  "ERP-01-ACT-SNAPSHOT-REFRESH","ERP-01-ACT-SYNC-CREATE","ERP-01-ACT-SYNC-STATUS","ERP-01-ACT-SYNC-RETRY","ERP-01-ACT-FAILURE-GET","ERP-01-ACT-DETAIL-OPEN",
] as const;

export const ERP_GATE_UIDS = [
  "ERP-01-GATE-PAGE","ERP-01-GATE-FINANCE","ERP-01-GATE-CONNECTOR-READ","ERP-01-GATE-CONNECTOR-WRITE","ERP-01-GATE-CONNECTOR-VALIDATE",
  "ERP-01-GATE-MAPPING-VALIDATE","ERP-01-GATE-SYNC-READ","ERP-01-GATE-SNAPSHOT-REFRESH","ERP-01-GATE-SYNC-CREATE","ERP-01-GATE-SYNC-RETRY",
] as const;

export const ERP_PERMISSION_UIDS = ["ERP-01-PERM-READ","ERP-01-PERM-FINANCE","ERP-01-PERM-CONNECTOR","ERP-01-PERM-SYNC"] as const;

export const ERP_ACCOUNT_PERMISSIONS = [
  "erp.connector.read","erp.connector.write","erp.connector.validate","erp.mapping.validate",
  "erp.sync.request","erp.sync.retry","erp.snapshot.read","finance.read",
] as const;

export const ERP_ERROR_UIDS = [
  "ERP-01-ERR-AUTH","ERP-01-ERR-SECRET","ERP-01-ERR-VERSION","ERP-01-ERR-CONNECTOR",
  "ERP-01-ERR-SYNC","ERP-01-ERR-FINANCE","ERP-01-ERR-UNREGISTERED-WRITE","ERP-01-ERR-UNDEFINED",
] as const;

export const ERP_PAGE_STATES = [
  "LOADING","READY","EMPTY","ERROR","POLICY_BLOCKED","VERSION_CONFLICT","REVIEW_REQUIRED","EXTERNAL_PENDING","READ_ONLY","ARCHIVED",
  "CONNECTOR_UNCONFIGURED","CONNECTOR_CONFIGURING","CONNECTOR_VALIDATING","CONNECTOR_READY","CONNECTOR_DEGRADED",
  "SNAPSHOT_STALE","SNAPSHOT_SYNCING","SNAPSHOT_FAILED","DATA_INCOMPLETE",
] as const;

export const ERP_OPERATION_IDS = [
  "getUiProjection","createERPConnector","updateERPConnector","validateERPConnector","validateERPMapping","refreshERPSnapshot","createERPSyncJob",
  "getERPSyncStatus","retryERPSync","getERPFailure","getERPFinanceFactPack","getERPCapacityGuardrails","getERPForecast","exportProjection",
] as const;

export const ERP_SOURCE_CONTROL_MAP = {
  "CTRL-ADMIN-ERP-01-CONNECTOR-OPEN":"ERP-01-FLD-CONN-CONNECTOR-ID",
  "CTRL-ADMIN-ERP-01-SNAPSHOT-OPEN":"ERP-01-FLD-SNAPSHOT",
  "CTRL-ADMIN-ERP-01-FRESHNESS-OPEN":"ERP-01-FLD-FRESHNESS",
  "CTRL-ADMIN-ERP-01-CURRENCY-TIMEZONE-OPEN":"ERP-01-FLD-SYNC-CURRENCY-TIMEZONE",
  "CTRL-ADMIN-ERP-01-COMPLETENESS-OPEN":"ERP-01-FLD-SYNC-COMPLETENESS",
  "CTRL-ADMIN-ERP-01-FAILURE-OPEN":"ERP-01-FLD-SYNC-FAILURE-ID",
  "CTRL-ADMIN-ERP-01-AUDIT-OPEN":"ERP-01-FLD-AUDIT-REF",
  "CTRL-ADMIN-ERP-01-ACT-01-ERP-CONNECTOR-CREATE":"ERP-01-BTN-CONNECTOR-CREATE",
  "CTRL-ADMIN-ERP-01-ACT-02-ERP-CONNECTOR-UPDATE":"ERP-01-BTN-CONNECTOR-UPDATE",
  "CTRL-ADMIN-ERP-01-ACT-03-ERP-CONNECTOR-VALIDATE":"ERP-01-BTN-CONNECTOR-VALIDATE",
  "CTRL-ADMIN-ERP-01-ACT-04-ERP-MAPPING-VALIDATE":"ERP-01-BTN-MAPPING-VALIDATE",
  "CTRL-ADMIN-ERP-01-ACT-05-ERP-SNAPSHOT-REFRESH":"ERP-01-BTN-SNAPSHOT-REFRESH",
  "CTRL-ADMIN-ERP-01-ACT-06-ERP-SYNC-CREATE":"ERP-01-BTN-SYNC-CREATE",
  "CTRL-ADMIN-ERP-01-ACT-07-ERP-SYNC-STATUS":"ERP-01-BTN-SYNC-STATUS",
  "CTRL-ADMIN-ERP-01-ACT-08-ERP-SYNC-RETRY":"ERP-01-BTN-SYNC-RETRY",
  "CTRL-ADMIN-ERP-01-ACT-09-ERP-FAILURE-GET":"ERP-01-BTN-FAILURE-GET",
  "CTRL-ADMIN-ERP-01-ACT-10-ACT-NAV-OPEN":"ERP-01-BTN-DETAIL",
  "CTRL-ADMIN-ERP-02-COST-OPEN":"ERP-01-FLD-FIN-COST",
  "CTRL-ADMIN-ERP-02-REVENUE-OPEN":"ERP-01-FLD-FIN-REVENUE",
  "CTRL-ADMIN-ERP-02-CASHFLOW-OPEN":"ERP-01-FLD-FIN-CASHFLOW",
  "CTRL-ADMIN-ERP-02-CAPACITY-OPEN":"ERP-01-FLD-FIN-CAPACITY",
  "CTRL-ADMIN-ERP-02-FORECAST-OPEN":"ERP-01-FLD-FIN-FORECAST",
  "CTRL-ADMIN-ERP-02-GUARDRAILS-OPEN":"ERP-01-FLD-FIN-GUARDRAILS",
  "CTRL-ADMIN-ERP-02-RECOMMENDATION-BOUNDARY-OPEN":"ERP-01-FLD-FIN-RECOMMENDATION-BOUNDARY",
  "CTRL-ADMIN-ERP-02-ACT-01-ERP-FINANCE-GET-FACTPACK":"ERP-01-BTN-FACTPACK",
  "CTRL-ADMIN-ERP-02-ACT-02-ERP-CAPACITY-GET-GUARDRAILS":"ERP-01-BTN-GUARDRAILS",
  "CTRL-ADMIN-ERP-02-ACT-03-ERP-FORECAST-GET":"ERP-01-BTN-FORECAST",
  "CTRL-ADMIN-ERP-02-ACT-04-ACT-EXPORT":"ERP-01-BTN-EXPORT",
  "CTRL-ADMIN-ERP-02-ACT-05-ACT-NAV-OPEN":"ERP-01-BTN-DETAIL",
} as const satisfies Record<string,(typeof ERP_CONTROL_UIDS)[number]>;

export const ERP_FORBIDDEN_WRITE_TERMS = ["revenue","expense","ledger","budget","erp_write_from_acpos","writeback"] as const;
