import{configureVideoSharedRuntime,type VideoInvokeInput,type VideoInvokeResult}from"./videoClientPort";
import{configureVideoProjectionResolver,type VideoNormalizedProjection}from"./videoProjectionPort";
import{createControlledTestMetadata,createControlledTestRef,isControlledTestMode}from"@/domain/testing/controlledTestData";
let lastProjection:VideoNormalizedProjection|null=null;let correctionCandidateRef:string|null=null;let approvedCorrectionRef:string|null=null;
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==="object";}
function normalize(raw:unknown):VideoNormalizedProjection{if(!isRecord(raw)||!isRecord(raw.values)||!isRecord(raw.lists)||!isRecord(raw.filters)||!isRecord(raw.gate_state)||!Array.isArray(raw.versions))throw new Error("VIDEO_TEST_PROJECTION_INVALID");const projection=raw as unknown as VideoNormalizedProjection;lastProjection=projection;return projection;}
export function rememberControlledVideoProjection(projection:VideoNormalizedProjection|null){if(projection)lastProjection=projection;}
function meta(){return createControlledTestMetadata("VIDEO-01");}
function cloneProjection(p:VideoNormalizedProjection):VideoNormalizedProjection{return{...p,values:{...p.values},lists:Object.fromEntries(Object.entries(p.lists).map(([k,v])=>[k,[...v]])),filters:Object.fromEntries(Object.entries(p.filters).map(([k,v])=>[k,[...v]])),gate_state:{...p.gate_state},versions:p.versions.map(v=>({...v}))};}
function failure(error_uid:"VIDEO-01-ERR-CORRECTION-001"|"VIDEO-01-ERR-VERSION-001"|"VIDEO-01-ERR-CRITERIA-001",reason_code:string):VideoInvokeResult{return{ok:false,error_uid,reason_code,correlation_id:"unresolved"};}
export function configureControlledVideoClientRuntime(){if(!isControlledTestMode())return;configureVideoProjectionResolver({resolve:normalize});configureVideoSharedRuntime({async invoke(operation_id,input){const correlation_id=createControlledTestRef("VIDEO-SHARED-CORRELATION");if(operation_id==="generateCorrectionScriptCandidate"){if(!lastProjection?.candidate_version_id)return failure("VIDEO-01-ERR-CORRECTION-001","VIDEO_CANDIDATE_REQUIRED");correctionCandidateRef=createControlledTestRef("VIDEO-CORRECTION-CANDIDATE");approvedCorrectionRef=null;return{ok:true,value:{candidate_ref:correctionCandidateRef,test_metadata:meta()},correlation_id};}if(operation_id==="approveCorrectionScriptCandidate"){if(!correctionCandidateRef)return failure("VIDEO-01-ERR-CORRECTION-001","CORRECTION_CANDIDATE_REQUIRED");approvedCorrectionRef=createControlledTestRef("VIDEO-CORRECTION-APPROVED");return{ok:true,value:{approved_candidate_ref:approvedCorrectionRef,test_metadata:meta()},correlation_id};}if(operation_id==="lockVideoVersion"){const p=lastProjection;if(!p?.current_version_id||p.page_state!=="CONFIRMED")return failure("VIDEO-01-ERR-VERSION-001","CONFIRMED_EXACT_VIDEO_VERSION_REQUIRED");const lockRef=`TEST-VIDEO-LOCK-${p.current_version_id}`,base=cloneProjection(p),values={...base.values,"VIDEO-01-FLD-PAGE-STATE":"LOCKED","VIDEO-01-FLD-TASK-STATE":"LOCKED","VIDEO-01-TEST-LOCK-REF":lockRef},gate_state={...base.gate_state,"VIDEO-01-GATE-LOCK":false,"VIDEO-01-GATE-HANDOFF":true},next:VideoNormalizedProjection={...base,page_state:"LOCKED",values,gate_state};lastProjection=next;return{ok:true,value:{projection:next,locked_version_ref:lockRef,test_metadata:meta()},correlation_id};}return failure("VIDEO-01-ERR-CORRECTION-001","CONTROLLED_VIDEO_SHARED_OPERATION_UNKNOWN");},async prepareEvaluation(){const p=lastProjection;if(!p?.candidate_version_id)throw new Error("VIDEO_EVALUATION_CANDIDATE_REQUIRED");return{test_metadata:meta(),target_output_version_id:p.candidate_version_id,criteria_version_id:p.values["VIDEO-01-FLD-CRITERIA-VERSION"],evidence_refs:[p.candidate_version_id]};},async prepareCorrectionExecution(input:VideoInvokeInput){const p=lastProjection;if(!p?.task_id||!p.candidate_version_id||!approvedCorrectionRef)throw new Error("VIDEO_APPROVED_CORRECTION_REQUIRED");const base=isRecord(input.payload)?input.payload:{};return{...base,test_metadata:meta(),mode:"CORRECTION",source_video_version_id:p.candidate_version_id,approved_candidate_ref:approvedCorrectionRef,translated_instruction_ref:createControlledTestRef("VIDEO-CORRECTION-INSTRUCTION")};}});}