import{isControlledTestMode}from"@/domain/testing/controlledTestData";
export type VideoListItem={ref:string;label:string};
export type VideoProjectionVersion={ref:string;label:string;uri:string;duration_seconds:number};
export type VideoProjectionTestMetadata={data_classification:"TEST_ONLY";synthetic:true;test_dataset_id:string;test_run_id:string;created_for_validation:true;production_eligible:false};
export type VideoNormalizedProjection={page_state:string|null;task_id:string|null;current_version_id:string|null;candidate_version_id:string|null;current_uri:string|null;candidate_uri:string|null;versions:readonly VideoProjectionVersion[];values:Readonly<Record<string,string>>;lists:Readonly<Record<string,readonly VideoListItem[]>>;filters:Readonly<Record<string,readonly VideoListItem[]>>;gate_state:Readonly<Record<string,boolean>>;test_metadata?:VideoProjectionTestMetadata};
export type VideoProjectionResolver={resolve:(raw:unknown)=>VideoNormalizedProjection|Promise<VideoNormalizedProjection>};
let resolver:VideoProjectionResolver|null=null;
export function configureVideoProjectionResolver(next:VideoProjectionResolver){resolver=next;}
export function isVideoProjectionResolverBound(){return resolver!==null;}
export async function readVideoProjection(signal?:AbortSignal){let response:Response;try{response=await fetch("/v1/ui-projections/VIDEO-01",{method:"GET",cache:"no-store",signal});}catch{return{ok:false as const,error_uid:"VIDEO-01-ERR-CONTEXT-001",reason_code:"VIDEO_PROJECTION_REQUEST_FAILED",correlation_id:"unresolved"};}const correlation_id=response.headers.get("x-correlation-id")??"unresolved";const raw:unknown=await response.json().catch(()=>null);if(!response.ok){const body=typeof raw==="object"&&raw!==null?raw as Record<string,unknown>:null;return{ok:false as const,error_uid:"VIDEO-01-ERR-CONTEXT-001",reason_code:typeof body?.reason_code==="string"?body.reason_code:"VIDEO_PROJECTION_READ_FAILED",correlation_id:typeof body?.correlation_id==="string"?body.correlation_id:correlation_id};}if(!resolver){if(isControlledTestMode()&&raw&&typeof raw==="object"&&(raw as Partial<VideoNormalizedProjection>).test_metadata?.data_classification==="TEST_ONLY"&&(raw as Partial<VideoNormalizedProjection>).test_metadata?.production_eligible===false)return{ok:true as const,projection:raw as VideoNormalizedProjection,correlation_id};return{ok:false as const,error_uid:"VIDEO-01-ERR-CONTEXT-001",reason_code:"VIDEO_PROJECTION_ADAPTER_NOT_BOUND",correlation_id};}try{const projection=await resolver.resolve(raw);if(projection.test_metadata!==undefined&&!isControlledTestMode())throw new Error("VIDEO_TEST_PROJECTION_FORBIDDEN_IN_PRODUCTION");return{ok:true as const,projection,correlation_id};}catch{return{ok:false as const,error_uid:"VIDEO-01-ERR-CONTEXT-001",reason_code:"VIDEO_PROJECTION_ADAPTER_REJECTED",correlation_id};}}