export const ASSET_ACTION_UIDS = [
  "ASSET-01-ACT-PROJECT-SELECT","ASSET-01-ACT-TOPIC-SELECT","ASSET-01-ACT-MODE-SET","ASSET-01-ACT-FLOW-START",
  "ASSET-01-ACT-ASSET-SEARCH","ASSET-01-ACT-ASSET-FILTER","ASSET-01-ACT-ASSET-SELECT","ASSET-01-ACT-BLUEPRINT-VIEW",
  "ASSET-01-ACT-SCRIPT-VIEW","ASSET-01-ACT-BINDING-VIEW","ASSET-01-ACT-COMPARE-SINGLE","ASSET-01-ACT-COMPARE-AB",
  "ASSET-01-ACT-COMPARE-ABC","ASSET-01-ACT-ZOOM-IN","ASSET-01-ACT-ZOOM-OUT","ASSET-01-ACT-FIT",
  "ASSET-01-ACT-REFERENCE-TOGGLE","ASSET-01-ACT-RESULT-VIEW","ASSET-01-ACT-EVALUATE","ASSET-01-ACT-CANDIDATE-CONFIRM",
  "ASSET-01-ACT-CORRECTION-OPEN","ASSET-01-ACT-CORRECTION-GENERATE","ASSET-01-ACT-CORRECTION-APPROVE","ASSET-01-ACT-CORRECTION-EXECUTE",
  "ASSET-01-ACT-FINDING-CREATE","ASSET-01-ACT-TASK-RETRY","ASSET-01-ACT-RUNTIME-VIEW","ASSET-01-ACT-VERSION-HISTORY",
  "ASSET-01-ACT-RESTORE-AS-NEW","ASSET-01-ACT-VERSION-LOCK","ASSET-01-ACT-HANDOFF","ASSET-01-ACT-LAYER-DOC-CREATE",
  "ASSET-01-ACT-LAYER-DOC-UPDATE","ASSET-01-ACT-LAYER-ADD","ASSET-01-ACT-LAYER-DELETE","ASSET-01-ACT-LAYER-DUPLICATE",
  "ASSET-01-ACT-LAYER-REORDER","ASSET-01-ACT-LAYER-PROPERTIES","ASSET-01-ACT-LAYER-MASK","ASSET-01-ACT-PATCH-CREATE",
  "ASSET-01-ACT-PATCH-PREVIEW","ASSET-01-ACT-PATCH-ACCEPT","ASSET-01-ACT-PATCH-REJECT","ASSET-01-ACT-PATCH-REVISE"
] as const;
export type AssetActionUid = typeof ASSET_ACTION_UIDS[number];

export const ASSET_PORT_UIDS = [
  "ASSET-01-PORT-IN-CORE-HANDOFF","ASSET-01-PORT-EXECUTE","ASSET-01-PORT-RETRY","ASSET-01-PORT-FINDING","ASSET-01-PORT-CORRECTION",
  "ASSET-01-PORT-DECISION","ASSET-01-PORT-SCORECARD","ASSET-01-PORT-OUT-VIDEO","ASSET-01-PORT-LAYER-DOC-CREATE","ASSET-01-PORT-LAYER-DOC-UPDATE",
  "ASSET-01-PORT-LAYER-ADD","ASSET-01-PORT-LAYER-DELETE","ASSET-01-PORT-LAYER-DUP","ASSET-01-PORT-LAYER-REORDER","ASSET-01-PORT-LAYER-PROPS",
  "ASSET-01-PORT-LAYER-MASK","ASSET-01-PORT-PATCH-CREATE","ASSET-01-PORT-PATCH-PREVIEW","ASSET-01-PORT-PATCH-DECIDE"
] as const;
export type AssetPortUid = typeof ASSET_PORT_UIDS[number];
export type AssetHttpMethod = "POST" | "PATCH" | "DELETE";

export const ASSET_PORT_METHOD_PATH: Record<AssetPortUid,{method:AssetHttpMethod;path:string}> = {
  "ASSET-01-PORT-IN-CORE-HANDOFF":{method:"POST",path:"/v1/handoffs"},
  "ASSET-01-PORT-EXECUTE":{method:"POST",path:"/v1/tasks/{taskId}/execute"},
  "ASSET-01-PORT-RETRY":{method:"POST",path:"/v1/tasks/{taskId}/retry"},
  "ASSET-01-PORT-FINDING":{method:"POST",path:"/v1/findings"},
  "ASSET-01-PORT-CORRECTION":{method:"POST",path:"/v1/correction-requests"},
  "ASSET-01-PORT-DECISION":{method:"POST",path:"/v1/tasks/{taskId}/outputs/{outputVersionId}/decision"},
  "ASSET-01-PORT-SCORECARD":{method:"POST",path:"/v1/scorecards"},
  "ASSET-01-PORT-OUT-VIDEO":{method:"POST",path:"/v1/handoffs"},
  "ASSET-01-PORT-LAYER-DOC-CREATE":{method:"POST",path:"/v1/layer-documents"},
  "ASSET-01-PORT-LAYER-DOC-UPDATE":{method:"PATCH",path:"/v1/layer-documents/{layerDocumentId}"},
  "ASSET-01-PORT-LAYER-ADD":{method:"POST",path:"/v1/layer-documents/{layerDocumentId}/layers"},
  "ASSET-01-PORT-LAYER-DELETE":{method:"DELETE",path:"/v1/layer-documents/{layerDocumentId}/layers/{layerId}"},
  "ASSET-01-PORT-LAYER-DUP":{method:"POST",path:"/v1/layer-documents/{layerDocumentId}/layers/{layerId}/duplicate"},
  "ASSET-01-PORT-LAYER-REORDER":{method:"POST",path:"/v1/layer-documents/{layerDocumentId}/layers/{layerId}/reorder"},
  "ASSET-01-PORT-LAYER-PROPS":{method:"PATCH",path:"/v1/layer-documents/{layerDocumentId}/layers/{layerId}"},
  "ASSET-01-PORT-LAYER-MASK":{method:"PATCH",path:"/v1/layer-documents/{layerDocumentId}/layers/{layerId}/mask"},
  "ASSET-01-PORT-PATCH-CREATE":{method:"POST",path:"/v1/asset-patches"},
  "ASSET-01-PORT-PATCH-PREVIEW":{method:"POST",path:"/v1/asset-patches/{patchId}/preview"},
  "ASSET-01-PORT-PATCH-DECIDE":{method:"POST",path:"/v1/asset-patches/{patchId}/decision"}
};

export const ASSET_ACTION_PORT: Partial<Record<AssetActionUid,AssetPortUid>> = {
  "ASSET-01-ACT-FLOW-START":"ASSET-01-PORT-EXECUTE",
  "ASSET-01-ACT-EVALUATE":"ASSET-01-PORT-SCORECARD",
  "ASSET-01-ACT-CANDIDATE-CONFIRM":"ASSET-01-PORT-DECISION",
  "ASSET-01-ACT-CORRECTION-EXECUTE":"ASSET-01-PORT-EXECUTE",
  "ASSET-01-ACT-FINDING-CREATE":"ASSET-01-PORT-FINDING",
  "ASSET-01-ACT-TASK-RETRY":"ASSET-01-PORT-RETRY",
  "ASSET-01-ACT-HANDOFF":"ASSET-01-PORT-OUT-VIDEO",
  "ASSET-01-ACT-LAYER-DOC-CREATE":"ASSET-01-PORT-LAYER-DOC-CREATE",
  "ASSET-01-ACT-LAYER-DOC-UPDATE":"ASSET-01-PORT-LAYER-DOC-UPDATE",
  "ASSET-01-ACT-LAYER-ADD":"ASSET-01-PORT-LAYER-ADD",
  "ASSET-01-ACT-LAYER-DELETE":"ASSET-01-PORT-LAYER-DELETE",
  "ASSET-01-ACT-LAYER-DUPLICATE":"ASSET-01-PORT-LAYER-DUP",
  "ASSET-01-ACT-LAYER-REORDER":"ASSET-01-PORT-LAYER-REORDER",
  "ASSET-01-ACT-LAYER-PROPERTIES":"ASSET-01-PORT-LAYER-PROPS",
  "ASSET-01-ACT-LAYER-MASK":"ASSET-01-PORT-LAYER-MASK",
  "ASSET-01-ACT-PATCH-CREATE":"ASSET-01-PORT-PATCH-CREATE",
  "ASSET-01-ACT-PATCH-PREVIEW":"ASSET-01-PORT-PATCH-PREVIEW",
  "ASSET-01-ACT-PATCH-ACCEPT":"ASSET-01-PORT-PATCH-DECIDE",
  "ASSET-01-ACT-PATCH-REJECT":"ASSET-01-PORT-PATCH-DECIDE"
};

export const ASSET_SHARED_OPERATION: Partial<Record<AssetActionUid,string>> = {
  "ASSET-01-ACT-CORRECTION-GENERATE":"generateCorrectionScriptCandidate",
  "ASSET-01-ACT-CORRECTION-APPROVE":"approveCorrectionScriptCandidate",
  "ASSET-01-ACT-RESTORE-AS-NEW":"restoreAssetVersionAsNewDraft",
  "ASSET-01-ACT-VERSION-LOCK":"lockAssetVersion"
};

export type AssetRuntimeErrorUid =
  | "ASSET-01-ERR-CONTEXT-001"|"ASSET-01-ERR-BLUEPRINT-001"|"ASSET-01-ERR-SCRIPT-001"|"ASSET-01-ERR-DNA-001"
  | "ASSET-01-ERR-MANIFEST-001"|"ASSET-01-ERR-NAMING-001"|"ASSET-01-ERR-ROUTE-001"|"ASSET-01-ERR-PROVIDER-001"
  | "ASSET-01-ERR-CANDIDATE-001"|"ASSET-01-ERR-CRITERIA-001"|"ASSET-01-ERR-CORRECTION-001"|"ASSET-01-ERR-TRANSLATION-001"
  | "ASSET-01-ERR-LAYER-001"|"ASSET-01-ERR-PATCH-001"|"ASSET-01-ERR-VERSION-001"|"ASSET-01-ERR-HANDOFF-001"|"ASSET-01-ERR-PERM-001";

export type AssetRuntimeRequest={port_uid:AssetPortUid;action_uid?:AssetActionUid;correlation_id:string;path_params?:Record<string,string>;payload?:unknown};
export type AssetRuntimeResult={ok:true;value:unknown;correlation_id:string}|{ok:false;error_uid:AssetRuntimeErrorUid;reason_code:string;correlation_id:string;status:number};
