export const ADMIN_STR_VISIBLE_CONTROLS = [
  "CTRL-ADMIN-STR-01-VIEW-OVERVIEW",
  "CTRL-ADMIN-STR-01-VIEW-INTELLIGENCE-FACT",
  "CTRL-ADMIN-STR-01-VIEW-PLAYBOOK",
  "CTRL-ADMIN-STR-01-VIEW-OPPORTUNITY",
  "CTRL-ADMIN-STR-01-VIEW-DECISION",
  "CTRL-ADMIN-STR-01-ACT-SEARCH",
  "CTRL-ADMIN-STR-01-ACT-REFRESH",
  "CTRL-ADMIN-STR-01-ACT-NAV-OPEN",
  "CTRL-ADMIN-STR-01-ACT-CONFIGURE",
  "CTRL-ADMIN-STR-01-ACT-APPROVE",
  "CTRL-ADMIN-STR-01-ACT-EXPORT",
  "CTRL-ADMIN-STR-01-ACT-DRAFT-SAVE",
  "CTRL-ADMIN-STR-01-ACT-CANDIDATE-CREATE",
  "CTRL-ADMIN-STR-01-ACT-CANDIDATE-COMPARE",
  "CTRL-ADMIN-STR-01-ACT-CANDIDATE-DECIDE",
  "CTRL-ADMIN-STR-01-ACT-ADOPT-CONTEXT",
] as const;

export const ADMIN_STR_CONTROL_ACTIONS: Record<string, string> = {
  "CTRL-ADMIN-STR-01-VIEW-OVERVIEW": "getUiProjection",
  "CTRL-ADMIN-STR-01-VIEW-INTELLIGENCE-FACT": "getUiProjection",
  "CTRL-ADMIN-STR-01-VIEW-PLAYBOOK": "getUiProjection",
  "CTRL-ADMIN-STR-01-VIEW-OPPORTUNITY": "getUiProjection",
  "CTRL-ADMIN-STR-01-VIEW-DECISION": "getUiProjection",
  "CTRL-ADMIN-STR-01-ACT-SEARCH": "searchProjection",
  "CTRL-ADMIN-STR-01-ACT-REFRESH": "refreshProjection",
  "CTRL-ADMIN-STR-01-ACT-NAV-OPEN": "getUiProjection",
  "CTRL-ADMIN-STR-01-ACT-CONFIGURE": "configureGovernedResource",
  "CTRL-ADMIN-STR-01-ACT-APPROVE": "approveGovernedResource",
  "CTRL-ADMIN-STR-01-ACT-EXPORT": "exportProjection",
  "CTRL-ADMIN-STR-01-ACT-DRAFT-SAVE": "saveDraft",
  "CTRL-ADMIN-STR-01-ACT-CANDIDATE-CREATE": "createCandidate",
  "CTRL-ADMIN-STR-01-ACT-CANDIDATE-COMPARE": "compareCandidates",
  "CTRL-ADMIN-STR-01-ACT-CANDIDATE-DECIDE": "rejectStrategyCandidate",
  "CTRL-ADMIN-STR-01-ACT-ADOPT-CONTEXT": "adoptAsContextCandidate",
};

export const ADMIN_STR_VIEWS = [
  "STR-CURRENT-VIEW-OVERVIEW",
  "STR-CURRENT-VIEW-INTELLIGENCE-FACT",
  "STR-CURRENT-VIEW-PLAYBOOK",
  "STR-CURRENT-VIEW-OPPORTUNITY",
  "STR-CURRENT-VIEW-DECISION",
] as const;

export type AdminStrView = (typeof ADMIN_STR_VIEWS)[number];

export type AdminStrDrawer = "nav" | "search" | "detail";

export const ADMIN_STR_VIEW_CONTROLS: Record<AdminStrView, string> = {
  "STR-CURRENT-VIEW-OVERVIEW": "CTRL-ADMIN-STR-01-VIEW-OVERVIEW",
  "STR-CURRENT-VIEW-INTELLIGENCE-FACT": "CTRL-ADMIN-STR-01-VIEW-INTELLIGENCE-FACT",
  "STR-CURRENT-VIEW-PLAYBOOK": "CTRL-ADMIN-STR-01-VIEW-PLAYBOOK",
  "STR-CURRENT-VIEW-OPPORTUNITY": "CTRL-ADMIN-STR-01-VIEW-OPPORTUNITY",
  "STR-CURRENT-VIEW-DECISION": "CTRL-ADMIN-STR-01-VIEW-DECISION",
};

export const ADMIN_STR_VIEW_ACTIONS: Record<AdminStrView, readonly string[]> = {
  "STR-CURRENT-VIEW-OVERVIEW": [
    "CTRL-ADMIN-STR-01-ACT-SEARCH",
    "CTRL-ADMIN-STR-01-ACT-REFRESH",
    "CTRL-ADMIN-STR-01-ACT-NAV-OPEN",
  ],
  "STR-CURRENT-VIEW-INTELLIGENCE-FACT": [
    "CTRL-ADMIN-STR-01-ACT-CONFIGURE",
    "CTRL-ADMIN-STR-01-ACT-APPROVE",
    "CTRL-ADMIN-STR-01-ACT-SEARCH",
    "CTRL-ADMIN-STR-01-ACT-EXPORT",
    "CTRL-ADMIN-STR-01-ACT-NAV-OPEN",
  ],
  "STR-CURRENT-VIEW-PLAYBOOK": [
    "CTRL-ADMIN-STR-01-ACT-DRAFT-SAVE",
    "CTRL-ADMIN-STR-01-ACT-APPROVE",
    "CTRL-ADMIN-STR-01-ACT-NAV-OPEN",
  ],
  "STR-CURRENT-VIEW-OPPORTUNITY": [
    "CTRL-ADMIN-STR-01-ACT-CANDIDATE-CREATE",
    "CTRL-ADMIN-STR-01-ACT-APPROVE",
    "CTRL-ADMIN-STR-01-ACT-NAV-OPEN",
  ],
  "STR-CURRENT-VIEW-DECISION": [
    "CTRL-ADMIN-STR-01-ACT-CANDIDATE-COMPARE",
    "CTRL-ADMIN-STR-01-ACT-CANDIDATE-DECIDE",
    "CTRL-ADMIN-STR-01-ACT-ADOPT-CONTEXT",
    "CTRL-ADMIN-STR-01-ACT-NAV-OPEN",
  ],
};
