export const AIAPI_VISIBLE_CONTROLS = [
  "AIAPI-01-BTN-TAB-OVERVIEW",
  "AIAPI-01-BTN-TAB-PROVIDER",
  "AIAPI-01-BTN-TAB-ROUTING",
  "AIAPI-01-BTN-TAB-OPERATIONS",
  "AIAPI-01-FLD-SEARCH",
  "AIAPI-01-FLD-OV-PROVIDER",
  "AIAPI-01-FLD-OV-ROUTE",
  "AIAPI-01-FLD-OV-CAPABILITY",
  "AIAPI-01-FLD-OV-JOB",
  "AIAPI-01-FLD-OV-COST",
  "AIAPI-01-FLD-OV-HEALTH",
  "AIAPI-01-FLD-OV-INCIDENT",
  "AIAPI-01-PROFILE-GRP-IDENTITY",
  "AIAPI-01-PROFILE-GRP-CONNECTION",
  "AIAPI-01-PROFILE-GRP-ADAPTER",
  "AIAPI-01-PROFILE-GRP-CAPABILITY",
  "AIAPI-01-PROFILE-GRP-DATA-CONTEXT",
  "AIAPI-01-PROFILE-GRP-STATUS",
  "AIAPI-01-PRO-DESC-IDENTITY",
  "AIAPI-01-PRO-DESC-POSITIONING",
  "AIAPI-01-PRO-DESC-ACPOS-SCOPE",
  "AIAPI-01-PRO-DESC-CAPABILITIES",
  "AIAPI-01-PRO-DESC-INPUT",
  "AIAPI-01-PRO-DESC-OUTPUT",
  "AIAPI-01-PRO-DESC-LIMITS",
  "AIAPI-01-PRO-DESC-ENDPOINT",
  "AIAPI-01-PRO-DESC-AUTH",
  "AIAPI-01-PRO-DESC-BILLING",
  "AIAPI-01-PRO-DESC-HEALTH",
  "AIAPI-01-PRO-DESC-LAST-TEST",
  "AIAPI-01-PRO-DESC-RECOMMENDED-USE",
  "AIAPI-01-PRO-DESC-RESTRICTIONS",
  "AIAPI-01-PRO-DESC-DOCS",
  "AIAPI-01-FLD-PF-CAPABILITY",
  "AIAPI-01-FLD-PF-RIGHTS",
  "AIAPI-01-FLD-PF-DATA",
  "AIAPI-01-FLD-PF-REFERENCE",
  "AIAPI-01-FLD-PF-BUDGET",
  "AIAPI-01-FLD-OPS-HEALTH",
  "AIAPI-01-FLD-OPS-CREDENTIAL",
  "AIAPI-01-FLD-OPS-QUEUE",
  "AIAPI-01-FLD-OPS-COST",
  "AIAPI-01-FLD-OPS-INCIDENT",
  "AIAPI-01-FLD-OPS-QUARANTINE",
  "AIAPI-01-FLD-JOB-ID",
  "AIAPI-01-FLD-JOB-STATUS",
  "AIAPI-01-FLD-ATTEMPT-ID",
  "AIAPI-01-FLD-CALLBACK",
  "AIAPI-01-FLD-ARTIFACT",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-CREATE-PROFILE",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-UPDATE-PROFILE",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-VIEW-PROFILE",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-TEST-PROFILE",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-RETIRE-PROFILE",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-SET-CREDENTIAL",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-DELETE-CREDENTIAL",
  "AIAPI-01-BTN-CONFIGURE-GOVERNED-RESOURCE",
  "AIAPI-01-BTN-APPROVE-GOVERNED-RESOURCE",
  "CTRL-ADMIN-AIAPI-05-PROVIDER-CANDIDATE-GROUPS-CREATE-GROUP",
  "AIAPI-01-BTN-RUN-SANDBOX-TEST",
  "CTRL-ADMIN-AIAPI-08-ROUTE-SIMULATION-EXECUTE-ROUTE",
  "CTRL-ADMIN-AIAPI-08-ROUTE-SIMULATION-VIEW-ROUTE-DECISION",
  "CTRL-ADMIN-AIAPI-05-PROVIDER-CANDIDATE-GROUPS-VIEW-QUARANTINE",
  "CTRL-ADMIN-AIAPI-05-PROVIDER-CANDIDATE-GROUPS-RESTORE-PROVIDER",
  "AIAPI-01-BTN-RUN-PROVIDER-QUEUE-PROBE",
  "CTRL-ADMIN-AIAPI-09-ACT-02-ACT-KILL-SWITCH",
] as const;

export const AIAPI_CONTROL_ACTIONS: Record<string, string> = {
  "AIAPI-01-BTN-TAB-OVERVIEW": "AIAPI-01-ACT-VIEW-OVERVIEW",
  "AIAPI-01-BTN-TAB-PROVIDER": "AIAPI-01-ACT-VIEW-PROVIDER",
  "AIAPI-01-BTN-TAB-ROUTING": "AIAPI-01-ACT-VIEW-ROUTING",
  "AIAPI-01-BTN-TAB-OPERATIONS": "AIAPI-01-ACT-VIEW-OPERATIONS",
  "AIAPI-01-FLD-SEARCH": "searchProjection",
  "AIAPI-01-FLD-OV-PROVIDER": "getUiProjection",
  "AIAPI-01-FLD-OV-ROUTE": "getUiProjection",
  "AIAPI-01-FLD-OV-CAPABILITY": "getUiProjection",
  "AIAPI-01-FLD-OV-JOB": "getUiProjection",
  "AIAPI-01-FLD-OV-COST": "getUiProjection",
  "AIAPI-01-FLD-OV-HEALTH": "getUiProjection",
  "AIAPI-01-FLD-OV-INCIDENT": "getUiProjection",
  "AIAPI-01-PROFILE-GRP-IDENTITY": "getProviderModelProfile",
  "AIAPI-01-PROFILE-GRP-CONNECTION": "getProviderModelProfile",
  "AIAPI-01-PROFILE-GRP-ADAPTER": "getProviderModelProfile",
  "AIAPI-01-PROFILE-GRP-CAPABILITY": "getProviderModelProfile",
  "AIAPI-01-PROFILE-GRP-DATA-CONTEXT": "getProviderModelProfile",
  "AIAPI-01-PROFILE-GRP-STATUS": "getProviderModelProfile",
  "AIAPI-01-PRO-DESC-IDENTITY": "getUiProjection",
  "AIAPI-01-PRO-DESC-POSITIONING": "getUiProjection",
  "AIAPI-01-PRO-DESC-ACPOS-SCOPE": "getUiProjection",
  "AIAPI-01-PRO-DESC-CAPABILITIES": "getUiProjection",
  "AIAPI-01-PRO-DESC-INPUT": "getUiProjection",
  "AIAPI-01-PRO-DESC-OUTPUT": "getUiProjection",
  "AIAPI-01-PRO-DESC-LIMITS": "getUiProjection",
  "AIAPI-01-PRO-DESC-ENDPOINT": "getUiProjection",
  "AIAPI-01-PRO-DESC-AUTH": "getUiProjection",
  "AIAPI-01-PRO-DESC-BILLING": "getUiProjection",
  "AIAPI-01-PRO-DESC-HEALTH": "getUiProjection",
  "AIAPI-01-PRO-DESC-LAST-TEST": "getUiProjection",
  "AIAPI-01-PRO-DESC-RECOMMENDED-USE": "getUiProjection",
  "AIAPI-01-PRO-DESC-RESTRICTIONS": "getUiProjection",
  "AIAPI-01-PRO-DESC-DOCS": "getUiProjection",
  "AIAPI-01-FLD-PF-CAPABILITY": "getUiProjection",
  "AIAPI-01-FLD-PF-RIGHTS": "getUiProjection",
  "AIAPI-01-FLD-PF-DATA": "getUiProjection",
  "AIAPI-01-FLD-PF-REFERENCE": "getUiProjection",
  "AIAPI-01-FLD-PF-BUDGET": "getUiProjection",
  "AIAPI-01-FLD-OPS-HEALTH": "getUiProjection",
  "AIAPI-01-FLD-OPS-CREDENTIAL": "getUiProjection",
  "AIAPI-01-FLD-OPS-QUEUE": "getUiProjection",
  "AIAPI-01-FLD-OPS-COST": "getUiProjection",
  "AIAPI-01-FLD-OPS-INCIDENT": "getUiProjection",
  "AIAPI-01-FLD-OPS-QUARANTINE": "getProviderQuarantine",
  "AIAPI-01-FLD-JOB-ID": "getUiProjection",
  "AIAPI-01-FLD-JOB-STATUS": "getUiProjection",
  "AIAPI-01-FLD-ATTEMPT-ID": "getUiProjection",
  "AIAPI-01-FLD-CALLBACK": "getUiProjection",
  "AIAPI-01-FLD-ARTIFACT": "getUiProjection",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-CREATE-PROFILE": "createProviderModelProfile",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-UPDATE-PROFILE": "updateProviderModelProfile",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-VIEW-PROFILE": "getProviderModelProfile",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-TEST-PROFILE": "testProviderModelProfile",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-RETIRE-PROFILE": "retireProviderModelProfile",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-SET-CREDENTIAL": "setProviderModelCredential",
  "CTRL-ADMIN-AIAPI-06-PROVIDER-MODEL-PROFILES-DELETE-CREDENTIAL": "deleteProviderModelCredential",
  "AIAPI-01-BTN-CONFIGURE-GOVERNED-RESOURCE": "configureGovernedResource",
  "AIAPI-01-BTN-APPROVE-GOVERNED-RESOURCE": "approveGovernedResource",
  "CTRL-ADMIN-AIAPI-05-PROVIDER-CANDIDATE-GROUPS-CREATE-GROUP": "createProviderCandidateGroup",
  "AIAPI-01-BTN-RUN-SANDBOX-TEST": "admin:AIAPI-08:ACT-SYSTEM-TEST",
  "CTRL-ADMIN-AIAPI-08-ROUTE-SIMULATION-EXECUTE-ROUTE": "executeProviderRoute",
  "CTRL-ADMIN-AIAPI-08-ROUTE-SIMULATION-VIEW-ROUTE-DECISION": "getProviderRouteDecision",
  "CTRL-ADMIN-AIAPI-05-PROVIDER-CANDIDATE-GROUPS-VIEW-QUARANTINE": "getProviderQuarantine",
  "CTRL-ADMIN-AIAPI-05-PROVIDER-CANDIDATE-GROUPS-RESTORE-PROVIDER": "restoreProviderFromQuarantine",
  "AIAPI-01-BTN-RUN-PROVIDER-QUEUE-PROBE": "runProviderQueueProbe",
  "CTRL-ADMIN-AIAPI-09-ACT-02-ACT-KILL-SWITCH": "setKillSwitch",
};

export const AIAPI_VIEWS = [
  { uid: "AIAPI-01-BTN-TAB-OVERVIEW", key: "overview", labelKey: "aiapi.tab-overview" as const },
  { uid: "AIAPI-01-BTN-TAB-PROVIDER", key: "provider_api", labelKey: "aiapi.tab-provider" as const },
  { uid: "AIAPI-01-BTN-TAB-ROUTING", key: "routing_test", labelKey: "aiapi.tab-routing" as const },
  { uid: "AIAPI-01-BTN-TAB-OPERATIONS", key: "operations", labelKey: "aiapi.tab-operations" as const },
] as const;

export type AiapiView = "overview" | "provider_api" | "routing_test" | "operations";

export const AIAPI_TABLE_COLUMNS = [
  "aiapi.col-provider",
  "aiapi.col-model",
  "aiapi.col-capability",
  "aiapi.col-adapter",
  "aiapi.col-base-url",
  "aiapi.col-endpoint",
  "aiapi.col-timeout",
  "aiapi.col-enabled",
  "aiapi.col-credential",
  "aiapi.col-last-test",
] as const;

export const AIAPI_PROFILE_GROUPS = [
  { uid: "AIAPI-01-PROFILE-GRP-IDENTITY", labelKey: "aiapi.grp-identity" as const },
  { uid: "AIAPI-01-PROFILE-GRP-CONNECTION", labelKey: "aiapi.grp-connection" as const },
  { uid: "AIAPI-01-PROFILE-GRP-ADAPTER", labelKey: "aiapi.grp-adapter" as const },
  { uid: "AIAPI-01-PROFILE-GRP-CAPABILITY", labelKey: "aiapi.grp-capability" as const },
  { uid: "AIAPI-01-PROFILE-GRP-DATA-CONTEXT", labelKey: "aiapi.grp-data" as const },
  { uid: "AIAPI-01-PROFILE-GRP-STATUS", labelKey: "aiapi.grp-status" as const },
] as const;

export const AIAPI_PRO_DESC_FIELDS = [
  { uid: "AIAPI-01-PRO-DESC-IDENTITY", labelKey: "aiapi.pro-identity" as const },
  { uid: "AIAPI-01-PRO-DESC-POSITIONING", labelKey: "aiapi.pro-positioning" as const },
  { uid: "AIAPI-01-PRO-DESC-ACPOS-SCOPE", labelKey: "aiapi.pro-scope" as const },
  { uid: "AIAPI-01-PRO-DESC-CAPABILITIES", labelKey: "aiapi.pro-capabilities" as const },
  { uid: "AIAPI-01-PRO-DESC-INPUT", labelKey: "aiapi.pro-input" as const },
  { uid: "AIAPI-01-PRO-DESC-OUTPUT", labelKey: "aiapi.pro-output" as const },
  { uid: "AIAPI-01-PRO-DESC-LIMITS", labelKey: "aiapi.pro-limits" as const },
  { uid: "AIAPI-01-PRO-DESC-ENDPOINT", labelKey: "aiapi.pro-endpoint" as const },
  { uid: "AIAPI-01-PRO-DESC-AUTH", labelKey: "aiapi.pro-auth" as const },
  { uid: "AIAPI-01-PRO-DESC-BILLING", labelKey: "aiapi.pro-billing" as const },
  { uid: "AIAPI-01-PRO-DESC-HEALTH", labelKey: "aiapi.pro-health" as const },
  { uid: "AIAPI-01-PRO-DESC-LAST-TEST", labelKey: "aiapi.pro-last-test" as const },
  { uid: "AIAPI-01-PRO-DESC-RECOMMENDED-USE", labelKey: "aiapi.pro-recommended" as const },
  { uid: "AIAPI-01-PRO-DESC-RESTRICTIONS", labelKey: "aiapi.pro-restrictions" as const },
  { uid: "AIAPI-01-PRO-DESC-DOCS", labelKey: "aiapi.pro-docs" as const },
] as const;
