"use client";
import{createContext,useContext,useEffect,useMemo,useReducer,useState,type Dispatch,type ReactNode}from"react";
import{useI18n}from"@/i18n/LocaleProvider";
import{dbText}from"@/i18n/dbCatalog";
import{INITIAL_DB_CLIENT_STATE,reduceDbClientState,type DbClientAction,type DbClientState}from"@/domain/database/dbClientState";
import{invokeDbRead,isDbClientRuntimeBound,openDbSystemLifecycle,readDbProjection,type DbNormalizedProjection,type DbProjectionItem}from"@/domain/database/dbClientPort";
import{DB_CONTROL_BINDINGS,type DbControlUid}from"@/domain/database/dbControlBindings";
import type{DbReadPortUid}from"@/domain/database/dbRuntimeContract";
import styles from"./DbVisual.module.css";
export type DbVisualKind="readonly"|"button"|"primary"|"search"|"select"|"list"|"table"|"toggle"|"graph"|"reference"|"trace";
type Runtime={state:DbClientState;dispatch:Dispatch<DbClientAction>;projection:DbNormalizedProjection|null;setProjection:(v:DbNormalizedProjection)=>void;runtimeError:string|null;setRuntimeError:(v:string|null)=>void;correlationId:string|null;setCorrelationId:(v:string|null)=>void};
const Ctx=createContext<Runtime|null>(null);
export function DbRuntimeProvider({children}:{children:ReactNode}){const[state,dispatch]=useReducer(reduceDbClientState,INITIAL_DB_CLIENT_STATE),[projection,setProjection]=useState<DbNormalizedProjection|null>(null),[runtimeError,setRuntimeError]=useState<string|null>(null),[correlationId,setCorrelationId]=useState<string|null>(null);useEffect(()=>{let active=true;void readDbProjection().then(r=>{if(!active)return;setCorrelationId(r.correlation_id);if(r.ok){setProjection(r.projection);setRuntimeError(null)}else setRuntimeError(`${r.error_uid}: ${r.reason_code}`)});return()=>{active=false}},[]);const value=useMemo(()=>({state,dispatch,projection,setProjection,runtimeError,setRuntimeError,correlationId,setCorrelationId}),[state,projection,runtimeError,correlationId]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useDbRuntimeState(){const v=useContext(Ctx);if(!v)throw new Error("DB_RUNTIME_PROVIDER_REQUIRED");return v;}
function gate(p:DbNormalizedProjection|null,uid:string){return p?.gates[uid]===true;}
const READ_PORT:Partial<Record<string,DbReadPortUid>>={"DB-01-ACT-SEARCH":"DB-01-PORT-ENTITY-LIST","DB-01-ACT-SCHEMA-REFRESH":"DB-01-PORT-SCHEMA","DB-01-ACT-TRACE":"DB-01-PORT-TRACE","DB-01-ACT-MIGRATION-REFRESH":"DB-01-PORT-MIGRATION","DB-01-ACT-INTEGRITY-REFRESH":"DB-01-PORT-INTEGRITY","DB-01-ACT-AUDIT-OPEN":"DB-01-PORT-AUDIT"};
function localValue(id:string,s:DbClientState){if(id==="DB-01-INP-SEARCH")return s.search;if(id==="DB-01-INP-TRACE-ID")return s.trace_ref??"";if(id==="DB-01-INP-MIGRATION-SEARCH")return s.migration_search;if(id==="DB-01-INP-AUDIT-ID")return s.audit_ref??"";if(id==="DB-01-SEL-DOMAIN")return s.domain_filter??"";if(id==="DB-01-SEL-ENTITY-TYPE")return s.entity_type_filter??"";if(id==="DB-01-SEL-TRACE-TYPE")return s.trace_type??"";if(id==="DB-01-SEL-FINDING-TYPE")return s.finding_type??"";return""}
function setLocal(id:string,value:string,dispatch:Dispatch<DbClientAction>){if(id==="DB-01-INP-SEARCH")dispatch({type:"SEARCH",value});else if(id==="DB-01-SEL-DOMAIN")dispatch({type:"DOMAIN",value:value||null});else if(id==="DB-01-SEL-ENTITY-TYPE")dispatch({type:"ENTITY_TYPE",value:value||null});else if(id==="DB-01-SEL-TRACE-TYPE")dispatch({type:"TRACE_TYPE",value:value||null});else if(id==="DB-01-INP-TRACE-ID")dispatch({type:"TRACE_REF",value:value||null});else if(id==="DB-01-INP-MIGRATION-SEARCH")dispatch({type:"MIGRATION_SEARCH",value});else if(id==="DB-01-SEL-FINDING-TYPE")dispatch({type:"FINDING_TYPE",value:value||null});else if(id==="DB-01-INP-AUDIT-ID")dispatch({type:"AUDIT_REF",value:value||null});}
function display(v:unknown){if(v===null||v===undefined||v==="")return"—";if(typeof v==="string"||typeof v==="number"||typeof v==="boolean")return String(v);try{return JSON.stringify(v)}catch{return"—"}}
function object(v:unknown):v is Record<string,unknown>{return Boolean(v)&&typeof v==="object"&&!Array.isArray(v);}
function refOf(v:unknown){return object(v)&&typeof v.ref==="string"?v.ref:null;}
function itemOf(v:unknown):DbProjectionItem|null{if(!object(v)||typeof v.ref!=="string")return null;return{ref:v.ref,label:typeof v.label==="string"?v.label:v.ref,meta:object(v.meta)?v.meta:undefined};}
function visibleList(id:string,rows:DbProjectionItem[],s:DbClientState){if(id==="DB-01-LIST-ENTITIES")return rows.filter(x=>(!s.domain_filter||x.meta?.domain===s.domain_filter)&&(!s.entity_type_filter||x.meta?.entity_type===s.entity_type_filter));if(id==="DB-01-LIST-FINDINGS")return rows.filter(x=>!s.finding_type||x.meta?.finding_type===s.finding_type);return rows;}
async function runRead(control_uid:string,action_uid:string,value:unknown,r:Runtime){const port=READ_PORT[action_uid];if(!port)return;const result=await invokeDbRead(port,{query:{action_uid,control_uid,value,client_state:r.state}});r.setCorrelationId(result.correlation_id);if(result.ok){r.setProjection(result.projection);r.setRuntimeError(null)}else r.setRuntimeError(`${result.error_uid}: ${result.reason_code}`)}
export function DbRuntimeControl({id,kind}:{id:string;kind:DbVisualKind}){const r=useDbRuntimeState(),{locale}=useI18n(),binding=DB_CONTROL_BINDINGS[id as DbControlUid],label=dbText(locale,id),allowed=Boolean(binding)&&gate(r.projection,binding.gate_uid),readPort=binding?READ_PORT[binding.action_uid]:undefined,enabled=allowed&&(!readPort||isDbClientRuntimeBound()),common={"data-control-id":id,"data-action-uid":binding?.action_uid,"data-gate-uid":binding?.gate_uid,"data-permission-uid":binding?.permission_uid,"data-disabled-reason":!allowed?binding?.gate_uid:readPort&&!isDbClientRuntimeBound()?"DB_CLIENT_RUNTIME_NOT_BOUND":undefined};
const choose=(ref:string)=>{if(binding?.action_uid==="DB-01-ACT-ENTITY-SELECT")r.dispatch({type:"ENTITY",value:ref});else if(binding?.action_uid==="DB-01-ACT-RELATION-OPEN")r.dispatch({type:"RELATION",value:ref});else if(binding?.action_uid==="DB-01-ACT-MIGRATION-SELECT")r.dispatch({type:"MIGRATION",value:ref});else if(binding?.action_uid==="DB-01-ACT-FINDING-SELECT")r.dispatch({type:"FINDING",value:ref});};
const click=()=>{const a=binding?.action_uid;if(!a)return;if(a==="DB-01-ACT-RELATION-MODE"){r.dispatch({type:"RELATION_MODE",value:r.state.relation_mode==="GRAPH"?"LIST":"GRAPH"});return}if(a==="DB-01-ACT-SYSTEM-LIFECYCLE"){void openDbSystemLifecycle().then(x=>{if(x.ok)window.location.assign(x.href);else r.setRuntimeError(x.reason_code)});return}if(READ_PORT[a])void runRead(id,a,null,r);};
if(kind==="readonly"){const raw=id==="DB-01-FLD-PAGE-STATE"?r.projection?.page_state:id==="DB-01-FLD-SOURCE-SYNC"?r.projection?.source_sync:id==="DB-01-FLD-DISABLED"?r.runtimeError:r.projection?.values[id];return <div className={styles.readonly}{...common}><span>{label}</span><strong>{display(raw)}</strong></div>}
if(kind==="list"){const rows=visibleList(id,r.projection?.lists[id]??[],r.state);return <div className={styles.listControl}{...common}><span>{label}</span><div className={styles.emptyView}>{rows.length?rows.map(x=><button key={x.ref} type="button" disabled={!enabled} onClick={()=>choose(x.ref)} data-exact-ref={x.ref}>{x.label}</button>):"—"}</div></div>}
if(kind==="table"){const rows=r.projection?.tables[id]??[],selectable=binding?.action_uid==="DB-01-ACT-MIGRATION-SELECT";return <div className={styles.tableControl}{...common}><span>{label}</span><div className={styles.tableView}>{rows.length?rows.map((x,i)=>{const ref=refOf(x);return selectable&&ref?<button key={ref} type="button" disabled={!enabled} onClick={()=>choose(ref)} data-exact-ref={ref}>{display(x)}</button>:<div key={i}>{display(x)}</div>}):"—"}</div></div>}
if(kind==="graph"){const raw=r.projection?.graph,items=Array.isArray(raw)?raw.map(itemOf).filter((x):x is DbProjectionItem=>Boolean(x)):[];return <div className={styles.graphControl}{...common}><span>{label}</span><div className={styles.graphView}>{items.length?items.map(x=><button key={x.ref} type="button" disabled={!enabled} onClick={()=>choose(x.ref)} data-exact-ref={x.ref}>{x.label}</button>):display(raw)}</div></div>}
if(kind==="trace"){const raw=id==="DB-01-VIEW-AUDIT"?r.projection?.audit:r.projection?.trace,items=Array.isArray(raw)?raw.map(itemOf).filter((x):x is DbProjectionItem=>Boolean(x)):[],selectable=binding?.action_uid==="DB-01-ACT-RELATION-OPEN";return <div className={styles.traceControl}{...common}><span>{label}</span><div className={styles.traceView}>{selectable&&items.length?items.map(x=><button key={x.ref} type="button" disabled={!enabled} onClick={()=>choose(x.ref)} data-exact-ref={x.ref}>{x.label}</button>):display(raw)}</div></div>}
if(kind==="toggle")return <div className={styles.segmented}{...common}><span>{label}</span><div><button type="button" disabled={!allowed} aria-pressed={r.state.relation_mode==="GRAPH"} onClick={()=>r.dispatch({type:"RELATION_MODE",value:"GRAPH"})}>Graph</button><button type="button" disabled={!allowed} aria-pressed={r.state.relation_mode==="LIST"} onClick={()=>r.dispatch({type:"RELATION_MODE",value:"LIST"})}>List</button></div></div>;
if(kind==="select"){const rows=r.projection?.filters[id]??r.projection?.lists[id]??[];return <label className={styles.fieldControl}><span>{label}</span><select {...common} disabled={!allowed} value={localValue(id,r.state)} onChange={e=>setLocal(id,e.target.value,r.dispatch)}><option value="">—</option>{rows.map(x=><option key={x.ref} value={x.ref}>{x.label}</option>)}</select></label>}
if(kind==="search"||kind==="reference"){const queryAction=binding?.action_uid&&READ_PORT[binding.action_uid];return <label className={styles.fieldControl}><span>{label}</span><input {...common} disabled={!allowed} value={localValue(id,r.state)} onChange={e=>{const value=e.target.value;setLocal(id,value,r.dispatch);if(queryAction)void runRead(id,binding.action_uid,value,{...r,state:{...r.state,search:id==="DB-01-INP-SEARCH"?value:r.state.search,migration_search:id==="DB-01-INP-MIGRATION-SEARCH"?value:r.state.migration_search}})}} placeholder="—"/></label>}
return <button type="button" disabled={!enabled} onClick={click} className={`${styles.button} ${kind==="primary"?styles.primary:""}`} {...common}>{label}</button>;
}
