"use client";
import{createContext,useContext,useEffect,useMemo,useState,type ReactNode}from"react";
import{readDevProjection,type DevNormalizedProjection}from"@/domain/dev/devProjectionPort";
import{invokeDevCommand,isDevCommandAdapterBound}from"@/domain/dev/devCommandPort";
import{DEV_CONTROL_BINDINGS,type DevControlUid}from"@/domain/dev/devControlBindings";
type Runtime={projection:DevNormalizedProjection|null;setProjection:(v:DevNormalizedProjection)=>void;runtimeError:string|null;setRuntimeError:(v:string|null)=>void;correlationId:string|null;setCorrelationId:(v:string|null)=>void};const Ctx=createContext<Runtime|null>(null);
export function DevRuntimeProvider({children}:{children:ReactNode}){const[projection,setProjection]=useState<DevNormalizedProjection|null>(null),[runtimeError,setRuntimeError]=useState<string|null>(null),[correlationId,setCorrelationId]=useState<string|null>(null);useEffect(()=>{const c=new AbortController();void readDevProjection(c.signal).then(r=>{setCorrelationId(r.correlation_id);if(r.ok){setProjection(r.projection);setRuntimeError(null)}else setRuntimeError(`${r.error_uid}: ${r.reason_code}`)});return()=>c.abort()},[]);const value=useMemo(()=>({projection,setProjection,runtimeError,setRuntimeError,correlationId,setCorrelationId}),[projection,runtimeError,correlationId]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useDevRuntimeState(){const v=useContext(Ctx);if(!v)throw new Error("DEV_RUNTIME_PROVIDER_REQUIRED");return v;}
export function useDevGate(gateUid:string){const{projection}=useDevRuntimeState();return projection?.gate_state[gateUid]===true;}
export function DevGovernedButton({controlId,className,children}:{controlId:string;className?:string;children:ReactNode}){const r=useDevRuntimeState(),binding=DEV_CONTROL_BINDINGS[controlId as DevControlUid],allowed=Boolean(binding)&&r.projection?.gate_state[binding.gate_uid]===true,formal=binding?.effect_type!=="UI_CONTEXT_STATE",enabled=allowed&&(!formal||isDevCommandAdapterBound());const click=()=>{if(!binding||!formal)return;void invokeDevCommand({action_uid:binding.action_uid,control_uid:controlId,projection:r.projection}).then(x=>{r.setCorrelationId(x.correlation_id);if(x.ok){r.setProjection(x.projection);r.setRuntimeError(null)}else r.setRuntimeError(`${x.error_uid}: ${x.reason_code}`)})};return <button className={className} type="button" data-control-id={controlId} data-action-uid={binding?.action_uid} data-gate-uid={binding?.gate_uid} data-permission={binding?.permission} data-method-path={binding?.method_path} data-disabled-reason={!allowed?binding?.gate_uid:formal&&!isDevCommandAdapterBound()?"DEV_COMMAND_RUNTIME_NOT_BOUND":undefined} disabled={!enabled} onClick={click}>{children}</button>}
