"use client";

import { createContext, useContext, useEffect, useMemo, useReducer, useState, type Dispatch, type ReactNode } from "react";
import { useI18n } from "@/i18n/LocaleProvider";
import { editText } from "@/i18n/editCatalog";
import { EDIT_CONTROL_BINDINGS, type EditControlUid } from "@/domain/edit/editControlBindings";
import { INITIAL_EDIT_CLIENT_STATE, reduceEditClientState, type EditClientState, type EditExecutionMode, type EditInspectorTab, type EditSourceMode } from "@/domain/edit/editClientState";
import { readEditProjection } from "@/domain/edit/editProjectionPort";
import { invokeGovernedEditAction, isEditActionInvokerBound } from "@/domain/edit/editActionPort";
import { ensureControlledEditClientTestRuntime, rememberControlledEditProjection } from "@/domain/edit/controlledEditClientTestRuntime";
import styles from "./EditVisual.module.css";

export type EditControlKind = "readonly"|"button"|"primary"|"select"|"search"|"segmented"|"list"|"range"|"timecode"|"toggle"|"overview"|"tab"|"number"|"textarea"|"preview"|"dropzone"|"mode-select"|"timeline";
type RuntimeContext = {state:EditClientState;dispatch:Dispatch<Parameters<typeof reduceEditClientState>[1]>;runtimeError:string|null;setRuntimeError:(value:string|null)=>void;};
const Ctx=createContext<RuntimeContext|null>(null);

const TAB_BY_ID: Record<string,EditInspectorTab>={
  "EDIT-01-TAB-CLIP":"CLIP","EDIT-01-TAB-API":"API","EDIT-01-TAB-VOICE":"VOICE","EDIT-01-TAB-AUDIO":"AUDIO","EDIT-01-TAB-LIPSYNC":"LIPSYNC",
  "EDIT-01-TAB-SUBTITLE":"SUBTITLE","EDIT-01-TAB-EVALUATION":"EVALUATION","EDIT-01-TAB-VERSION":"VERSION","EDIT-01-TAB-OUTPUT":"OUTPUT",
};
const VIEW_COMPONENT:Record<string,string>={
  "EDIT-01-ACT-BLUEPRINT-VIEW":"EDIT-01-CMP-SOURCE-BAR","EDIT-01-ACT-PACKAGE-VIEW":"EDIT-01-CMP-SOURCE-BAR","EDIT-01-ACT-MANIFEST-VIEW":"EDIT-01-CMP-MEDIA-BIN",
  "EDIT-01-ACT-API-COMPARE":"EDIT-01-CMP-API","EDIT-01-ACT-VOICE-PREVIEW":"EDIT-01-CMP-VOICE","EDIT-01-ACT-VOICE-COMPARE":"EDIT-01-CMP-VOICE",
  "EDIT-01-ACT-MIX-PREVIEW":"EDIT-01-CMP-AUDIO","EDIT-01-ACT-LIPSYNC-PREVIEW":"EDIT-01-CMP-LIPSYNC","EDIT-01-ACT-VERSION-COMPARE":"EDIT-01-CMP-VERSION",
  "EDIT-01-ACT-RENDER-SETTINGS":"EDIT-01-CMP-OUTPUT","EDIT-01-ACT-EVAL-EVIDENCE":"EDIT-01-CMP-STAGE-EVALUATION",
};
function gatePass(state:EditClientState,gateUid:string|null|undefined){if(!gateUid)return false;if(gateUid==="EDIT-01-GATE-CONTEXT-MUTABLE")return state.resolved.page_state_uid!==null&&state.resolved.page_state_uid!=="EDIT-01-ST-PAGE-LOCKED"&&state.resolved.page_state_uid!=="EDIT-01-ST-PAGE-HANDED_OFF";if(gateUid==="EDIT-01-GATE-STANDALONE")return state.source_mode==="STANDALONE_UPLOAD";return state.resolved.gate_state[gateUid]===true;}
function readonlyValue(id:string,state:EditClientState,runtimeError:string|null){if(id==="EDIT-01-LBL-PAGE-STATE")return state.resolved.page_state_uid??"—";if(id==="EDIT-01-LBL-CURRENT-STAGE")return state.resolved.current_stage_uid??"—";if(id==="EDIT-01-LBL-STAGE-SCORE")return state.resolved.current_stage_score===null?"—":String(state.resolved.current_stage_score);if(id==="EDIT-01-LBL-ERROR-STATE")return runtimeError??state.resolved.current_error_uid??"—";if(id==="EDIT-01-FLD-PROJECT")return state.resolved.project_id??"—";if(id==="EDIT-01-FLD-TOPIC")return state.resolved.topic_id??"—";if(id==="EDIT-01-FLD-TASK")return state.resolved.task_id??"—";if(id==="EDIT-01-FLD-CLIP-ID")return state.selected_clip_ref??state.resolved.values[id]??"—";if(id==="EDIT-01-FLD-TRACK-ID")return state.selected_track_ref??state.resolved.values[id]??"—";if(id==="EDIT-01-FLD-TIMECODE")return state.playhead===null?"—":String(state.playhead);if(id==="EDIT-01-LBL-BINDING-FINGERPRINT")return state.resolved.input_fingerprint??"—";if(id==="EDIT-01-LBL-LIPSYNC-SYNC-BINDING"||id==="EDIT-01-LBL-SUB-SYNC-BINDING")return state.resolved.dialogue_timing_binding_ref??"—";return state.resolved.values[id]??"—";}
function listItems(id:string,state:EditClientState){return state.resolved.lists[id]??[];}
function focusComponent(uid:string|undefined){if(!uid)return;requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[data-component-uid="${uid}"]`)?.scrollIntoView({block:"nearest",inline:"nearest"}));}
async function syncProjection(dispatch:Dispatch<Parameters<typeof reduceEditClientState>[1]>,setRuntimeError:(value:string|null)=>void){const result=await readEditProjection();if(result.ok){rememberControlledEditProjection(result.context);dispatch({type:"BIND_RESOLVED_CONTEXT",value:result.context});setRuntimeError(null);return true;}setRuntimeError(`${result.error_uid}: ${result.reason_code}`);return false;}

export function EditRuntimeProvider({children}:{children:ReactNode}){const[state,dispatch]=useReducer(reduceEditClientState,INITIAL_EDIT_CLIENT_STATE);const[runtimeError,setRuntimeError]=useState<string|null>(null);useEffect(()=>{ensureControlledEditClientTestRuntime();const controller=new AbortController();void readEditProjection(controller.signal).then(result=>{if(result.ok){rememberControlledEditProjection(result.context);dispatch({type:"BIND_RESOLVED_CONTEXT",value:result.context});setRuntimeError(null);}else setRuntimeError(`${result.error_uid}: ${result.reason_code}`);});return()=>controller.abort();},[]);const value=useMemo(()=>({state,dispatch,runtimeError,setRuntimeError}),[state,runtimeError]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>;}
export function useEditRuntimeState(){const value=useContext(Ctx);if(!value)throw new Error("EDIT_RUNTIME_PROVIDER_REQUIRED");return value;}

async function invokeFormalAction(id:EditControlUid,state:EditClientState,dispatch:Dispatch<Parameters<typeof reduceEditClientState>[1]>,setRuntimeError:(v:string|null)=>void){const binding=EDIT_CONTROL_BINDINGS[id];if(!binding.action_uid){setRuntimeError("EDIT-01-ERR-CONTEXT-001: CONTROL_HAS_NO_ACTION");return;}if(!isEditActionInvokerBound()){setRuntimeError("EDIT-01-ERR-CONTEXT-001: EDIT_ACTION_CLIENT_ADAPTER_NOT_BOUND");return;}dispatch({type:"BUSY",value:binding.action_uid});rememberControlledEditProjection(state.resolved);try{const result=await invokeGovernedEditAction({action_uid:binding.action_uid,source_mode:state.source_mode,state});if(!result.ok){setRuntimeError(`${result.error_uid}: ${result.reason_code}`);dispatch({type:"RUNTIME_RESULT",action_uid:binding.action_uid,result:`ERROR:${result.reason_code}`});return;}const embedded=result.value&&typeof result.value==="object"?(result.value as{projection?:unknown}).projection:null;if(embedded&&typeof embedded==="object"){const projection=embedded as EditClientState["resolved"];rememberControlledEditProjection(projection);dispatch({type:"BIND_RESOLVED_CONTEXT",value:projection});setRuntimeError(null);}else await syncProjection(dispatch,setRuntimeError);dispatch({type:"RUNTIME_RESULT",action_uid:binding.action_uid,result:"ACTION_BOUND"});}finally{dispatch({type:"BUSY",value:null});}}

const FORMAL_MUTATION_ACTIONS=new Set(["EDIT-01-ACT-CORRECTION-EXECUTE","EDIT-01-ACT-API-APPLY"]);
function isLocalEffect(effect:string|null|undefined){return effect==="UI_ONLY"||effect==="CONTEXT_STATE"||effect==="DRAFT_MUTATION";}
function localAction(controlId:string,state:EditClientState,dispatch:Dispatch<Parameters<typeof reduceEditClientState>[1]>,setRuntimeError:(v:string|null)=>void,value?:unknown,scopeRef?:string){const binding=EDIT_CONTROL_BINDINGS[controlId as EditControlUid];const action=binding?.action_uid;if(!action)return false;setRuntimeError(null);
  const contextValue=typeof value==="string"&&value?value:null;
  if(controlId==="EDIT-01-FLD-PROJECT"){dispatch({type:"CONTEXT_PROJECT_SET",value:contextValue});return true;}if(controlId==="EDIT-01-FLD-TOPIC"){dispatch({type:"CONTEXT_TOPIC_SET",value:contextValue});return true;}if(controlId==="EDIT-01-FLD-TASK"){dispatch({type:"CONTEXT_TASK_SET",value:contextValue});return true;}
  if(controlId==="EDIT-01-BTN-PLAY"){dispatch({type:"PLAY"});return true;}if(controlId==="EDIT-01-BTN-PAUSE"){dispatch({type:"PAUSE"});return true;}if(controlId==="EDIT-01-BTN-PREV-FRAME"){dispatch({type:"SEEK",value:Math.max(0,Number(state.playhead??0)-1)});return true;}if(controlId==="EDIT-01-BTN-NEXT-FRAME"){dispatch({type:"SEEK",value:Number(state.playhead??0)+1});return true;}
  if(controlId==="EDIT-01-BTN-CLEAR-RANGE"){dispatch({type:"RANGE_CLEAR"});return true;}if(controlId==="EDIT-01-CTL-SNAP"){dispatch({type:"SNAP"});return true;}if(controlId==="EDIT-01-BTN-ZOOM-IN"){dispatch({type:"ZOOM_IN"});return true;}if(controlId==="EDIT-01-BTN-ZOOM-OUT"){dispatch({type:"ZOOM_OUT"});return true;}if(controlId==="EDIT-01-BTN-ZOOM-FIT"){dispatch({type:"ZOOM_FIT"});return true;}if(controlId==="EDIT-01-BTN-MUTE"){dispatch({type:"MUTE"});return true;}if(controlId==="EDIT-01-CTL-LOOP"){dispatch({type:"LOOP"});return true;}
  if(controlId==="EDIT-01-BTN-SET-IN"){if(state.playhead!==null)dispatch({type:"RANGE_IN",value:state.playhead});else setRuntimeError("EDIT-01-ERR-TIME-001: CANONICAL_PLAYHEAD_REQUIRED");return true;}if(controlId==="EDIT-01-BTN-SET-OUT"){if(state.playhead!==null)dispatch({type:"RANGE_OUT",value:state.playhead});else setRuntimeError("EDIT-01-ERR-TIME-001: CANONICAL_PLAYHEAD_REQUIRED");return true;}
  if(controlId==="EDIT-01-BTN-FULLSCREEN"){const el=document.querySelector('[data-component-uid="EDIT-01-CMP-PREVIEW"]');if(document.fullscreenElement){void document.exitFullscreen().catch(()=>setRuntimeError("EDIT-01-ERR-CONTEXT-001: FULLSCREEN_EXIT_FAILED"));}else if(el instanceof HTMLElement&&el.requestFullscreen){void el.requestFullscreen().catch(()=>setRuntimeError("EDIT-01-ERR-CONTEXT-001: FULLSCREEN_REQUEST_FAILED"));}dispatch({type:"LOCAL_ACTION",action_uid:action,result:"FULLSCREEN_TOGGLED"});return true;}
  if(controlId==="EDIT-01-CTL-DROP-TIMELINE"){const media=typeof value==="string"&&value?value:state.selected_media_ref;if(!media){setRuntimeError("EDIT-01-ERR-MEDIA-001: MEDIA_SELECTION_REQUIRED");return true;}dispatch({type:"CLIP_SELECT",value:`WORKING-CLIP:${media}`});dispatch({type:"LOCAL_ACTION",action_uid:action,dirty:true,result:`CLIP_INSERT:${media}`});return true;}
  if(controlId==="EDIT-01-CTL-RULER"||controlId==="EDIT-01-CTL-PLAYHEAD"){dispatch({type:"SEEK",value:Number(value??0)});dispatch({type:"LOCAL_ACTION",action_uid:action,result:`SEEK:${String(value??0)}`});return true;}if(controlId==="EDIT-01-CTL-MINI-TIMELINE"||controlId==="EDIT-01-CTL-MARKER-RAIL"){dispatch({type:"LOCAL_ACTION",action_uid:action,result:`TIMELINE_NAV:${String(value??0)}`});return true;}
  if(scopeRef&&["EDIT-01-CTL-TRACK-VISIBLE","EDIT-01-CTL-TRACK-MUTE","EDIT-01-CTL-TRACK-SOLO","EDIT-01-CTL-TRACK-LOCK"].includes(controlId)){dispatch({type:"TRACK_SELECT",value:scopeRef});dispatch({type:"LOCAL_ACTION",action_uid:action,dirty:binding.effect_type==="DRAFT_MUTATION",result:`TRACK:${scopeRef}:${controlId}`});return true;}
  if(controlId==="EDIT-01-CTL-SUBTITLE-TOGGLE"){dispatch({type:"SUBTITLE_TOGGLE"});return true;}if(controlId==="EDIT-01-FLD-MEDIA-SEARCH"){dispatch({type:"MEDIA_SEARCH",value:String(value??"")});return true;}if(controlId==="EDIT-01-CTL-MEDIA-TYPE-FILTER"){dispatch({type:"MEDIA_FILTER",value:typeof value==="string"&&value?value:null});return true;}if(controlId==="EDIT-01-LST-MEDIA"){dispatch({type:"MEDIA_SELECT",value:typeof value==="string"?value:null});return true;}if(controlId==="EDIT-01-LST-EVAL-ISSUES"){dispatch({type:"ISSUE_SELECT",value:typeof value==="string"?value:null});return true;}if(controlId==="EDIT-01-LST-VERSION-HISTORY"){dispatch({type:"VERSION_SELECT",value:typeof value==="string"?value:null});return true;}
  if(binding.effect_type==="UI_ONLY"){dispatch({type:"VIEW_ACTION",action_uid:action});focusComponent(VIEW_COMPONENT[action]);return true;}if(binding.effect_type==="DRAFT_MUTATION"){dispatch({type:"LOCAL_ACTION",action_uid:action,dirty:true,result:`WORKING_DRAFT_MUTATION:${String(value??"")}`});return true;}if(binding.effect_type==="CONTEXT_STATE"){dispatch({type:"LOCAL_ACTION",action_uid:action,result:`CONTEXT_STATE:${String(value??"")}`});focusComponent(VIEW_COMPONENT[action]);return true;}return false;}

export function EditRuntimeControl({controlId,kind,compact=false,scopeRef}:{controlId:string;kind:EditControlKind;compact?:boolean;scopeRef?:string}){const runtime=useEditRuntimeState();const{state,dispatch,runtimeError,setRuntimeError}=runtime;const{locale}=useI18n();const id=controlId as EditControlUid;const binding=EDIT_CONTROL_BINDINGS[id];const label=editText(locale,controlId);const gateAllowed=Boolean(binding)&&gatePass(state,binding.gate_uid);const executable=Boolean(binding?.action_uid);const local=Boolean(binding&&isLocalEffect(binding.effect_type)&&!FORMAL_MUTATION_ACTIONS.has(binding.action_uid??""));const formal=executable&&!local;const formalReady=!formal||isEditActionInvokerBound();const busy=state.busy_action!==null;const projectContextControl=controlId==="EDIT-01-FLD-PROJECT"||controlId==="EDIT-01-FLD-TOPIC"||controlId==="EDIT-01-FLD-TASK";const contextDependencyBlocked=state.source_mode==="PROJECT_TASK"&&(controlId==="EDIT-01-FLD-TOPIC"||controlId==="EDIT-01-FLD-TASK")&&!state.resolved.project_id;const enabled=executable&&gateAllowed&&formalReady&&!busy&&!contextDependencyBlocked;const disabledReason=!binding?"CONTROL_NOT_IN_AUTHORITY":!executable?"READ_ONLY":!gateAllowed?binding.gate_uid:!formalReady?"FORMAL_RUNTIME_ADAPTER_NOT_BOUND":busy?"BUSY":contextDependencyBlocked?"PROJECT_REQUIRED":undefined;const common={"data-control-id":controlId,"data-action-uid":binding?.action_uid??undefined,"data-gate-uid":binding?.gate_uid??undefined,"data-permission-uid":binding?.permission_uid??undefined,"data-effect-type":binding?.effect_type??undefined,"data-disabled-reason":disabledReason,"data-view-active":binding?.action_uid&&state.active_view_action===binding.action_uid?"true":undefined,"data-last-action":state.last_action_uid===binding?.action_uid?"true":undefined,"data-busy-action":state.busy_action??undefined,"data-scope-ref":scopeRef};
  const act=(value?:unknown)=>{if(!binding?.action_uid){setRuntimeError("EDIT-01-ERR-CONTEXT-001: ACTION_BINDING_MISSING");return;}if(busy){setRuntimeError(`EDIT-01-ERR-CONTEXT-001: BUSY:${state.busy_action}`);return;}if(!gateAllowed){setRuntimeError(`EDIT-01-ERR-CONTEXT-001: ${binding.gate_uid}:NOT_SATISFIED`);return;}if(contextDependencyBlocked){setRuntimeError("EDIT-01-ERR-CONTEXT-001: PROJECT_REQUIRED");return;}if(local){if(!localAction(controlId,state,dispatch,setRuntimeError,value,scopeRef))setRuntimeError("EDIT-01-ERR-CONTEXT-001: LOCAL_ACTION_UNHANDLED");return;}if(!formalReady){setRuntimeError("EDIT-01-ERR-CONTEXT-001: EDIT_ACTION_CLIENT_ADAPTER_NOT_BOUND");return;}void invokeFormalAction(id,state,dispatch,setRuntimeError);};
  if(kind==="readonly"||kind==="overview")return <div className={`${styles.readonly} ${compact?styles.compact:""}`} {...common}><span>{label}</span><strong>{readonlyValue(controlId,state,runtimeError)}</strong></div>;
  if(kind==="mode-select"){if(state.source_mode==="PROJECT_TASK")return <div className={`${styles.readonly} ${compact?styles.compact:""}`} {...common}><span>{label}</span><strong>{readonlyValue(controlId,state,runtimeError)}</strong></div>;const items=listItems(controlId,state);return <label className={styles.fieldControl}><span>{label}</span><select {...common} disabled={!enabled||items.length===0} defaultValue="" onChange={event=>act(event.target.value)}><option value="">—</option>{items.map(item=><option key={item.ref} value={item.ref}>{item.label}</option>)}</select></label>;}
  if(kind==="dropzone")return <button className={styles.button} type="button" disabled={!enabled} draggable={false} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();act(event.dataTransfer.getData("text/plain")||state.selected_media_ref||undefined)}} onClick={()=>act(state.selected_media_ref??undefined)} {...common}>{label}</button>;
  if(kind==="timeline"){const current=typeof state.playhead==="number"?state.playhead:0;return <label className={styles.rangeControl}><span>{label}</span><input {...common} disabled={!enabled} type="range" min="0" max="1000" value={Math.max(0,Math.min(1000,current))} onChange={event=>act(Number(event.target.value))}/></label>;}
  if(kind==="list"){const items=listItems(controlId,state);return <div className={styles.listControl} {...common}><span>{label}</span><div className={styles.listEmpty}>{items.length?items.map(item=><button type="button" key={item.ref} disabled={busy||!gateAllowed} onClick={()=>act(item.ref)}>{item.label}</button>):"—"}</div></div>;}
  if(kind==="preview"){const uri=controlId==="EDIT-01-PNL-FINAL-PREVIEW"?state.resolved.final_preview_uri:state.resolved.preview_uri;return <div className={styles.previewControl} {...common}><span>{label}</span><div data-preview-ref={uri??undefined}>{uri??"—"}</div></div>;}
  if(kind==="segmented"){const source=controlId==="EDIT-01-CTL-SOURCE-MODE";const options=source?["PROJECT_TASK","STANDALONE_UPLOAD"]:["AUTO","MANUAL"];return <div className={styles.segmentedControl} {...common} aria-label={label}><span>{label}</span><div className={styles.segmentedButtons}>{options.map(option=><button key={option} type="button" disabled={!enabled} aria-pressed={source?state.source_mode===option:state.execution_mode===option} onClick={()=>{if(source){const nextMode=option as EditSourceMode;dispatch({type:"SOURCE_MODE",value:nextMode});dispatch({type:"LOCAL_ACTION",action_uid:binding?.action_uid??"EDIT-01-ACT-SOURCE-MODE-SET",result:`SOURCE_MODE:${option}`});if(nextMode==="PROJECT_TASK")void syncProjection(dispatch,setRuntimeError);}else{dispatch({type:"EXECUTION_MODE",value:option as EditExecutionMode});}}}>{option}</button>)}</div></div>;}
  if(kind==="tab"){const tab=TAB_BY_ID[controlId];return <button className={`${styles.tab} ${state.inspector_tab===tab?styles.selectedTab:""}`} type="button" disabled={!enabled} onClick={()=>{if(tab)dispatch({type:"INSPECTOR_TAB",value:tab});if(binding?.action_uid)dispatch({type:"VIEW_ACTION",action_uid:binding.action_uid});}} {...common}>{label}</button>;}
  if(kind==="textarea"){const correction=controlId==="EDIT-01-FLD-API-INSTRUCTION";const value=correction?state.correction_instruction:undefined;return <label className={styles.fieldControl}><span>{label}</span><textarea {...common} disabled={!enabled} value={value} defaultValue={correction?undefined:""} onChange={event=>correction?dispatch({type:"CORRECTION_INSTRUCTION",value:event.target.value}):binding?.action_uid&&dispatch({type:"LOCAL_ACTION",action_uid:binding.action_uid,dirty:true,result:`TEXT:${event.target.value}`})} placeholder="—" /></label>;}
  if(kind==="select"){if(projectContextControl&&state.source_mode==="STANDALONE_UPLOAD")return null;if(controlId==="EDIT-01-CTL-PLAYBACK-RATE")return <label className={styles.fieldControl}><span>{label}</span><select {...common} disabled={!enabled} value={state.playback_rate} onChange={event=>dispatch({type:"RATE",value:Number(event.target.value) as EditClientState["playback_rate"]})}>{[0.25,0.5,1,1.5,2].map(value=><option key={value} value={value}>{value}x</option>)}</select></label>;const items=listItems(controlId,state);const exact=controlId==="EDIT-01-FLD-PROJECT"?state.resolved.project_id:controlId==="EDIT-01-FLD-TOPIC"?state.resolved.topic_id:controlId==="EDIT-01-FLD-TASK"?state.resolved.task_id:controlId==="EDIT-01-CTL-AUDIO-MONITOR"?state.audio_monitor:"";const requiredContext=projectContextControl&&state.source_mode==="PROJECT_TASK";return <label className={styles.fieldControl}><span>{label}</span><select {...common} disabled={!enabled||items.length===0} value={exact??""} onChange={event=>controlId==="EDIT-01-CTL-AUDIO-MONITOR"?dispatch({type:"AUDIO_MONITOR",value:event.target.value||null}):act(event.target.value)}><option value="" disabled={requiredContext}>—</option>{items.map(item=><option key={item.ref} value={item.ref}>{item.label}</option>)}</select></label>;}
  if(kind==="search"||kind==="timecode"||kind==="number"){const mediaSearch=controlId==="EDIT-01-FLD-MEDIA-SEARCH";const timecode=controlId==="EDIT-01-FLD-TIMECODE";const value=mediaSearch?state.media_search:timecode?(state.playhead===null?"":String(state.playhead)):undefined;return <label className={styles.fieldControl}><span>{label}</span><input {...common} disabled={!enabled} value={value} defaultValue={value===undefined?"":undefined} onChange={event=>mediaSearch?act(event.target.value):timecode?dispatch({type:"SEEK",value:event.target.value}):binding?.action_uid&&dispatch({type:"LOCAL_ACTION",action_uid:binding.action_uid,dirty:true,result:`VALUE:${event.target.value}`})} placeholder="—" inputMode={kind==="number"?"decimal":undefined}/></label>;}
  if(kind==="range"){const previewVolume=controlId==="EDIT-01-CTL-VOLUME";if(controlId==="EDIT-01-CTL-IN-OUT"){const a=typeof state.range_in==="number"?state.range_in:0,b=typeof state.range_out==="number"?state.range_out:100;return <fieldset className={styles.rangeControl} {...common} disabled={!enabled}><legend>{label}</legend><input aria-label={`${label} In`} type="range" min="0" max="1000" value={Math.max(0,Math.min(1000,a))} onChange={event=>dispatch({type:"RANGE_IN",value:Number(event.target.value)})}/><input aria-label={`${label} Out`} type="range" min="0" max="1000" value={Math.max(0,Math.min(1000,b))} onChange={event=>dispatch({type:"RANGE_OUT",value:Number(event.target.value)})}/></fieldset>;}const value=previewVolume?Math.round(state.preview_volume*100):50;return <label className={styles.rangeControl}><span>{label}</span><input {...common} disabled={!enabled} type="range" min="0" max="100" value={value} onChange={event=>previewVolume?dispatch({type:"PREVIEW_VOLUME",value:Number(event.target.value)/100}):act(Number(event.target.value))}/></label>;}
  return <button className={`${styles.button} ${kind==="primary"?styles.primary:""}`} type="button" disabled={!enabled} onClick={()=>act()} {...common}>{label}</button>;
}