"use client";
import{createContext,useContext,useEffect,useMemo,useState,type ReactNode}from"react";
import{readErpProjection,type ErpNormalizedProjection}from"@/domain/erp/erpProjectionPort";
import{invokeErpCommand,isErpCommandAdapterBound}from"@/domain/erp/erpCommandPort";
import{ERP_CONTROL_BINDINGS,type ErpControlBinding,type ErpControlUid}from"@/domain/erp/erpControlBindings";
type Runtime={projection:ErpNormalizedProjection|null;setProjection:(v:ErpNormalizedProjection)=>void;runtimeError:string|null;setRuntimeError:(v:string|null)=>void;correlationId:string|null;setCorrelationId:(v:string|null)=>void};const Ctx=createContext<Runtime|null>(null);
export function ErpRuntimeProvider({children}:{children:ReactNode}){const[projection,setProjection]=useState<ErpNormalizedProjection|null>(null),[runtimeError,setRuntimeError]=useState<string|null>(null),[correlationId,setCorrelationId]=useState<string|null>(null);useEffect(()=>{const c=new AbortController();void readErpProjection(c.signal).then(r=>{setCorrelationId(r.correlation_id);if(r.ok){setProjection(r.projection);setRuntimeError(null)}else setRuntimeError(`${r.error_uid}: ${r.reason_code}`)});return()=>c.abort()},[]);const value=useMemo(()=>({projection,setProjection,runtimeError,setRuntimeError,correlationId,setCorrelationId}),[projection,runtimeError,correlationId]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useErpRuntimeState(){const v=useContext(Ctx);if(!v)throw new Error("ERP_RUNTIME_PROVIDER_REQUIRED");return v;}
export function ErpValue({controlId}:{controlId:string}){const{projection}=useErpRuntimeState();return <>{projection?.values[controlId]??"—"}</>}
export function ErpGovernedButton({controlId,className,children,onUiClick}:{controlId:string;className?:string;children:ReactNode;onUiClick?:()=>void}){const r=useErpRuntimeState(),binding:ErpControlBinding|undefined=ERP_CONTROL_BINDINGS[controlId as ErpControlUid],allowed=Boolean(binding)&&r.projection?.gate_state[binding.gate_uid]===true,ui=binding?.effect_type==="UI_CONTEXT_STATE",enabled=allowed&&(ui||isErpCommandAdapterBound());const click=()=>{if(!binding)return;if(ui){onUiClick?.();return}void invokeErpCommand({action_uid:binding.action_uid,control_uid:controlId,projection:r.projection}).then(x=>{r.setCorrelationId(x.correlation_id);if(x.ok){r.setProjection(x.projection);r.setRuntimeError(null)}else r.setRuntimeError(`${x.error_uid}: ${x.reason_code}`)})};return <button type="button" className={className} data-control-id={controlId} data-action-uid={binding?.action_uid} data-gate-uid={binding?.gate_uid} data-permission-uid={binding?.permission_uid} data-disabled-reason={!allowed?binding?.gate_uid:!ui&&!isErpCommandAdapterBound()?"ERP_COMMAND_RUNTIME_NOT_BOUND":undefined} disabled={!enabled} onClick={click}>{children}</button>}
