"use client";
import{createContext,useContext,useEffect,useMemo,useState,type ReactNode}from"react";
import{INITIAL_IAM_CLIENT_STATE,openIamCreate,openIamEdit,selectAllAdmin,selectAllFront,type IamClientState}from"@/domain/iam/iamClientState";
import{readIamProjection,invokeIamClientCommand,isIamClientCommandAdapterBound,type IamNormalizedProjection}from"@/domain/iam/iamClientPort";
import{IAM_CONTROL_BINDINGS,type IamControlBinding,type IamControlUid}from"@/domain/iam/iamControlBindings";
type Runtime={client:IamClientState;setClient:(v:IamClientState)=>void;projection:IamNormalizedProjection|null;setProjection:(v:IamNormalizedProjection)=>void;runtimeError:string|null;setRuntimeError:(v:string|null)=>void;correlationId:string|null;setCorrelationId:(v:string|null)=>void};const Ctx=createContext<Runtime|null>(null);
export function IamRuntimeProvider({children}:{children:ReactNode}){const[client,setClient]=useState<IamClientState>(INITIAL_IAM_CLIENT_STATE),[projection,setProjection]=useState<IamNormalizedProjection|null>(null),[runtimeError,setRuntimeError]=useState<string|null>(null),[correlationId,setCorrelationId]=useState<string|null>(null);useEffect(()=>{const c=new AbortController();void readIamProjection(c.signal).then(r=>{setCorrelationId(r.correlation_id);if(r.ok){setProjection(r.projection);setRuntimeError(null)}else setRuntimeError(`${r.error_uid}: ${r.reason_code}`)});return()=>c.abort()},[]);const value=useMemo(()=>({client,setClient,projection,setProjection,runtimeError,setRuntimeError,correlationId,setCorrelationId}),[client,projection,runtimeError,correlationId]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useIamRuntimeState(){const v=useContext(Ctx);if(!v)throw new Error("IAM_RUNTIME_PROVIDER_REQUIRED");return v;}
export function useIamGate(gateUid:string){return useIamRuntimeState().projection?.gate_state[gateUid]===true;}
function toggle(list:string[],key:string,on:boolean){return on?[...new Set([...list,key])]:list.filter(x=>x!==key)}
export function setIamFrontL1(r:Runtime,key:string,on:boolean){r.setClient({...r.client,front_l1:toggle(r.client.front_l1,key,on)})}
export function setIamAdminL1(r:Runtime,key:string,on:boolean){r.setClient({...r.client,admin_l1:toggle(r.client.admin_l1,key,on)})}
export function IamGovernedButton({controlId,className,children,selectedAccountId}:{controlId:string;className?:string;children:ReactNode;selectedAccountId?:string|null}){const r=useIamRuntimeState(),binding:IamControlBinding|undefined=IAM_CONTROL_BINDINGS[controlId as IamControlUid],allowed=Boolean(binding)&&r.projection?.gate_state[binding.gate_uid]===true,local=binding?.effect_type==="UI_ONLY"||binding?.effect_type==="DRAFT_UI",enabled=allowed&&(local||isIamClientCommandAdapterBound());const click=()=>{if(!binding)return;switch(binding.action_uid){case"IAM-01-ACT-OPEN-CREATE":r.setClient(openIamCreate(r.client));return;case"IAM-01-ACT-OPEN-EDIT":if(selectedAccountId)r.setClient(openIamEdit(r.client,selectedAccountId));return;case"IAM-01-ACT-FRONT-ALL-DRAFT":r.setClient(selectAllFront(r.client,r.client.front_l1.length!==9));return;case"IAM-01-ACT-BACK-ALL-DRAFT":r.setClient(selectAllAdmin(r.client,r.client.admin_l1.length!==9));return;}if(local)return;void invokeIamClientCommand({action_uid:binding.action_uid,control_uid:controlId,client_state:r.client,projection:r.projection}).then(x=>{r.setCorrelationId(x.correlation_id);if(x.ok){r.setProjection(x.projection);r.setRuntimeError(null);if(x.client_state&&typeof x.client_state==="object")r.setClient(x.client_state as IamClientState)}else r.setRuntimeError(`${x.error_uid}: ${x.reason_code}`)})};return <button type="button" className={className} data-control-id={controlId} data-action-uid={binding?.action_uid} data-gate-uid={binding?.gate_uid} data-permission={binding?.permission} data-disabled-reason={!allowed?binding?.gate_uid:!local&&!isIamClientCommandAdapterBound()?"IAM_CLIENT_COMMAND_RUNTIME_NOT_BOUND":undefined} disabled={!enabled} onClick={click}>{children}</button>}
