"use client";
import{createContext,useContext,useEffect,useMemo,useReducer,type Dispatch,type ReactNode}from'react';
import{useI18n}from'@/i18n/LocaleProvider';
import{infoText,type InfoControlSpec}from'@/i18n/infoCatalog';
import{INFO_CONTROL_BINDINGS,type InfoControlUid}from'@/domain/info/infoControlBindings';
import{INITIAL_INFO_CLIENT_STATE,reduceInfoClientState,type InfoClientAction,type InfoClientState}from'@/domain/info/infoClientState';
import{readInfoProjection}from'@/domain/info/infoProjectionPort';
import{buildAndInvokeInfoCommand,isInfoCommandPayloadBuilderBound,type InfoCommandAction}from'@/domain/info/infoCommandPort';
import styles from'./InfoVisual.module.css';
type Runtime={state:InfoClientState;dispatch:Dispatch<InfoClientAction>};const Ctx=createContext<Runtime|null>(null);
export function InfoRuntimeProvider({children}:{children:ReactNode}){const[state,dispatch]=useReducer(reduceInfoClientState,INITIAL_INFO_CLIENT_STATE);useEffect(()=>{const c=new AbortController();void readInfoProjection(c.signal).then(r=>r.ok?dispatch({type:'PROJECTION',value:r.projection,correlation_id:r.correlation_id}):dispatch({type:'RUNTIME_ERROR',value:`${r.error_uid}: ${r.reason_code}`,correlation_id:r.correlation_id}));return()=>c.abort();},[]);const v=useMemo(()=>({state,dispatch}),[state]);return <Ctx.Provider value={v}>{children}</Ctx.Provider>}
export function useInfoRuntimeState(){const v=useContext(Ctx);if(!v)throw new Error('INFO_RUNTIME_PROVIDER_REQUIRED');return v;}
function gate(state:InfoClientState,uid:string){return state.projection?.gate_state[uid]===true;}
function valueOf(id:string,state:InfoClientState){const p=state.projection;if(id==='INFO-01-FLD-SCOPE')return p?.authorized_scope??'—';if(id==='INFO-01-FLD-PROJECTION-VERSION')return p?.projection_version??'—';if(id==='INFO-01-FLD-PAGE-STATE')return p?.page_state??'—';if(id==='INFO-01-FLD-LAST-REFRESH')return p?.last_refresh??'—';if(id==='INFO-01-FLD-SOURCE-REF')return state.source_ref??'—';if(id==='INFO-01-FLD-ALERT-REF')return state.alert_ref??'—';if(id==='INFO-01-FLD-FACTPACK-REF')return state.fact_pack_ref??'—';if(id==='INFO-01-FLD-EVIDENCE-REF')return state.evidence_ref??'—';if(id==='INFO-01-FLD-RESEARCH-REF')return state.research_ref??'—';if(id==='INFO-01-FLD-CANDIDATE-ID')return state.candidate_ref??'—';if(id==='INFO-01-FLD-CORRELATION')return state.correlation_id??'—';if(id==='INFO-01-FLD-DISABLED')return state.runtime_error??'—';return p?.values[id]??'—';}
const FORMAL=new Set<InfoCommandAction>(['INFO-01-ACT-REFRESH','INFO-01-ACT-SEARCH','INFO-01-ACT-EXPORT','INFO-01-ACT-ADOPT-CONTEXT','INFO-01-ACT-CANDIDATE-DECIDE']);
export function InfoRuntimeControl({item}:{item:InfoControlSpec}){const{state,dispatch}=useInfoRuntimeState(),{locale}=useI18n(),binding=INFO_CONTROL_BINDINGS[item.id as InfoControlUid],label=infoText(locale,item),allowed=Boolean(binding)&&gate(state,binding.gate_uid),formal=FORMAL.has(binding?.action_uid as InfoCommandAction),enabled=allowed&&(!formal||isInfoCommandPayloadBuilderBound()),common={"data-control-id":item.id,"data-component-uid":item.component,"data-visual-uid":item.visual,"data-action-uid":binding?.action_uid,"data-gate-uid":binding?.gate_uid,"data-permission-uid":binding?.permission_uid,"data-effect-type":binding?.effect_type,"data-disabled-reason":!allowed?binding?.gate_uid:formal&&!isInfoCommandPayloadBuilderBound()?'INFO_COMMAND_PAYLOAD_ADAPTER_NOT_BOUND':undefined};
const select=(ref:string)=>{switch(binding?.action_uid){case'INFO-01-ACT-SOURCE-SELECT':dispatch({type:'SOURCE',value:ref});break;case'INFO-01-ACT-ALERT-SELECT':dispatch({type:'ALERT',value:ref});break;case'INFO-01-ACT-FACTPACK-SELECT':dispatch({type:'FACTPACK',value:ref});break;case'INFO-01-ACT-EVIDENCE-SELECT':dispatch({type:'EVIDENCE',value:ref});break;case'INFO-01-ACT-RESEARCH-SELECT':dispatch({type:'RESEARCH',value:ref});break;case'INFO-01-ACT-CANDIDATE-SELECT':dispatch({type:'CANDIDATE',value:ref});break;}}
const click=()=>{if(binding?.action_uid==='INFO-01-ACT-FACT-TYPE'){dispatch({type:'FACT_VIEW',value:item.id==='INFO-01-TAB-FACT'?'FACT':'INFERENCE'});return;}if(binding?.action_uid==='INFO-01-ACT-CITATION-OPEN'){dispatch({type:'CITATION',value:true});return;}if(binding?.action_uid==='INFO-01-ACT-AUDIT-OPEN'){dispatch({type:'AUDIT',value:!state.audit_open});return;}if(formal){void buildAndInvokeInfoCommand({action_uid:binding.action_uid as InfoCommandAction,candidate_ref:state.candidate_ref,scope_filter:state.scope_filter,projection_version:state.projection?.projection_version??null,authorized_scope:state.projection?.authorized_scope??null}).then(r=>dispatch({type:'RUNTIME_ERROR',value:r.ok?null:`${r.error_uid}: ${r.reason_code}`,correlation_id:r.correlation_id}));}};
if(item.type==='READONLY')return <div className={styles.readonly}{...common}><span>{label}</span><strong>{valueOf(item.id,state)}</strong></div>;
if(item.type==='LIST'){const items=state.projection?.lists[item.id]??[];return <div className={styles.listControl}{...common}><span>{label}</span><div className={styles.listView}>{items.length?items.map(x=><button key={x.ref} type="button" disabled={!enabled} onClick={()=>select(x.ref)}>{x.label}</button>):'—'}</div></div>}
if(item.type==='FILTER'){const options=state.projection?.filters[item.id]??[];return <label className={styles.fieldControl}{...common}><span>{label}</span><select disabled={!enabled} value={state.scope_filter??''} onChange={e=>dispatch({type:'SCOPE',value:e.target.value||null})}><option value="">—</option>{options.map(x=><option key={x.ref} value={x.ref}>{x.label}</option>)}</select></label>}
if(item.type==='TAB')return <button type="button" className={styles.tab}{...common} disabled={!enabled} aria-pressed={item.id==='INFO-01-TAB-FACT'?state.fact_view==='FACT':state.fact_view==='INFERENCE'} onClick={click}>{label}</button>;
return <button type="button" disabled={!enabled} onClick={click} className={`${styles.button} ${item.type==='PRIMARY_BUTTON'?styles.primary:''}`} {...common}>{label}</button>}
