"use client";
import{createContext,useContext,useEffect,useMemo,useReducer,type Dispatch,type ReactNode}from"react";
import{useI18n}from"@/i18n/LocaleProvider";
import{qaText}from"@/i18n/qaCatalog";
import{QA_CONTROL_BINDINGS,type QaControlUid,type QaActionUid}from"@/domain/qa/qaControlBindings";
import{INITIAL_QA_CLIENT_STATE,reduceQaClientState,type QaClientAction,type QaClientState,type QaReviewMode}from"@/domain/qa/qaClientState";
import{readQaProjection}from"@/domain/qa/qaProjectionPort";
import{invokeQaFormalAction}from"@/domain/qa/qaActionPort";
import styles from"./QaVisual.module.css";
export type QaControlKind="readonly"|"button"|"primary"|"search"|"select"|"list"|"viewer"|"range"|"segmented"|"table"|"input"|"textarea"|"multiselect";
type RuntimeContext={state:QaClientState;dispatch:Dispatch<QaClientAction>;refresh:()=>Promise<boolean>};const Ctx=createContext<RuntimeContext|null>(null);
const ROOT_CAUSES=["CANON","SCRIPT_VIEW","INSTRUCTION_PACKAGE","INPUT_ASSET","PROVIDER_ROUTE","OUTPUT_ARTIFACT","RIGHTS_POLICY","QUALITY_CRITERIA","EDITING","UNKNOWN"] as const;
const LOCAL_ACTIONS=new Set<QaActionUid>(["QA-01-ACT-NOOP-VIEW","QA-01-ACT-QUEUE-SEARCH","QA-01-ACT-QUEUE-FILTER","QA-01-ACT-REVIEW-SELECT","QA-01-ACT-VIEWER-PLAY","QA-01-ACT-VIEWER-SEEK","QA-01-ACT-VIEWER-VOLUME","QA-01-ACT-VIEWER-FULLSCREEN","QA-01-ACT-COMPARE-TOGGLE","QA-01-ACT-SCRIPT-VIEW","QA-01-ACT-EVIDENCE-VIEW","QA-01-ACT-FINDING-SELECT","QA-01-ACT-MANUAL-VIEW","QA-01-ACT-AUDIT-VIEW","QA-01-ACT-REVIEW-MODE-SET","QA-01-ACT-VIEWER-PREV-FRAME","QA-01-ACT-VIEWER-NEXT-FRAME","QA-01-ACT-EVIDENCE-POINT","QA-01-ACT-EVIDENCE-RANGE-IN","QA-01-ACT-EVIDENCE-RANGE-OUT"]);
const VIEW_ACTIONS:Partial<Record<QaActionUid,string>>={"QA-01-ACT-SCRIPT-VIEW":"QA-01-CMP-SCRIPT","QA-01-ACT-EVIDENCE-VIEW":"QA-01-CMP-EVIDENCE","QA-01-ACT-AUDIT-VIEW":"QA-01-CMP-STATUS","QA-01-ACT-MANUAL-VIEW":"QA-01-CMP-MANUAL"};
function gatePass(state:QaClientState,gate:string){return state.resolved.gate_state[gate]===true;}
function controlVisible(id:QaControlUid,state:QaClientState){const v=QA_CONTROL_BINDINGS[id].visibility_condition;if(!v)return true;if(v==="mode=MANUAL")return state.mode==="MANUAL";if(v==="mode=AUTO")return state.mode==="AUTO";if(v==="ManualReviewCase required/open")return Boolean(state.resolved.manual_review_case_ref)&&String(state.resolved.values["QA-01-FLD-MANUAL-STATE"]??"").includes("OPEN");if(v==="VIDEO_OR_EDIT_OUTPUT")return String(state.resolved.values["QA-01-FLD-PROVENANCE"]??"").includes("EDIT")||String(state.resolved.values["QA-01-FLD-PROVENANCE"]??"").includes("VIDEO");return true;}
function readonlyValue(id:string,state:QaClientState){const r=state.resolved;if(id==="QA-01-FLD-PROJECT")return r.project_id??"—";if(id==="QA-01-FLD-TOPIC")return r.topic_id??"—";if(id==="QA-01-FLD-QA-TASK")return r.qa_task_ref??"—";if(id==="QA-01-FLD-TARGET-OUTPUT")return r.target_output_version_id??"—";if(id==="QA-01-FLD-REVIEW-STATE")return r.values[id]??r.page_state_uid;if(id==="QA-01-FLD-PAGE-STATE")return r.page_state_uid;if(id==="QA-01-FLD-ERROR")return state.runtime_error??r.values[id]??"—";if(id==="QA-01-FLD-CORRELATION")return r.correlation_id??"—";if(id==="QA-01-FLD-AUDIT")return r.audit_ref??r.values[id]??"—";if(id==="QA-01-FLD-CURRENT-TIMECODE")return state.current_timecode??0;if(id==="QA-01-FLD-MANUAL-CASE")return r.manual_review_case_ref??"—";if(id==="QA-01-FLD-FAILED-VERSION")return r.failed_output_version_id??r.values[id]??"—";if(id==="QA-01-FLD-NEW-VERSION")return r.verified_new_output_version_id??r.values[id]??"—";return r.values[id]??"—";}
function listItems(id:string,state:QaClientState){const raw=state.resolved.lists[id]??[];if(id!=="QA-01-LIST-REVIEWS")return raw;const q=state.queue_search.trim().toLowerCase();return raw.filter(x=>(!q||`${x.ref} ${x.label}`.toLowerCase().includes(q))&&(!state.queue_state||String(x.meta?.state??"")===state.queue_state)&&(!state.queue_source_department||String(x.meta?.source_department??"")===state.queue_source_department)&&(!state.queue_severity||String(x.meta?.severity??"")===state.queue_severity));}
async function refreshProjection(dispatch:Dispatch<QaClientAction>){const r=await readQaProjection();if(r.ok){dispatch({type:"BIND_RESOLVED_CONTEXT",value:r.context});dispatch({type:"RUNTIME_ERROR",value:null});return true;}dispatch({type:"RUNTIME_ERROR",value:`${r.error_uid}:${r.reason_code}`,correlation_id:r.correlation_id});return false;}
export function QaRuntimeProvider({children}:{children:ReactNode}){const[state,dispatch]=useReducer(reduceQaClientState,INITIAL_QA_CLIENT_STATE);useEffect(()=>{const c=new AbortController();void readQaProjection(c.signal).then(r=>r.ok?dispatch({type:"BIND_RESOLVED_CONTEXT",value:r.context}):dispatch({type:"RUNTIME_ERROR",value:`${r.error_uid}:${r.reason_code}`,correlation_id:r.correlation_id}));return()=>c.abort();},[]);const value=useMemo(()=>({state,dispatch,refresh:()=>refreshProjection(dispatch)}),[state]);return<Ctx.Provider value={value}>{children}</Ctx.Provider>;}
export function useQaRuntimeState(){const x=useContext(Ctx);if(!x)throw new Error("QA_RUNTIME_PROVIDER_REQUIRED");return x;}
function localAction(id:QaControlUid,state:QaClientState,dispatch:Dispatch<QaClientAction>,value?:unknown){const action=QA_CONTROL_BINDINGS[id].action_uid as QaActionUid;if(id==="QA-01-INP-QUEUE-SEARCH"){dispatch({type:"QUEUE_SEARCH",value:String(value??"")});return;}if(id==="QA-01-SEL-QUEUE-STATE"){dispatch({type:"QUEUE_STATE",value:String(value||"")||null});return;}if(id==="QA-01-SEL-QUEUE-SEVERITY"){dispatch({type:"QUEUE_SEVERITY",value:String(value||"")||null});return;}if(id==="QA-01-SEL-QUEUE-SOURCE-DEPT"){dispatch({type:"QUEUE_SOURCE",value:String(value||"")||null});return;}if(id==="QA-01-LIST-REVIEWS"){dispatch({type:"REVIEW_SELECT",value:String(value||"")||null});return;}if(id==="QA-01-LIST-FINDINGS"){dispatch({type:"FINDING_SELECT",value:String(value||"")||null});return;}if(id==="QA-01-BTN-PLAY"){dispatch({type:"PLAY"});return;}if(id==="QA-01-CTL-SEEK"){dispatch({type:"SEEK",value:Number(value??0)});return;}if(id==="QA-01-BTN-VOLUME"){dispatch({type:"MUTE"});return;}if(id==="QA-01-BTN-FULLSCREEN"){const el=document.querySelector('[data-component-uid="QA-01-CMP-VIEWER"]');if(document.fullscreenElement){void document.exitFullscreen().then(()=>dispatch({type:"FULLSCREEN",value:false})).catch(()=>dispatch({type:"RUNTIME_ERROR",value:"QA-01-ERR-EVIDENCE-001:FULLSCREEN_EXIT_FAILED"}));}else if(el instanceof HTMLElement&&el.requestFullscreen){void el.requestFullscreen().then(()=>dispatch({type:"FULLSCREEN",value:true})).catch(()=>dispatch({type:"RUNTIME_ERROR",value:"QA-01-ERR-EVIDENCE-001:FULLSCREEN_REQUEST_FAILED"}));}else{dispatch({type:"RUNTIME_ERROR",value:"QA-01-ERR-EVIDENCE-001:FULLSCREEN_UNAVAILABLE"});}return;}if(id==="QA-01-BTN-COMPARE"){dispatch({type:"COMPARE"});return;}if(id==="QA-01-BTN-PREV-FRAME"||id==="QA-01-BTN-NEXT-FRAME"){dispatch({type:"RUNTIME_ERROR",value:"QA-01-ERR-OUTPUT-001:SOURCE_OR_PROJECT_TIMEBASE_REQUIRED"});return;}if(id==="QA-01-BTN-FINDING-POINT"){dispatch({type:"EVIDENCE_POINT",value:state.current_timecode});return;}if(id==="QA-01-BTN-EVIDENCE-IN"){dispatch({type:"EVIDENCE_IN",value:state.current_timecode});return;}if(id==="QA-01-BTN-EVIDENCE-OUT"){dispatch({type:"EVIDENCE_OUT",value:state.current_timecode});return;}if(id==="QA-01-BTN-MANUAL-VIEW"){dispatch({type:"MANUAL_VIEW",value:!state.manual_review_open});return;}dispatch({type:"VIEW_ACTION",action_uid:action});const target=VIEW_ACTIONS[action];if(target)requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[data-component-uid="${target}"]`)?.scrollIntoView({block:"nearest"}));}
async function formalAction(id:QaControlUid,state:QaClientState,dispatch:Dispatch<QaClientAction>){const action=QA_CONTROL_BINDINGS[id].action_uid as QaActionUid;dispatch({type:"BUSY",value:action});try{const r=await invokeQaFormalAction(action,state);if(!r.ok){dispatch({type:"RUNTIME_ERROR",value:`${r.error_uid}:${r.reason_code}`,correlation_id:r.correlation_id});dispatch({type:"RUNTIME_RESULT",action_uid:action,result:`ERROR:${r.reason_code}`});return;}if(r.projection)dispatch({type:"BIND_RESOLVED_CONTEXT",value:r.projection});else await refreshProjection(dispatch);dispatch({type:"RUNTIME_ERROR",value:null});dispatch({type:"RUNTIME_RESULT",action_uid:action,result:"ACTION_BOUND"});}finally{dispatch({type:"BUSY",value:null});}}
function derivedOptions(id:string,state:QaClientState){if(id==="QA-01-INP-CORR-ROOT")return ROOT_CAUSES.map(x=>({value:x,label:x}));if(id==="QA-01-INP-CORR-REVALIDATE")return(state.resolved.lists[id]??[]).map(x=>({value:x.ref,label:x.label}));const queue=state.resolved.lists["QA-01-LIST-REVIEWS"]??[];const key=id==="QA-01-SEL-QUEUE-STATE"?"state":id==="QA-01-SEL-QUEUE-SEVERITY"?"severity":id==="QA-01-SEL-QUEUE-SOURCE-DEPT"?"source_department":null;if(!key)return[];return[...new Set(queue.map(x=>String(x.meta?.[key]??"")).filter(Boolean))].map(x=>({value:x,label:x}));}
export function QaRuntimeControl({controlId,kind}:{controlId:string;kind:QaControlKind}){const{state,dispatch}=useQaRuntimeState();const{locale}=useI18n();const id=controlId as QaControlUid;const binding=QA_CONTROL_BINDINGS[id];if(!binding)return null;if(!controlVisible(id,state))return null;const label=qaText(locale,id);const gate=gatePass(state,binding.gate_uid);const action=binding.action_uid as QaActionUid;const local=LOCAL_ACTIONS.has(action);const busy=state.busy_action!==null;const authorityGap=binding.gate_uid==="QA-01-GATE-FINDING"&&!gate;const enabled=gate&&!busy&&action!=="QA-01-ACT-NOOP-VIEW";const disabledReason=authorityGap?"AUTHORITY_GAP_QA_ISSUE_CATEGORY_REGISTRY":!gate?binding.gate_uid:busy?`BUSY:${state.busy_action}`:action==="QA-01-ACT-NOOP-VIEW"?"READ_OR_DRAFT_FIELD":undefined;const common={"data-control-id":id,"data-action-uid":action,"data-gate-uid":binding.gate_uid,"data-permission-uid":binding.permission_uid,"data-disabled-reason":disabledReason,"data-last-action":state.last_action_uid===action?"true":undefined};const act=(value?:unknown)=>{if(!gate){dispatch({type:"RUNTIME_ERROR",value:`QA-01-ERR-GATE-001:${disabledReason}`});return;}if(local)localAction(id,state,dispatch,value);else void formalAction(id,state,dispatch);};
 if(kind==="readonly")return<div className={styles.readonly}{...common}><span>{label}</span><strong>{String(readonlyValue(id,state))}</strong></div>;
 if(kind==="viewer")return<div className={styles.viewerControl}{...common}><span>{label}</span><div className={styles.viewerCanvas} data-viewer-ref={state.resolved.viewer_uri??undefined}>{state.resolved.viewer_uri??"—"}</div></div>;
 if(kind==="table"){const rows=listItems(id,state);return<div className={styles.tableControl}{...common}><span>{label}</span><div className={styles.scoreTable}>{rows.length?<div>{rows.map(x=><div key={x.ref} data-score-ref={x.ref}>{x.label}{x.meta?.score!==undefined?` · ${x.meta.score}`:""}</div>)}</div>:"—"}</div></div>}
 if(kind==="list"){const rows=listItems(id,state);return<div className={styles.listControl}{...common}><span>{label}</span><div className={styles.emptyList}>{rows.length?<div>{rows.map(x=><button type="button" key={x.ref} disabled={!gate||busy||(id==="QA-01-LIST-REVIEWS"&&state.mode==="AUTO")} onClick={()=>act(x.ref)} data-item-ref={x.ref}>{x.label}</button>)}</div>:"—"}</div></div>}
 if(kind==="segmented")return<div className={styles.segmented}{...common}><span>{label}</span><div>{(["AUTO","MANUAL"]as QaReviewMode[]).map(m=><button type="button" key={m} disabled={!gate||busy} className={state.mode===m?styles.selectedSegment:""} aria-pressed={state.mode===m} onClick={()=>dispatch({type:"MODE",value:m})}>{m}</button>)}</div></div>;
 if(kind==="search")return<label className={styles.fieldControl}><span>{label}</span><input {...common} value={state.queue_search} disabled={!gate||busy} onChange={e=>act(e.target.value)} placeholder="—"/></label>;
 if(kind==="range")return<label className={styles.rangeControl}><span>{label}</span><input {...common} disabled={!gate||busy} type="range" min="0" max="100" value={state.seek??0} onChange={e=>act(Number(e.target.value))}/></label>;
 if(kind==="input"){const value=id==="QA-01-INP-FINDING-SCOPE"?state.finding_scope:id==="QA-01-INP-CORR-SCOPE"?state.correction_scope:"";return<label className={styles.fieldControl}><span>{label}</span><input {...common} disabled={!gate||busy||authorityGap} value={value} onChange={e=>id==="QA-01-INP-FINDING-SCOPE"?dispatch({type:"FINDING_SCOPE",value:e.target.value}):dispatch({type:"CORRECTION_SCOPE",value:e.target.value})} placeholder="—"/></label>}
 if(kind==="textarea")return<label className={styles.fieldControl}><span>{label}</span><textarea {...common} disabled={!gate||busy} value={state.correction_action} onChange={e=>dispatch({type:"CORRECTION_ACTION",value:e.target.value})} placeholder="—"/></label>;
 if(kind==="select"||kind==="multiselect"){const options=derivedOptions(id,state);const value=id==="QA-01-SEL-QUEUE-STATE"?(state.queue_state??""):id==="QA-01-SEL-QUEUE-SEVERITY"?(state.queue_severity??""):id==="QA-01-SEL-QUEUE-SOURCE-DEPT"?(state.queue_source_department??""):id==="QA-01-INP-CORR-ROOT"?state.correction_root:id==="QA-01-INP-FINDING-SEVERITY"?state.finding_severity:id==="QA-01-INP-FINDING-CATEGORY"?state.finding_category:"";return<label className={styles.fieldControl}><span>{label}</span><select {...common} disabled={!gate||busy||authorityGap} multiple={kind==="multiselect"} value={kind==="multiselect"?state.correction_revalidate:value} onChange={e=>{if(kind==="multiselect"){dispatch({type:"CORRECTION_REVALIDATE",value:Array.from(e.target.selectedOptions).map(o=>o.value)});return;}if(id==="QA-01-SEL-QUEUE-STATE")localAction(id,state,dispatch,e.target.value);else if(id==="QA-01-SEL-QUEUE-SEVERITY")localAction(id,state,dispatch,e.target.value);else if(id==="QA-01-SEL-QUEUE-SOURCE-DEPT")localAction(id,state,dispatch,e.target.value);else if(id==="QA-01-INP-CORR-ROOT")dispatch({type:"CORRECTION_ROOT",value:e.target.value});else if(id==="QA-01-INP-FINDING-SEVERITY")dispatch({type:"FINDING_SEVERITY",value:e.target.value});else if(id==="QA-01-INP-FINDING-CATEGORY")dispatch({type:"FINDING_CATEGORY",value:e.target.value});}}><option value="">—</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
 return<button type="button" disabled={!enabled} onClick={()=>act()} className={`${styles.button} ${kind==="primary"?styles.primary:""}`} {...common}>{label}</button>;
}