"use client";

import { useMemo, useReducer, type Dispatch } from "react";
import { useI18n } from "@/i18n/LocaleProvider";
import { QA_CONTROL_TEXT, qaText, qaUiText } from "@/i18n/qaCatalog";
import { INITIAL_QA_CLIENT_STATE, reduceQaClientState, type QaClientAction, type QaClientState } from "@/domain/qa/qaClientState";
import styles from "./QaVisual.module.css";

type Kind = "readonly" | "button" | "primary" | "search" | "select" | "list" | "viewer" | "range" | "segmented" | "table" | "input" | "textarea" | "multiselect";
type Spec = { id: string; kind: Kind };
const s = (id: string, kind: Kind): Spec => ({ id, kind });

const CONTEXT = [s("QA-01-FLD-PROJECT", "readonly"), s("QA-01-FLD-TOPIC", "readonly"), s("QA-01-FLD-QA-TASK", "readonly"), s("QA-01-FLD-TARGET-OUTPUT", "readonly"), s("QA-01-FLD-REVIEW-STATE", "readonly"), s("QA-01-BTN-START-REVIEW", "button")];
const QUEUE = [s("QA-01-INP-QUEUE-SEARCH", "search"), s("QA-01-SEL-QUEUE-STATE", "select"), s("QA-01-SEL-QUEUE-SEVERITY", "select"), s("QA-01-LIST-REVIEWS", "list"), s("QA-01-SEG-REVIEW-MODE", "segmented"), s("QA-01-BTN-AUTO-START", "primary"), s("QA-01-FLD-AUTO-PROGRESS", "readonly"), s("QA-01-SEL-QUEUE-SOURCE-DEPT", "select")];
const VIEWER = [s("QA-01-VIEW-OUTPUT", "viewer"), s("QA-01-BTN-PLAY", "button"), s("QA-01-CTL-SEEK", "range"), s("QA-01-BTN-VOLUME", "button"), s("QA-01-BTN-FULLSCREEN", "button"), s("QA-01-BTN-COMPARE", "button"), s("QA-01-BTN-PREV-FRAME", "button"), s("QA-01-BTN-NEXT-FRAME", "button"), s("QA-01-FLD-CURRENT-TIMECODE", "readonly"), s("QA-01-BTN-FINDING-POINT", "button"), s("QA-01-BTN-EVIDENCE-IN", "button"), s("QA-01-BTN-EVIDENCE-OUT", "button")];
const SCRIPT = [s("QA-01-FLD-QA-SCRIPT", "readonly"), s("QA-01-FLD-SCRIPT-HASH", "readonly"), s("QA-01-FLD-CRITERIA-VERSION", "readonly"), s("QA-01-FLD-GATE-POLICY", "readonly"), s("QA-01-BTN-SCRIPT-VIEW", "button")];
const EVIDENCE = [s("QA-01-FLD-EVIDENCE", "readonly"), s("QA-01-FLD-CHECKSUM", "readonly"), s("QA-01-FLD-PROVENANCE", "readonly"), s("QA-01-FLD-REQUIRED-CHECKS", "readonly"), s("QA-01-FLD-RIGHTS", "readonly"), s("QA-01-FLD-POLICY", "readonly"), s("QA-01-BTN-EVIDENCE", "button")];
const SCORE = [s("QA-01-FLD-TOTAL-SCORE", "readonly"), s("QA-01-FLD-HARD-BLOCK", "readonly"), s("QA-01-FLD-GATE-STATUS", "readonly"), s("QA-01-FLD-OPEN-FINDINGS", "readonly"), s("QA-01-FLD-MANUAL-STATE", "readonly"), s("QA-01-LIST-SCORE-DIMENSIONS", "table")];
const FINDING = [s("QA-01-LIST-FINDINGS", "list"), s("QA-01-INP-FINDING-SEVERITY", "select"), s("QA-01-INP-FINDING-CATEGORY", "select"), s("QA-01-INP-FINDING-SCOPE", "input"), s("QA-01-INP-FINDING-EVIDENCE", "readonly"), s("QA-01-BTN-FINDING-CREATE", "primary"), s("QA-01-FLD-MANUAL-CASE", "readonly"), s("QA-01-FLD-MANUAL-OWNER", "readonly"), s("QA-01-FLD-MANUAL-BLOCKER", "readonly"), s("QA-01-FLD-MANUAL-DECISION", "readonly"), s("QA-01-BTN-MANUAL-VIEW", "button"), s("QA-01-BTN-MANUAL-MODIFY", "button"), s("QA-01-BTN-MANUAL-PASS", "primary")];
const CORRECTION = [s("QA-01-INP-CORR-FINDINGS", "readonly"), s("QA-01-INP-CORR-SCORECARDS", "readonly"), s("QA-01-INP-CORR-INSTRUCTION", "readonly"), s("QA-01-INP-CORR-SCOPE", "input"), s("QA-01-INP-CORR-ROOT", "select"), s("QA-01-INP-CORR-ACTION", "textarea"), s("QA-01-INP-CORR-TARGET", "readonly"), s("QA-01-INP-CORR-REVALIDATE", "multiselect"), s("QA-01-BTN-CORRECTION", "primary"), s("QA-01-FLD-FAILED-VERSION", "readonly"), s("QA-01-FLD-NEW-VERSION", "readonly"), s("QA-01-FLD-RECHECK-STATUS", "readonly"), s("QA-01-BTN-RECHECK", "primary")];
const RELEASE = [s("QA-01-FLD-REL-QA-PASS", "readonly"), s("QA-01-FLD-REL-FINDINGS", "readonly"), s("QA-01-FLD-REL-MANUAL", "readonly"), s("QA-01-FLD-REL-RIGHTS", "readonly"), s("QA-01-FLD-REL-POLICY", "readonly"), s("QA-01-FLD-REL-CHANNEL", "readonly"), s("QA-01-FLD-REL-PACKAGE", "readonly"), s("QA-01-FLD-REL-OUTPUTS", "readonly"), s("QA-01-FLD-REL-QA-GATE", "readonly"), s("QA-01-FLD-REL-RIGHTS-GATE", "readonly"), s("QA-01-BTN-RELEASE-CREATE", "primary")];
const STATUS = [s("QA-01-FLD-PAGE-STATE", "readonly"), s("QA-01-FLD-ERROR", "readonly"), s("QA-01-FLD-DISABLED", "readonly"), s("QA-01-FLD-CORRELATION", "readonly"), s("QA-01-FLD-AUDIT", "readonly"), s("QA-01-BTN-AUDIT", "button")];
const ALL = [...CONTEXT, ...QUEUE, ...VIEWER, ...SCRIPT, ...EVIDENCE, ...SCORE, ...FINDING, ...CORRECTION, ...RELEASE, ...STATUS];

type ControlProps={spec:Spec;state:QaClientState;dispatch:Dispatch<QaClientAction>};
function Control({ spec, state, dispatch }: ControlProps) {
  const { locale } = useI18n();
  const label = qaText(locale, spec.id);
  const reviewBound=Boolean(state.review_ref);
  const localAlways=spec.id==="QA-01-SEG-REVIEW-MODE"||spec.id==="QA-01-INP-QUEUE-SEARCH";
  const localViewer=reviewBound&&["QA-01-BTN-PLAY","QA-01-CTL-SEEK","QA-01-BTN-VOLUME","QA-01-BTN-FULLSCREEN","QA-01-BTN-COMPARE","QA-01-BTN-FINDING-POINT","QA-01-BTN-EVIDENCE-IN","QA-01-BTN-EVIDENCE-OUT"].includes(spec.id);
  const manualView=spec.id==="QA-01-BTN-MANUAL-VIEW"&&Boolean(state.finding_ref);
  const enabled=localAlways||localViewer||manualView;
  const common = { "data-control-id": spec.id, "data-disabled-reason": enabled?undefined:"Gate not satisfied" };
  if (spec.kind === "readonly") {const value=spec.id==="QA-01-FLD-CURRENT-TIMECODE"?(state.current_timecode??"—"):spec.id==="QA-01-FLD-MANUAL-STATE"?(state.manual_review_open?"OPEN":"—"):"—";return <div className={styles.readonly} {...common}><span>{label}</span><strong>{String(value)}</strong></div>;}
  if (spec.kind === "list") return <div className={styles.listControl} {...common}><span>{label}</span><div className={styles.emptyList}>—</div></div>;
  if (spec.kind === "viewer") return <div className={styles.viewerControl} {...common}><span>{label}</span><div className={styles.viewerCanvas}>—</div></div>;
  if (spec.kind === "table") return <div className={styles.tableControl} {...common}><span>{label}</span><div className={styles.scoreTable}>—</div></div>;
  if (spec.kind === "segmented") return <div className={styles.segmented} {...common}><span>{label}</span><div><button type="button" className={state.mode==="AUTO"?styles.selectedSegment:""} aria-pressed={state.mode==="AUTO"} onClick={()=>dispatch({type:"MODE",value:"AUTO"})}>AUTO</button><button type="button" className={state.mode==="MANUAL"?styles.selectedSegment:""} aria-pressed={state.mode==="MANUAL"} onClick={()=>dispatch({type:"MODE",value:"MANUAL"})}>MANUAL</button></div></div>;
  if (spec.kind === "search") return <label className={styles.fieldControl}><span>{label}</span><input {...common} value={state.queue_search} onChange={e=>dispatch({type:"QUEUE_SEARCH",value:e.target.value})} placeholder="—" /></label>;
  if (spec.kind === "input") return <label className={styles.fieldControl}><span>{label}</span><input {...common} disabled placeholder="—" /></label>;
  if (spec.kind === "textarea") return <label className={styles.fieldControl}><span>{label}</span><textarea {...common} disabled placeholder="—" /></label>;
  if (spec.kind === "select" || spec.kind === "multiselect") return <label className={styles.fieldControl}><span>{label}</span><select {...common} disabled multiple={spec.kind === "multiselect"} defaultValue={spec.kind === "multiselect" ? [] : ""}><option value="">—</option></select></label>;
  if (spec.kind === "range") {const n=typeof state.seek==="number"?state.seek:0;return <label className={styles.rangeControl}><span>{label}</span><input {...common} disabled={!enabled} type="range" min="0" max="100" value={n} onChange={e=>dispatch({type:"SEEK",value:Number(e.target.value)})} /></label>;}
  const onClick=spec.id==="QA-01-BTN-PLAY"?()=>dispatch({type:"PLAY"}):spec.id==="QA-01-BTN-VOLUME"?()=>dispatch({type:"MUTE"}):spec.id==="QA-01-BTN-FULLSCREEN"?()=>dispatch({type:"FULLSCREEN",value:!state.fullscreen}):spec.id==="QA-01-BTN-COMPARE"?()=>dispatch({type:"COMPARE"}):spec.id==="QA-01-BTN-FINDING-POINT"?()=>dispatch({type:"EVIDENCE_POINT",value:state.current_timecode}):spec.id==="QA-01-BTN-EVIDENCE-IN"?()=>dispatch({type:"EVIDENCE_IN",value:state.current_timecode}):spec.id==="QA-01-BTN-EVIDENCE-OUT"?()=>dispatch({type:"EVIDENCE_OUT",value:state.current_timecode}):spec.id==="QA-01-BTN-MANUAL-VIEW"?()=>dispatch({type:"MANUAL_VIEW",value:!state.manual_review_open}):undefined;
  return <button type="button" disabled={!enabled} onClick={onClick} className={`${styles.button} ${spec.kind === "primary" ? styles.primary : ""}`} {...common}>{label}</button>;
}
function Title({ text, meta }: { text: string; meta?: string }) { return <div className={styles.titleRow}><h2>{text}</h2>{meta ? <span>{meta}</span> : null}</div>; }

export function QaVisual() {
  const { locale } = useI18n();
  const [state,dispatch]=useReducer(reduceQaClientState,INITIAL_QA_CLIENT_STATE);
  const registryValid = useMemo(() => {const ids = new Set(ALL.map((item) => item.id));return ids.size === 87 && Object.keys(QA_CONTROL_TEXT).length === 87 && [...ids].every((id) => id in QA_CONTROL_TEXT);}, []);
  const byId = (id: string) => ALL.find((item) => item.id === id)!;
  const C=({spec}:{spec:Spec})=><Control spec={spec} state={state} dispatch={dispatch}/>;
  return <div className={styles.page} data-page-uid="QA-01" data-vis-step="VIS-06" data-page-state="EMPTY" data-authority-controls="87" data-registry-valid={registryValid ? "true" : "false"} data-review-mode={state.mode} data-review-bound={state.review_ref?"true":"false"}>
    <section className={styles.contextBar} data-section-id="QA-01-SEC-01" data-visual-uid="QA-01-VIS-CONTEXT" data-component-uid="QA-01-CMP-CONTEXT"><div className={styles.contextGrid}>{CONTEXT.slice(0, 5).map((spec) => <C key={spec.id} spec={spec} />)}</div><div className={styles.registryOnly}><C spec={CONTEXT[5]} /></div></section>
    <div className={styles.primaryGrid}>
      <aside className={`${styles.panel} ${styles.queuePanel}`} data-section-id="QA-01-SEC-02" data-visual-uid="QA-01-VIS-LEFT" data-component-uid="QA-01-CMP-QUEUE"><Title text={qaUiText(locale, "queue")} meta="20% / min 260px" /><div data-component-uid="QA-01-CMP-REVIEW-MODE" className={styles.stack}><C spec={byId("QA-01-SEG-REVIEW-MODE")} /><C spec={byId("QA-01-BTN-AUTO-START")} /></div><div data-component-uid="QA-01-CMP-AUTO-PROGRESS" className={styles.progressBlock}><C spec={byId("QA-01-FLD-AUTO-PROGRESS")} /></div><div className={styles.filterGrid}><C spec={byId("QA-01-INP-QUEUE-SEARCH")} /><C spec={byId("QA-01-SEL-QUEUE-STATE")} /><C spec={byId("QA-01-SEL-QUEUE-SEVERITY")} /><C spec={byId("QA-01-SEL-QUEUE-SOURCE-DEPT")} /></div><C spec={byId("QA-01-LIST-REVIEWS")} /><div className={styles.emptyNote}>{qaUiText(locale, "noReview")}</div></aside>
      <main className={styles.centerStack}><section className={`${styles.panel} ${styles.viewerPanel}`} data-section-id="QA-01-SEC-03" data-visual-uid="QA-01-VIS-VIEWER" data-component-uid="QA-01-CMP-VIEWER"><Title text={qaUiText(locale, "viewer")} meta="60% / highest priority" /><C spec={byId("QA-01-VIEW-OUTPUT")} /><div className={styles.transportRow}><C spec={byId("QA-01-BTN-PLAY")} /><C spec={byId("QA-01-CTL-SEEK")} /><C spec={byId("QA-01-BTN-VOLUME")} /><C spec={byId("QA-01-BTN-FULLSCREEN")} /></div><div data-component-uid="QA-01-CMP-EVIDENCE-CAPTURE" className={styles.captureRow}><C spec={byId("QA-01-FLD-CURRENT-TIMECODE")} /><C spec={byId("QA-01-BTN-FINDING-POINT")} /><C spec={byId("QA-01-BTN-EVIDENCE-IN")} /><C spec={byId("QA-01-BTN-EVIDENCE-OUT")} /></div><div className={styles.registryOnly}><div data-component-uid="QA-01-CMP-COMPARE"><C spec={byId("QA-01-BTN-COMPARE")} /></div><C spec={byId("QA-01-BTN-PREV-FRAME")} /><C spec={byId("QA-01-BTN-NEXT-FRAME")} /></div></section><section className={styles.panel} data-section-id="QA-01-SEC-04" data-visual-uid="QA-01-VIS-SCRIPT"><Title text={qaUiText(locale, "scriptCriteria")} /><div className={styles.dualGrid}><div data-component-uid="QA-01-CMP-SCRIPT" className={styles.stack}><C spec={byId("QA-01-FLD-QA-SCRIPT")} /><C spec={byId("QA-01-FLD-SCRIPT-HASH")} /><C spec={byId("QA-01-BTN-SCRIPT-VIEW")} /></div><div data-component-uid="QA-01-CMP-CRITERIA" className={styles.stack}><C spec={byId("QA-01-FLD-CRITERIA-VERSION")} /><C spec={byId("QA-01-FLD-GATE-POLICY")} /></div></div></section><section className={styles.panel} data-section-id="QA-01-SEC-05" data-visual-uid="QA-01-VIS-EVIDENCE" data-component-uid="QA-01-CMP-EVIDENCE"><Title text={qaUiText(locale, "evidence")} /><div className={styles.evidenceGrid}>{EVIDENCE.map((spec) => <C key={spec.id} spec={spec} />)}</div></section></main>
      <aside className={`${styles.panel} ${styles.scorePanel}`} data-section-id="QA-01-SEC-06" data-visual-uid="QA-01-VIS-RIGHT"><Title text={qaUiText(locale, "scoreGate")} meta="20% / min 300px" /><div data-component-uid="QA-01-CMP-SCORE" className={styles.stack}><C spec={byId("QA-01-LIST-SCORE-DIMENSIONS")} /><C spec={byId("QA-01-FLD-TOTAL-SCORE")} /><C spec={byId("QA-01-FLD-HARD-BLOCK")} /></div><div className={styles.divider} /><div data-component-uid="QA-01-CMP-GATE" className={styles.stack}><C spec={byId("QA-01-FLD-GATE-STATUS")} /><C spec={byId("QA-01-FLD-OPEN-FINDINGS")} /><C spec={byId("QA-01-FLD-MANUAL-STATE")} /></div><div className={styles.policyNote}>{qaUiText(locale, "scoreReadonly")}</div></aside>
    </div>
    <section className={styles.lowerPanel} data-section-id="QA-01-SEC-07" data-visual-uid="QA-01-VIS-FINDING"><div className={styles.findingGrid}><div className={styles.card} data-component-uid="QA-01-CMP-FINDING-LIST"><Title text={qaUiText(locale, "finding")} /><C spec={byId("QA-01-LIST-FINDINGS")} /></div><div className={styles.card} data-component-uid="QA-01-CMP-FINDING-FORM"><Title text={qaUiText(locale, "findingDetail")} /><div className={styles.findingForm}>{FINDING.slice(1, 6).map((spec) => <C key={spec.id} spec={spec} />)}</div></div></div><div className={styles.registryOnly} data-component-uid="QA-01-CMP-MANUAL"><Title text={qaUiText(locale, "manual")} />{FINDING.slice(6, 11).map((spec) => <C key={spec.id} spec={spec} />)}<div data-component-uid="QA-01-CMP-MANUAL-DECISION">{FINDING.slice(11).map((spec) => <C key={spec.id} spec={spec} />)}</div></div></section>
    <section className={styles.lowerPanel} data-section-id="QA-01-SEC-08" data-visual-uid="QA-01-VIS-RECHECK"><div className={styles.dualGrid}><div className={styles.card} data-component-uid="QA-01-CMP-CORRECTION"><Title text={qaUiText(locale, "correction")} /><div className={styles.correctionGrid}>{CORRECTION.slice(0, 9).map((spec) => <C key={spec.id} spec={spec} />)}</div></div><div className={styles.card} data-component-uid="QA-01-CMP-RECHECK"><Title text={qaUiText(locale, "recheck")} /><div className={styles.stack}>{CORRECTION.slice(9).map((spec) => <C key={spec.id} spec={spec} />)}</div></div></div></section>
    <section className={styles.lowerPanel} data-section-id="QA-01-SEC-09" data-visual-uid="QA-01-VIS-RELEASE"><div className={styles.dualGrid}><div className={styles.card} data-component-uid="QA-01-CMP-RELEASE-READY"><Title text={qaUiText(locale, "releaseReady")} /><div className={styles.releaseGrid}>{RELEASE.slice(0, 6).map((spec) => <C key={spec.id} spec={spec} />)}</div></div><div className={styles.card} data-component-uid="QA-01-CMP-RELEASE"><Title text={qaUiText(locale, "release")} /><div className={styles.releaseGrid}>{RELEASE.slice(6).map((spec) => <C key={spec.id} spec={spec} />)}</div></div></div></section>
    <section className={styles.lowerPanel} data-section-id="QA-01-SEC-10" data-visual-uid="QA-01-VIS-STATUS" data-component-uid="QA-01-CMP-STATUS"><Title text={qaUiText(locale, "audit")} /><div className={styles.statusGrid}>{STATUS.map((spec) => <C key={spec.id} spec={spec} />)}</div></section>
  </div>;
}
