"use client";
import{createContext,useContext,useEffect,useMemo,useState,type KeyboardEvent,type ReactNode}from"react";
import{readSocProjection,type SocNormalizedProjection}from"@/domain/social/socProjectionPort";
import{invokeSocCommand,isSocCommandAdapterBound}from"@/domain/social/socCommandPort";
import{SOC_CONTROL_BINDINGS,type SocControlBinding,type SocControlUid}from"@/domain/social/socControlBindings";
import{ensureControlledSocClientTestRuntime}from"@/domain/social/controlledSocClientTestRuntime";
type Runtime={projection:SocNormalizedProjection|null;setProjection:(v:SocNormalizedProjection)=>void;runtimeError:string|null;setRuntimeError:(v:string|null)=>void;correlationId:string|null;setCorrelationId:(v:string|null)=>void};const Ctx=createContext<Runtime|null>(null);
export function SocRuntimeProvider({children}:{children:ReactNode}){ensureControlledSocClientTestRuntime();const[projection,setProjection]=useState<SocNormalizedProjection|null>(null),[runtimeError,setRuntimeError]=useState<string|null>(null),[correlationId,setCorrelationId]=useState<string|null>(null);useEffect(()=>{const c=new AbortController();void readSocProjection(c.signal).then(r=>{setCorrelationId(r.correlation_id);if(r.ok){setProjection(r.projection);setRuntimeError(null)}else setRuntimeError(`${r.error_uid}: ${r.reason_code}`)});return()=>c.abort()},[]);const value=useMemo(()=>({projection,setProjection,runtimeError,setRuntimeError,correlationId,setCorrelationId}),[projection,runtimeError,correlationId]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useSocRuntimeState(){const v=useContext(Ctx);if(!v)throw new Error("SOC_RUNTIME_PROVIDER_REQUIRED");return v;}
export function useSocGate(gateUid:string){return useSocRuntimeState().projection?.gate_state[gateUid]===true;}
export function SocValue({controlId}:{controlId:string}){const{projection}=useSocRuntimeState();return <>{projection?.values[controlId]??"—"}</>}
function apply(r:Runtime,binding:SocControlBinding,controlId:string){void invokeSocCommand({action_uid:binding.action_uid,control_uid:controlId,projection:r.projection}).then(x=>{r.setCorrelationId(x.correlation_id);if(x.ok){r.setProjection(x.projection);r.setRuntimeError(null)}else r.setRuntimeError(`${x.error_uid}: ${x.reason_code}`)})}
export function SocSearchInput({controlId,className,placeholder}:{controlId:string;className?:string;placeholder?:string}){const r=useSocRuntimeState(),binding:SocControlBinding|undefined=SOC_CONTROL_BINDINGS[controlId as SocControlUid],allowed=Boolean(binding)&&r.projection?.gate_state[binding!.gate_uid]===true,enabled=allowed&&isSocCommandAdapterBound();const onKeyDown=(e:KeyboardEvent<HTMLInputElement>)=>{if(e.key==="Enter"&&binding&&enabled){e.preventDefault();apply(r,binding,controlId)}};return <input className={className} data-control-id={controlId} data-action-uid={binding?.action_uid} data-gate-uid={binding?.gate_uid} placeholder={placeholder} disabled={!enabled} onKeyDown={onKeyDown}/>}
export function SocGovernedButton({controlId,className,children,onUiClick}:{controlId:string;className?:string;children:ReactNode;onUiClick?:()=>void}){const r=useSocRuntimeState(),binding:SocControlBinding|undefined=SOC_CONTROL_BINDINGS[controlId as SocControlUid],allowed=Boolean(binding)&&r.projection?.gate_state[binding!.gate_uid]===true,local=binding?.effect_type==="UI_CONTEXT_STATE"||binding?.effect_type==="UI_ONLY",enabled=allowed&&(local||isSocCommandAdapterBound());const click=()=>{if(!binding||!enabled)return;if(local){onUiClick?.();return}apply(r,binding,controlId)};return <button type="button" className={className} data-control-id={controlId} data-action-uid={binding?.action_uid} data-gate-uid={binding?.gate_uid} data-permission-uid={binding?.permission_uid} data-disabled-reason={!allowed?binding?.gate_uid:!local&&!isSocCommandAdapterBound()?"SOC_COMMAND_RUNTIME_NOT_BOUND":undefined} disabled={!enabled} onClick={click}>{children}</button>}
