"use client";
import{createContext,useContext,useEffect,useMemo,useState,type ReactNode}from"react";
import{isStrategyAdminCommandAdapterBound,invokeStrategyAdminAction,readStrategyAdminProjection,type StrategyAdminMappedAction,type StrategyAdminProjection,type StrategyAdminView}from"@/domain/strategyAdmin/strategyAdminRuntimePort";

type Runtime={projection:StrategyAdminProjection|null;runtimeError:string|null;invoke:(actionId:string,view:StrategyAdminView)=>Promise<void>;canInvoke:(actionId:string)=>boolean};
const Ctx=createContext<Runtime|null>(null);
export function StrategyAdminRuntimeProvider({children}:{children:ReactNode}){const[projection,setProjection]=useState<StrategyAdminProjection|null>(null),[runtimeError,setRuntimeError]=useState<string|null>(null);useEffect(()=>{const c=new AbortController();void readStrategyAdminProjection(c.signal).then(r=>{if(r.ok){setProjection(r.projection);setRuntimeError(null)}else setRuntimeError(r.reason_code)});return()=>c.abort()},[]);const canInvoke=(actionId:string)=>Boolean(projection?.action_enabled[actionId])&&actionId!=='ACT-CANDIDATE-DECIDE'&&actionId!=='ACT-NAV-OPEN'&&actionId in ACTIONS&&isStrategyAdminCommandAdapterBound();const invoke=async(actionId:string,view:StrategyAdminView)=>{if(!projection){setRuntimeError('STR_ADMIN_PROJECTION_NOT_READY');return}if(actionId==='ACT-CANDIDATE-DECIDE'){setRuntimeError('STR_ADMIN_AUTHORITY_BINDING_UNRESOLVED: ACT-CANDIDATE-DECIDE');return}if(!(actionId in ACTIONS)){setRuntimeError('STR_ADMIN_ACTION_OPERATION_NOT_REGISTERED');return}const r=await invokeStrategyAdminAction(actionId as StrategyAdminMappedAction,view,projection);setRuntimeError(r.ok?null:r.reason_code)};const value=useMemo(()=>({projection,runtimeError,invoke,canInvoke}),[projection,runtimeError]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
const ACTIONS:Readonly<Record<StrategyAdminMappedAction,true>>={'ACT-REFRESH':true,'ACT-SEARCH':true,'ACT-CONFIGURE':true,'ACT-APPROVE':true,'ACT-EXPORT':true,'ACT-DRAFT-SAVE':true,'ACT-CANDIDATE-CREATE':true,'ACT-CANDIDATE-COMPARE':true,'ACT-ADOPT-CONTEXT':true};
export function useStrategyAdminRuntime(){const v=useContext(Ctx);if(!v)throw new Error('STRATEGY_ADMIN_RUNTIME_PROVIDER_REQUIRED');return v;}
