"use client";
import{createContext,useContext,useEffect,useMemo,useReducer,useRef,type Dispatch,type ReactNode}from'react';
import{useI18n}from'@/i18n/LocaleProvider';
import{strategyText}from'@/i18n/strategyCatalog';
import{STRATEGY_CONTROL_BINDINGS,type StrategyControlUid}from'@/domain/strategy/strategyControlBindings';
import{INITIAL_STRATEGY_CLIENT_STATE,reduceStrategyClientState,type StrategyClientAction,type StrategyClientState,type StrategyMode}from'@/domain/strategy/strategyClientState';
import{readStrategyProjection}from'@/domain/strategy/strategyProjectionPort';
import{buildAndInvokeStrategyAction,isStrategyRequestBuilderBound,type StrategyFormalAction}from'@/domain/strategy/strategyCommandPort';
import{isStrategyOwnerNavigationResolverBound,resolveStrategyOwnerNavigation}from'@/domain/strategy/strategyOwnerNavigationPort';
import styles from'./StrategyVisual.module.css';
export type StrategyControlKind='readonly'|'button'|'primary'|'search'|'list'|'conversation'|'attachment'|'textarea'|'table'|'card'|'toggle';
type Runtime={state:StrategyClientState;dispatch:Dispatch<StrategyClientAction>};const Ctx=createContext<Runtime|null>(null);
export function StrategyRuntimeProvider({children}:{children:ReactNode}){const[state,dispatch]=useReducer(reduceStrategyClientState,INITIAL_STRATEGY_CLIENT_STATE);useEffect(()=>{const c=new AbortController();void readStrategyProjection(c.signal).then(r=>r.ok?dispatch({type:'PROJECTION',value:r.projection,correlation_id:r.correlation_id}):dispatch({type:'RUNTIME_ERROR',value:`${r.error_uid}: ${r.reason_code}`,correlation_id:r.correlation_id}));return()=>c.abort();},[]);const value=useMemo(()=>({state,dispatch}),[state]);return <Ctx.Provider value={value}>{children}<StrategyAuditDrawer/></Ctx.Provider>}
export function useStrategyRuntimeState(){const value=useContext(Ctx);if(!value)throw new Error('STRATEGY_RUNTIME_PROVIDER_REQUIRED');return value;}
function gate(state:StrategyClientState,uid:string){return state.projection?.gate_state[uid]===true;}
function actionCondition(state:StrategyClientState,actionUid:string|undefined){if(actionUid==='STR-01-ACT-SEND')return state.message.trim().length>0;if(actionUid==='STR-01-ACT-STOP')return state.projection?.page_state==='RESPONDING'&&state.message.trim().length>0;return true;}
function inputContextReady(state:StrategyClientState){return state.projection?.gate_state['STR-01-GATE-TOPIC']===true&&state.projection?.gate_state['STR-01-GATE-CONTEXT']===true;}
function valueOf(id:string,state:StrategyClientState){const p=state.projection;if(id==='STR-01-FLD-TOPIC')return state.topic_ref??p?.values[id]??'—';if(id==='STR-01-FLD-CORRELATION')return state.correlation_id??'—';if(id==='STR-01-FLD-DISABLED')return state.runtime_error??'—';return p?.values[id]??'—';}
function StrategyAuditDrawer(){const{state,dispatch}=useStrategyRuntimeState(),{locale}=useI18n(),drawerRef=useRef<HTMLElement>(null);useEffect(()=>{if(!state.audit_open)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null,node=drawerRef.current;node?.focus();const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();dispatch({type:'AUDIT',value:false});return;}if(event.key==='Tab'){event.preventDefault();node?.focus();}};document.addEventListener('keydown',onKeyDown);return()=>{document.removeEventListener('keydown',onKeyDown);previous?.focus();};},[state.audit_open,dispatch]);if(!state.audit_open)return null;const fields=['STR-01-FLD-PROVIDER-BRAND','STR-01-FLD-CORRELATION','STR-01-FLD-DISABLED','STR-01-FLD-OWNER-BOUNDARY']as const;return <div className={styles.drawerLayer} data-strategy-audit-layer="true"><aside ref={drawerRef} tabIndex={-1} role="dialog" aria-modal="true" aria-label={strategyText(locale,'STR-01-BTN-AUDIT')} className={styles.auditDrawer} data-audit-trace-drawer="true"><div className={styles.auditDrawerTitle}>{strategyText(locale,'STR-01-BTN-AUDIT')}</div><div className={styles.auditDrawerGrid}>{fields.map(id=><div key={id} className={styles.auditDrawerRow}><span>{strategyText(locale,id)}</span><strong>{valueOf(id,state)}</strong></div>)}</div></aside></div>}
const FORMAL=new Set<StrategyFormalAction>(['STR-01-ACT-SEND','STR-01-ACT-STOP','STR-01-ACT-COMPARE','STR-01-ACT-REVIEW','STR-01-ACT-ADOPT']);
async function refreshProjection(dispatch:Dispatch<StrategyClientAction>){const p=await readStrategyProjection();if(p.ok){dispatch({type:'PROJECTION',value:p.projection,correlation_id:p.correlation_id});return true;}dispatch({type:'RUNTIME_ERROR',value:`${p.error_uid}: ${p.reason_code}`,correlation_id:p.correlation_id});return false;}
async function formal(action:StrategyFormalAction,state:StrategyClientState,dispatch:Dispatch<StrategyClientAction>){const r=await buildAndInvokeStrategyAction({action_uid:action,conversation_id:state.projection?.conversation_id??null,topic_ref:state.topic_ref,message:state.message,attachment_refs:state.attachment_refs,mode:state.mode,compare_candidate_refs:state.compare_candidate_refs,candidate_ref:state.projection?.candidate_ref??null,candidate_version_ref:state.projection?.candidate_version_ref??null});if(!r.ok){dispatch({type:'RUNTIME_ERROR',value:`${r.error_uid}: ${r.reason_code}`,correlation_id:r.correlation_id});return;}dispatch({type:'RUNTIME_ERROR',value:null,correlation_id:r.correlation_id});await refreshProjection(dispatch);if(action==='STR-01-ACT-STOP')dispatch({type:'MESSAGE',value:''});}
export function StrategyRuntimeControl({id,kind}:{id:string;kind:StrategyControlKind}){const{state,dispatch}=useStrategyRuntimeState(),{locale}=useI18n(),binding=STRATEGY_CONTROL_BINDINGS[id as StrategyControlUid],label=strategyText(locale,id),formalAction=FORMAL.has(binding?.action_uid as StrategyFormalAction),allowed=Boolean(binding)&&gate(state,binding.gate_uid)&&actionCondition(state,binding?.action_uid),formalReady=!formalAction||isStrategyRequestBuilderBound(),ownerReady=binding?.action_uid!=='STR-01-ACT-OPEN-OWNER'||isStrategyOwnerNavigationResolverBound(),enabled=allowed&&formalReady&&ownerReady,common={"data-control-id":id,"data-action-uid":binding?.action_uid,"data-gate-uid":binding?.gate_uid,"data-permission-uid":binding?.permission_uid,"data-effect-type":binding?.effect_type,"data-disabled-reason":!allowed?binding?.gate_uid:!formalReady?'STRATEGY_REQUEST_ADAPTER_NOT_BOUND':!ownerReady?'STRATEGY_OWNER_ROUTE_NOT_BOUND':undefined};
const click=()=>{if(binding?.action_uid==='STR-01-ACT-MODE')return;if(binding?.action_uid==='STR-01-ACT-AUDIT'){dispatch({type:'AUDIT',value:!state.audit_open});return;}if(binding?.action_uid==='STR-01-ACT-OPEN-OWNER'){const owner=state.projection?.owner_type,ref=state.projection?.owner_context_ref??null;if(!owner){dispatch({type:'RUNTIME_ERROR',value:'STR-01-ERR-CONTEXT-001: EXECUTION_OWNER_REF_MISSING'});return;}void resolveStrategyOwnerNavigation({owner_type:owner,context_ref:ref}).then(r=>{if(!r.ok){dispatch({type:'RUNTIME_ERROR',value:`STR-01-ERR-CONTEXT-001: ${r.reason_code}`});return;}window.location.assign(r.href);});return;}if(formalAction)void formal(binding.action_uid as StrategyFormalAction,state,dispatch);};
if(kind==='readonly')return <div className={styles.readonly}{...common}><span>{label}</span><strong>{valueOf(id,state)}</strong></div>;
if(kind==='list'){const raw=state.projection?.lists[id]??[],query=state.topic_search.trim().toLowerCase(),items=id==='STR-01-LST-TOPICS'&&query?raw.filter(x=>x.ref.toLowerCase().includes(query)||x.label.toLowerCase().includes(query)):raw;return <div className={styles.listControl}{...common}><span>{label}</span><div className={styles.listView}>{items.length?items.map(x=><button key={x.ref} type="button" disabled={binding?.action_uid==='STR-01-ACT-TOPIC-SELECT'?!gate(state,'STR-01-GATE-PAGE'):true} onClick={()=>binding?.action_uid==='STR-01-ACT-TOPIC-SELECT'&&dispatch({type:'TOPIC',value:x.ref})}>{x.label}</button>):'—'}</div></div>}
if(kind==='conversation')return <div className={styles.conversationControl}{...common}><span>{label}</span><div className={styles.conversationView}>{state.projection?.blocks[id]??'—'}</div></div>;
if(kind==='table')return <div className={styles.tableControl}{...common}><span>{label}</span><div className={styles.tableView}>{state.projection?.blocks[id]??'—'}</div></div>;
if(kind==='card')return <div className={styles.outputCard}{...common}><span>{label}</span><div>{state.projection?.blocks[id]??'—'}</div></div>;
if(kind==='toggle')return <div className={styles.segmented}{...common}><span>{label}</span><div>{(['SINGLE_AI','MULTI_AI']as StrategyMode[]).map(mode=><button key={mode} type="button" disabled={!gate(state,'STR-01-GATE-TOPIC')||(mode==='MULTI_AI'&&!gate(state,'STR-01-GATE-MULTI'))} onClick={()=>dispatch({type:'MODE',value:mode})} aria-pressed={state.mode===mode}>{mode==='SINGLE_AI'?'Single AI':'Multi AI'}</button>)}</div></div>;
if(kind==='search')return <label className={styles.fieldControl}><span>{label}</span><input {...common} disabled={!gate(state,'STR-01-GATE-PAGE')} value={state.topic_search} onChange={e=>dispatch({type:'SEARCH',value:e.target.value})} placeholder="—"/></label>;
if(kind==='textarea')return <label className={styles.textareaControl}><span>{label}</span><textarea {...common} disabled={!inputContextReady(state)} value={state.message} onChange={e=>dispatch({type:'MESSAGE',value:e.target.value})} placeholder="—"/></label>;
if(kind==='attachment')return <button type="button" disabled data-disabled-reason="STRATEGY_ATTACHMENT_FLOW_NOT_BOUND" title="Attachment refs must be supplied by registered conversation attachment flow" className={styles.button}{...common}>{label}</button>;
return <button type="button" disabled={!enabled} onClick={click} className={`${styles.button} ${kind==='primary'?styles.primary:''}`} {...common}>{label}</button>}
