
-- ACPOS Deployment Runtime Operational Schema (server-side job/session/UI operational persistence)
CREATE SCHEMA IF NOT EXISTS acpos_runtime;
CREATE TABLE IF NOT EXISTS acpos_runtime.entities(kind text NOT NULL, id text NOT NULL, parent_id text NULL, status text NULL, version integer NOT NULL DEFAULT 1, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(kind,id));
CREATE TABLE IF NOT EXISTS acpos_runtime.audit(id text PRIMARY KEY, operation_id text NOT NULL, account_id text NULL, correlation_id text NULL, idempotency_key text NULL, request_hash text NULL, outcome text NOT NULL, payload jsonb NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.idempotency(idempotency_key text PRIMARY KEY, operation_id text NOT NULL, response_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.events(id text PRIMARY KEY, event_type text NOT NULL, resource_ref text NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.project_conversation_workspaces(id text PRIMARY KEY, project_id text NOT NULL UNIQUE, shared_context_snapshot_id text NULL, view_state jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.conversations(id text PRIMARY KEY, workspace_id text NOT NULL REFERENCES acpos_runtime.project_conversation_workspaces(id), project_id text NOT NULL, topic_id text NULL, task_id text NULL, candidate_version_id text NULL, blueprint_version_id text NULL, asset_version_id text NULL, shot_id text NULL, title text NOT NULL, parent_thread_id text NULL REFERENCES acpos_runtime.conversations(id), branch_source_message_id text NULL, context_snapshot_id text NULL, view_state jsonb NOT NULL DEFAULT '{}'::jsonb, draft_text text NOT NULL DEFAULT '', draft_attachments jsonb NOT NULL DEFAULT '[]'::jsonb, draft_cursor_position integer NULL, status text NOT NULL, last_read_message_id text NULL, scroll_anchor_message_id text NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.conversation_messages(id text PRIMARY KEY, conversation_id text NOT NULL REFERENCES acpos_runtime.conversations(id), sender_type text NOT NULL, content text NOT NULL, provider_id text NULL, model_id text NULL, job_id text NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.thread_syncs(id text PRIMARY KEY, source_thread_id text NOT NULL REFERENCES acpos_runtime.conversations(id), target_thread_id text NOT NULL REFERENCES acpos_runtime.conversations(id), direction text NOT NULL, sync_types jsonb NOT NULL, selected_message_ids jsonb NOT NULL DEFAULT '[]'::jsonb, sync_payload jsonb NOT NULL DEFAULT '{}'::jsonb, provenance_json jsonb NOT NULL DEFAULT '{}'::jsonb, applied_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.thread_context_items(id text PRIMARY KEY, thread_id text NOT NULL REFERENCES acpos_runtime.conversations(id), item_type text NOT NULL, source_thread_id text NOT NULL REFERENCES acpos_runtime.conversations(id), source_ref text NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.conversation_generation_jobs(id text PRIMARY KEY, conversation_id text NOT NULL REFERENCES acpos_runtime.conversations(id), user_message_id text NOT NULL REFERENCES acpos_runtime.conversation_messages(id), candidate_group_id text NULL, provider_mode text NOT NULL, requested_provider_id text NULL, requested_model_id text NULL, status text NOT NULL, cancel_requested boolean NOT NULL DEFAULT false, provider_id text NULL, model_id text NULL, result_message_id text NULL REFERENCES acpos_runtime.conversation_messages(id), failure_code text NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.meetings(id text PRIMARY KEY, project_id text NOT NULL, topic_id text NULL, title text NOT NULL, objective text NOT NULL, agenda jsonb NOT NULL, context_snapshot_id text NULL, context_snapshot_hash char(64) NULL, current_round integer NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.meeting_participants(id text PRIMARY KEY, meeting_id text NOT NULL REFERENCES acpos_runtime.meetings(id), perspective text NOT NULL, route_mode text NOT NULL, candidate_group_id text NULL, requested_provider_id text NULL, requested_model_id text NULL, actual_provider_id text NULL, actual_model_id text NULL, allow_substitution boolean NOT NULL DEFAULT false, participant_status text NOT NULL, preflight_status text NULL, failure_reason text NULL, substitution_reason text NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.meeting_rounds(id text PRIMARY KEY, meeting_id text NOT NULL REFERENCES acpos_runtime.meetings(id), round_no integer NOT NULL, round_mode text NOT NULL, context_snapshot_id text NULL, prompt text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.meeting_messages(id text PRIMARY KEY, meeting_id text NOT NULL REFERENCES acpos_runtime.meetings(id), round_id text NULL REFERENCES acpos_runtime.meeting_rounds(id), participant_id text NULL REFERENCES acpos_runtime.meeting_participants(id), sender_type text NOT NULL, content text NOT NULL, provider_id text NULL, model_id text NULL, evidence_json jsonb NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.execution_jobs(id text PRIMARY KEY, title text NOT NULL, job_type text NOT NULL, project_id text NULL, topic_id text NULL, status text NOT NULL, current_step integer NOT NULL DEFAULT 0, total_steps integer NOT NULL DEFAULT 0, cancel_requested boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.execution_steps(id text PRIMARY KEY, job_id text NOT NULL REFERENCES acpos_runtime.execution_jobs(id), step_no integer NOT NULL, name text NOT NULL, status text NOT NULL, result_json jsonb NULL, started_at timestamptz NULL, completed_at timestamptz NULL);
CREATE TABLE IF NOT EXISTS acpos_runtime.execution_logs(id text PRIMARY KEY, job_id text NOT NULL REFERENCES acpos_runtime.execution_jobs(id), page_no integer NOT NULL, content text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(job_id,page_no));
CREATE TABLE IF NOT EXISTS acpos_runtime.todos(id text PRIMARY KEY, project_id text NOT NULL, topic_id text NULL, task_id text NULL, title text NOT NULL, description text NULL, priority text NULL, due_at timestamptz NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.provider_groups(id text PRIMARY KEY, name text NOT NULL, use_case text NOT NULL, data_classification text NULL, quality_tiers jsonb NULL, enabled boolean NOT NULL DEFAULT true, limits_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.provider_members(id text PRIMARY KEY, group_id text NOT NULL REFERENCES acpos_runtime.provider_groups(id), provider_id text NOT NULL, model_id text NOT NULL, capability_id text NULL, priority integer NOT NULL, enabled boolean NOT NULL DEFAULT true, health_status text NOT NULL DEFAULT 'UNKNOWN', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.provider_profiles(id text PRIMARY KEY, provider_id text NOT NULL, model_id text NOT NULL, capability_type text NOT NULL, adapter_type text NOT NULL, base_url text NOT NULL, endpoint_path text NOT NULL, http_method text NOT NULL, secret_env_ref text NOT NULL, preferred_language text NULL, max_context integer NULL, timeout_seconds integer NOT NULL, request_template jsonb NOT NULL, response_text_path text NOT NULL, enabled boolean NOT NULL DEFAULT true, health_status text NOT NULL DEFAULT 'UNKNOWN', version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider_id,model_id));
CREATE TABLE IF NOT EXISTS acpos_runtime.provider_quarantine(id text PRIMARY KEY, member_id text NOT NULL REFERENCES acpos_runtime.provider_members(id), reason text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), restored_at timestamptz NULL);
CREATE TABLE IF NOT EXISTS acpos_runtime.layer_documents(id text PRIMARY KEY, project_id text NULL, topic_id text NULL, asset_version_id text NULL, name text NOT NULL, width integer NULL, height integer NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.layers(id text PRIMARY KEY, document_id text NOT NULL REFERENCES acpos_runtime.layer_documents(id), layer_type text NOT NULL, layer_name text NOT NULL, semantic_target text NULL, parent_layer_id text NULL REFERENCES acpos_runtime.layers(id), z_index integer NOT NULL, visible boolean NOT NULL DEFAULT true, locked boolean NOT NULL DEFAULT false, opacity numeric(5,4) NOT NULL DEFAULT 1.0, blend_mode text NOT NULL DEFAULT 'NORMAL', transform_json jsonb NULL, mask_ref text NULL, source_ref text NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.patches(id text PRIMARY KEY, patch_type text NOT NULL, source_ref text NOT NULL, target_ref text NULL, instruction text NULL, payload jsonb NOT NULL, status text NOT NULL, preview_json jsonb NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_requests_runtime(id text PRIMARY KEY, finding_id text NOT NULL, source_output_version_id text NOT NULL, source_instruction_package_id text NOT NULL, source_scorecard_id text NULL, original_owner_task_id text NOT NULL, blueprint_version_id text NOT NULL, department text NOT NULL CHECK(department IN ('ASSET','VIDEO','EDITING','VOICE')), provider_id text NULL, root_cause text NOT NULL, affected_scope_json jsonb NOT NULL, revalidation_requirements_json jsonb NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_script_versions_runtime(id text PRIMARY KEY, correction_request_id text NOT NULL REFERENCES acpos_runtime.correction_requests_runtime(id), version_no integer NOT NULL CHECK(version_no > 0), finding_id text NOT NULL, failed_output_version_id text NOT NULL, blueprint_version_id text NOT NULL, original_instruction_package_id text NOT NULL, department text NOT NULL CHECK(department IN ('ASSET','VIDEO','EDITING','VOICE')), provider_id text NULL, root_cause_snapshot text NOT NULL, correction_instruction_json jsonb NOT NULL, status text NOT NULL, decision_reason text NULL, decided_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(correction_request_id,version_no));
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_runs(id text PRIMARY KEY, correction_script_id text NOT NULL REFERENCES acpos_runtime.correction_script_versions_runtime(id), task_id text NOT NULL, provider_candidate_group_id text NOT NULL REFERENCES acpos_runtime.provider_groups(id), source_output_version_id text NOT NULL, new_output_version_id text NULL, route_decision_id text NULL, provider_id text NULL, model_id text NULL, execution_mode text NOT NULL, status text NOT NULL, evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz NULL);
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_rescores(id text PRIMARY KEY, correction_run_id text NOT NULL REFERENCES acpos_runtime.correction_runs(id), correction_script_id text NOT NULL REFERENCES acpos_runtime.correction_script_versions_runtime(id), output_version_id text NOT NULL, scorecard_profile_id text NOT NULL, finding_id text NULL, total_score numeric(5,2) NULL CHECK(total_score IS NULL OR (total_score >= 0 AND total_score <= 100)), gate_status text NOT NULL, evaluation_mode text NOT NULL, evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.voice_runtime_profiles_runtime(id text PRIMARY KEY, profile_key text NOT NULL, version_no integer NOT NULL CHECK(version_no > 0), dna_version_id text NOT NULL, character_id text NULL, profile_json jsonb NOT NULL, content_hash char(64) NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(profile_key,version_no));
CREATE TABLE IF NOT EXISTS acpos_runtime.editing_runtime_runs_runtime(id text PRIMARY KEY, task_id text NOT NULL, timeline_version_id text NOT NULL, approved_video_output_version_ids_json jsonb NOT NULL, voice_runtime_profile_id text NOT NULL REFERENCES acpos_runtime.voice_runtime_profiles_runtime(id), subtitle_language text NOT NULL, subtitle_format text NOT NULL CHECK(subtitle_format IN ('SRT','VTT','ASS','BURN_IN')), current_state text NOT NULL CHECK(current_state IN ('ASSEMBLY','AUDIO_MIX','LIP_SYNC','SUBTITLE','QA_READY','FAILED','SUPERSEDED')), status text NOT NULL, current_output_version_id text NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.editing_runtime_steps_runtime(id text PRIMARY KEY, run_id text NOT NULL REFERENCES acpos_runtime.editing_runtime_runs_runtime(id), step_no integer NOT NULL CHECK(step_no BETWEEN 1 AND 4), step_name text NOT NULL CHECK(step_name IN ('ASSEMBLY','AUDIO_MIX','LIP_SYNC','SUBTITLE')), from_state text NOT NULL, to_state text NOT NULL, evidence_ref text NOT NULL, output_version_id text NOT NULL, payload_json jsonb NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(run_id,step_name));
CREATE TABLE IF NOT EXISTS acpos_runtime.account_permissions(id text PRIMARY KEY, account_id text NOT NULL, resource_key text NOT NULL, actions jsonb NOT NULL, scope_json jsonb NOT NULL, condition_json jsonb NULL, expires_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,resource_key));
CREATE TABLE IF NOT EXISTS acpos_runtime.accounts(id text PRIMARY KEY, email text NOT NULL UNIQUE, password_hash text NOT NULL, status text NOT NULL, bootstrap_admin boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.sessions(token_hash text PRIMARY KEY, account_id text NOT NULL REFERENCES acpos_runtime.accounts(id), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.ui_preferences(account_id text PRIMARY KEY, sidebar_mode text NOT NULL DEFAULT 'MANUAL' CHECK(sidebar_mode IN ('MANUAL','AUTO','PINNED')), auto_collapse_large_workspace boolean NOT NULL DEFAULT true, updated_at timestamptz NOT NULL DEFAULT now());

INSERT INTO schema_migration_history(migration_id, checksum, applied_by, approval_ref)
VALUES ('0007_runtime_operational_schema', 'fcaa7a67b4f21d43bdaf2341c1d0fd4942b302cb4a2522f7530e45a4f24bfa2b', 'migration-runner', 'CR-R9-0007')
ON CONFLICT (migration_id) DO NOTHING;
