-- R9 Correction Engine runtime closure. Existing deployment upgrade; fresh installs also receive these tables from 0007/canonical bootstrap.
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_requests_runtime(id text PRIMARY KEY, finding_id text NOT NULL, source_output_version_id text NOT NULL, source_instruction_package_id text NOT NULL, source_scorecard_id text NULL, original_owner_task_id text NOT NULL, blueprint_version_id text NOT NULL, department text NOT NULL CHECK(department IN ('ASSET','VIDEO','EDITING','VOICE')), provider_id text NULL, root_cause text NOT NULL, affected_scope_json jsonb NOT NULL, revalidation_requirements_json jsonb NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_script_versions_runtime(id text PRIMARY KEY, correction_request_id text NOT NULL REFERENCES acpos_runtime.correction_requests_runtime(id), version_no integer NOT NULL CHECK(version_no > 0), finding_id text NOT NULL, failed_output_version_id text NOT NULL, blueprint_version_id text NOT NULL, original_instruction_package_id text NOT NULL, department text NOT NULL CHECK(department IN ('ASSET','VIDEO','EDITING','VOICE')), provider_id text NULL, root_cause_snapshot text NOT NULL, correction_instruction_json jsonb NOT NULL, status text NOT NULL, decision_reason text NULL, decided_at timestamptz NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(correction_request_id,version_no));
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_runs(id text PRIMARY KEY, correction_script_id text NOT NULL REFERENCES acpos_runtime.correction_script_versions_runtime(id), task_id text NOT NULL, provider_candidate_group_id text NOT NULL REFERENCES acpos_runtime.provider_groups(id), source_output_version_id text NOT NULL, new_output_version_id text NULL, route_decision_id text NULL, provider_id text NULL, model_id text NULL, execution_mode text NOT NULL, status text NOT NULL, evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz NULL);
CREATE TABLE IF NOT EXISTS acpos_runtime.correction_rescores(id text PRIMARY KEY, correction_run_id text NOT NULL REFERENCES acpos_runtime.correction_runs(id), correction_script_id text NOT NULL REFERENCES acpos_runtime.correction_script_versions_runtime(id), output_version_id text NOT NULL, scorecard_profile_id text NOT NULL, finding_id text NULL, total_score numeric(5,2) NULL CHECK(total_score IS NULL OR (total_score >= 0 AND total_score <= 100)), gate_status text NOT NULL, evaluation_mode text NOT NULL, evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());

INSERT INTO schema_migration_history(migration_id, checksum, applied_by, approval_ref)
VALUES ('0011_correction_runtime_closure', 'fd40c4f92763cb80e5ba909c6d492298909c4d74c79cfaf03c35460c7be76e4f', 'migration-runner', 'CR-R9-0011')
ON CONFLICT (migration_id) DO NOTHING;
