import { chromium } from "playwright";
import fs from "node:fs/promises";

const out = "artifacts/vis04";
await fs.mkdir(out, { recursive: true });
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const near = (a,b,t=2) => Math.abs(a-b) <= t;
const rect = async locator => {
  const box = await locator.boundingBox();
  if (!box) throw new Error("Missing geometry target");
  return { x:+box.x.toFixed(1), y:+box.y.toFixed(1), width:+box.width.toFixed(1), height:+box.height.toFixed(1) };
};

const browser = await chromium.launch({ headless:true });
const context = await browser.newContext({ viewport:{ width:1440, height:900 } });
const page = await context.newPage();
const businessRequests = [];
page.on("request", request => { if (["xhr","fetch"].includes(request.resourceType())) businessRequests.push(request.url()); });
await page.goto("http://127.0.0.1:3000/video", { waitUntil:"networkidle" });

const root = page.locator('[data-page-uid="VIDEO-01"]');
assert(await root.count() === 1, "VIDEO-01 root missing");
assert(await root.getAttribute("data-vis-step") === "VIS-04", "VIS-04 marker missing");
assert(await root.getAttribute("data-page-state") === "EMPTY", "VIDEO empty state missing");
assert(await root.getAttribute("data-registry-valid") === "true", "85-control VIDEO registry invalid");
assert(await root.getAttribute("data-authority-controls") === "85", "VIDEO authority control marker mismatch");
const sections = root.locator('[data-section-id]');
const components = await root.locator('[data-component-uid]').evaluateAll(nodes => [...new Set(nodes.map(n=>n.getAttribute('data-component-uid')).filter(Boolean))]);
assert(await sections.count() === 10, `Expected 10 sections, got ${await sections.count()}`);
assert(components.length === 17, `Expected 17 components, got ${components.length}: ${components.join(',')}`);
const visibleControls = root.locator('[data-control-id]');
assert(await visibleControls.count() === 71, `Expected 71 empty-state visible controls, got ${await visibleControls.count()}`);
const conditionalDeclared = await root.locator('[data-conditional-controls]').evaluateAll(nodes => nodes.reduce((sum,n)=>sum+Number(n.getAttribute('data-conditional-controls')||0),0));
assert(conditionalDeclared === 14, `Expected 14 conditional controls, got ${conditionalDeclared}`);
assert(71 + conditionalDeclared === 85, "VIDEO visible + conditional controls do not close to 85");
assert(await root.locator('[data-control-id="VIDEO-01-CTL-VERSION-B"]').count() === 0, "Candidate Version B rendered without Candidate");
assert(await root.locator('[data-section-id="VIDEO-01-SEC-05"] [data-control-id]').count() === 0, "Correction Scope controls rendered before Correction");
assert(await root.locator('[data-section-id="VIDEO-01-SEC-06"] [data-control-id]').count() === 0, "AI Correction controls rendered on first production/empty state");
assert(await root.locator('[data-viewer-count="1"]').count() === 1, "VIDEO must render exactly one current viewer without Candidate");
const interactive = root.locator('button[data-control-id], select[data-control-id], input[data-control-id], textarea[data-control-id]');
const enabledCount = await interactive.evaluateAll(nodes => nodes.filter(n=>!n.disabled).length);
assert(enabledCount === 0, `VIDEO business controls prematurely enabled: ${enabledCount}`);
const header = await rect(page.locator('.global-header'));
const sidebar = await rect(page.locator('.global-sidebar'));
const workspace = await rect(page.locator('.workspace-slot'));
const contextBar = await rect(root.locator('[data-section-id="VIDEO-01-SEC-01"]'));
const left = await rect(root.locator('[data-section-id="VIDEO-01-SEC-02"]'));
const center = await rect(root.locator('[data-section-id="VIDEO-01-SEC-03"]'));
const right = await rect(root.locator('[data-section-id="VIDEO-01-SEC-04"]'));
const viewer = await rect(root.locator('[data-viewer-count="1"]'));
const viewerRatio = viewer.width / viewer.height;
assert(near(header.height,58), `Header height ${header.height}`);
assert(near(sidebar.width,64), `Sidebar width ${sidebar.width}`);
assert(near(workspace.x,78) && near(workspace.y,68), `Workspace origin ${JSON.stringify(workspace)}`);
assert(contextBar.height >= 56, `Context height ${contextBar.height}`);
assert(left.width >= 260, `Left width ${left.width}`);
assert(center.width >= 720, `Center width ${center.width}`);
assert(right.width >= 280, `Right width ${right.width}`);
assert(Math.abs(viewerRatio - 16/9) <= 0.03, `Viewer is not 16:9: ${viewer.width}x${viewer.height} ratio=${viewerRatio}`);
assert(await page.locator('[data-nav-id="NAV-04"][aria-current="page"]').count() === 1, "NAV-04 not active");
assert(await page.locator('[data-nav-id]').count() === 8, "Global nav count changed");
assert(await page.locator('[data-nav-id="NAV-04"]').getAttribute('href') === '/video', "NAV-04 route mismatch");
await page.screenshot({ path:`${out}/vis04-1440-top.png` });
const workspaceNode = page.locator('.workspace-slot');
await workspaceNode.evaluate(el=>{el.scrollTop=680;}); await page.waitForTimeout(100);
await page.screenshot({ path:`${out}/vis04-1440-middle.png` });
await workspaceNode.evaluate(el=>{el.scrollTop=el.scrollHeight;}); await page.waitForTimeout(100);
await page.screenshot({ path:`${out}/vis04-1440-bottom.png` });
await workspaceNode.evaluate(el=>{el.scrollTop=0;});
const languageButton = page.locator('button[aria-haspopup="listbox"]');
await languageButton.click(); await page.getByRole('option',{name:/简体中文/}).click();
assert((await root.locator('[data-control-id="VIDEO-01-BTN-CONFIRM"]').textContent())?.trim() === '确认版本', "zh-CN VIDEO text mismatch");
await languageButton.click(); await page.getByRole('option',{name:/English/}).click();
assert((await root.locator('[data-control-id="VIDEO-01-BTN-EXECUTE"]').textContent())?.trim() === 'Execute', "English execute mismatch");
assert((await root.locator('[data-section-id="VIDEO-01-SEC-03"] h2').textContent())?.includes('Main Preview / Compare'), "English preview heading mismatch");
assert((await root.locator('[data-control-id="VIDEO-01-FLD-PROVIDER"] span').textContent())?.includes('Provider Brand / Model'), "Provider/Model read-only label mismatch");
assert(await page.locator('img[alt="ORANGE ONE"]').count() === 1, "ORANGE ONE logo missing");
await page.screenshot({ path:`${out}/vis04-language-en.png` });
await languageButton.click(); await page.getByRole('option',{name:/繁體中文/}).click();
const workspaceBefore = await rect(page.locator('.workspace-slot'));
await page.locator('.global-sidebar').hover(); await page.waitForTimeout(220);
const sidebarExpanded = await rect(page.locator('.global-sidebar'));
const workspaceAfter = await rect(page.locator('.workspace-slot'));
assert(near(sidebarExpanded.width,221), `Expanded sidebar ${sidebarExpanded.width}`);
assert(near(workspaceBefore.x,workspaceAfter.x) && near(workspaceBefore.width,workspaceAfter.width), "Workspace reflowed on sidebar expand");
assert(businessRequests.length === 0, `Business requests occurred: ${businessRequests.join(',')}`);
const validation = { result:"PASS", implementation:"VIS-04", route:"/video", pageUid:"VIDEO-01", authorityCounts:{sections:10,components:17,controls:85,visibleEmptyStateControls:71,conditionalControls:14}, geometry:{header,sidebarCollapsed:sidebar,sidebarExpanded,workspace,contextBar,left,center,right,viewer,viewerRatio}, state:{fakeBusinessData:false,enabledBusinessControls:enabledCount,viewerCount:1,candidateVersionBRendered:false,correctionControlsRendered:false}, localeSwitching:{locales:["zh-TW","zh-CN","en"],businessRequests:businessRequests.length}, navigation:{count:8,active:"NAV-04",route:"/video"}, workspaceReflowOnSidebarExpand:false };
await fs.writeFile(`${out}/vis04-validation.json`,JSON.stringify(validation,null,2));
await context.close();
const context1200 = await browser.newContext({viewport:{width:1200,height:900}});
const page1200 = await context1200.newPage();
await page1200.goto('http://127.0.0.1:3000/video',{waitUntil:'networkidle'});
const width1200 = await page1200.locator('[data-page-uid="VIDEO-01"]').evaluate(el=>el.getBoundingClientRect().width);
assert(width1200 >= 1280, `1200 viewport must preserve 1280 min width; got ${width1200}`);
await page1200.screenshot({path:`${out}/vis04-1200-minwidth.png`});
await context1200.close();
await browser.close();
console.log(JSON.stringify(validation));
