export type QaCriteriaProjection={page_state:string|null;values:Readonly<Record<string,string>>;control_enabled:Readonly<Record<string,boolean>>};
export type QaCriteriaProjectionResolver={resolve:(raw:unknown)=>QaCriteriaProjection|Promise<QaCriteriaProjection>};
let resolver:QaCriteriaProjectionResolver|null=null;
export function configureQaCriteriaProjectionResolver(next:QaCriteriaProjectionResolver){resolver=next;}
function asRecord(v:unknown):Record<string,unknown>|null{return typeof v==='object'&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:null}
function normalize(raw:unknown):QaCriteriaProjection{const r=asRecord(raw);if(!r)throw new Error('SG02_PROJECTION_NOT_OBJECT');const valuesRaw=asRecord(r.values)??{};const controlRaw=asRecord(r.control_enabled)??{};const values:Record<string,string>={},control_enabled:Record<string,boolean>={};for(const[k,v]of Object.entries(valuesRaw))if(typeof v==='string')values[k]=v;for(const[k,v]of Object.entries(controlRaw))if(typeof v==='boolean')control_enabled[k]=v;const page_state=r.page_state===null||typeof r.page_state==='string'?r.page_state:null;return{page_state,values,control_enabled}}
export async function readQaCriteriaProjection(signal?:AbortSignal){let response:Response;try{response=await fetch('/v1/ui-projections/admin%3ASG-02',{method:'GET',cache:'no-store',signal});}catch{return{ok:false as const,reason_code:'SG02_PROJECTION_REQUEST_FAILED',correlation_id:'unresolved'}}const correlation_id=response.headers.get('x-correlation-id')??'unresolved';const raw:unknown=await response.json().catch(()=>null);if(!response.ok){const b=asRecord(raw);return{ok:false as const,reason_code:typeof b?.reason_code==='string'?b.reason_code:'SG02_PROJECTION_READ_FAILED',correlation_id:typeof b?.correlation_id==='string'?b.correlation_id:correlation_id}}try{return{ok:true as const,projection:resolver?await resolver.resolve(raw):normalize(raw),correlation_id}}catch{return{ok:false as const,reason_code:'SG02_PROJECTION_ADAPTER_REJECTED',correlation_id}}}
export type ConfigureGovernedResourceRequest={resource_type:string;resource_id:string;config_patch_json:unknown;reason:string};
export type ApproveGovernedResourceRequest={resource_type:string;resource_id:string;rationale:string;expected_resource_version?:string};
export async function configureQaCriteriaResource(payload:ConfigureGovernedResourceRequest){const id=encodeURIComponent(payload.resource_id);return command(`/v1/governance/resources/${id}`,'PATCH',payload)}
export async function approveQaCriteriaResource(payload:ApproveGovernedResourceRequest){const id=encodeURIComponent(payload.resource_id);return command(`/v1/governance/resources/${id}/approve`,'POST',payload)}
async function command(path:string,method:'PATCH'|'POST',payload:unknown){const correlation_id=crypto.randomUUID();let response:Response;try{response=await fetch(path,{method,headers:{'content-type':'application/json','x-correlation-id':correlation_id},body:JSON.stringify(payload),cache:'no-store'});}catch{return{ok:false as const,reason_code:'SG02_COMMAND_REQUEST_FAILED',correlation_id}}const raw:unknown=await response.json().catch(()=>null);const body=asRecord(raw);return response.ok?{ok:true as const,value:raw,correlation_id:typeof body?.correlation_id==='string'?body.correlation_id:correlation_id}:{ok:false as const,reason_code:typeof body?.reason_code==='string'?body.reason_code:'SG02_COMMAND_FAILED',correlation_id:typeof body?.correlation_id==='string'?body.correlation_id:correlation_id}}
