export const CORE_ACTION_UIDS = [
  "CORE-01-ACT-PROJECT-SELECT","CORE-01-ACT-PROJECT-CREATE","CORE-01-ACT-TOPIC-SELECT","CORE-01-ACT-TOPIC-CREATE","CORE-01-ACT-WORK-ITEM-SELECT","CORE-01-ACT-THREAD-CREATE","CORE-01-ACT-THREAD-SELECT","CORE-01-ACT-AI-MODE-SINGLE","CORE-01-ACT-AI-MODE-MULTI","CORE-01-ACT-ASSISTANT-RECORD","CORE-01-ACT-MSG-QUOTE","CORE-01-ACT-MSG-CONTINUE","CORE-01-ACT-MSG-ANALYZE","CORE-01-ACT-MSG-DECISION","CORE-01-ACT-MSG-BRANCH","CORE-01-ACT-MSG-COPY","CORE-01-ACT-SEND","CORE-01-ACT-CANDIDATE-CREATE","CORE-01-ACT-CANDIDATE-ACCEPT","CORE-01-ACT-CANDIDATE-RETURN","CORE-01-ACT-CANDIDATE-COMPARE","CORE-01-ACT-PROJECT-VALIDATE","CORE-01-ACT-PROJECT-CONFIRM","CORE-01-ACT-STORY-CANDIDATE","CORE-01-ACT-DNA-LOCK-REQUEST","CORE-01-ACT-CORE-REVIEW-SUBMIT","CORE-01-ACT-MOTHER-LOCK-REQUEST","CORE-01-ACT-BLUEPRINT-CREATE","CORE-01-ACT-BLUEPRINT-VALIDATE","CORE-01-ACT-BLUEPRINT-APPROVE","CORE-01-ACT-CHILD-LOCK-REQUEST","CORE-01-ACT-CANONICAL-SCRIPT-VIEW","CORE-01-ACT-ATTACHMENT","CORE-01-ACT-REFERENCE-ATTACH"
] as const;
export type CoreActionUid = typeof CORE_ACTION_UIDS[number];

export const CORE_GATE_UIDS = [
  "CORE-01-GATE-PAGE","CORE-01-GATE-PROJECT-CONTEXT","CORE-01-GATE-PROJECT-DRAFT","CORE-01-GATE-PROJECT-CONFIRM","CORE-01-GATE-PROJECT-CORE-READY","CORE-01-GATE-PROJECT-LOCK-READY","CORE-01-GATE-TOPIC-CREATE","CORE-01-GATE-TOPIC-CONTEXT","CORE-01-GATE-WORK-ITEM","CORE-01-GATE-THREAD","CORE-01-GATE-MESSAGE","CORE-01-GATE-MULTI-AI","CORE-01-GATE-SUMMARY","CORE-01-GATE-EVALUATION","CORE-01-GATE-HUMAN-DECISION","CORE-01-GATE-CANDIDATE-CREATE","CORE-01-GATE-CANDIDATE-DECIDE","CORE-01-GATE-STORY","CORE-01-GATE-DNA-LOCK","CORE-01-GATE-BLUEPRINT-CREATE","CORE-01-GATE-BLUEPRINT-VALIDATE","CORE-01-GATE-BLUEPRINT-APPROVE","CORE-01-GATE-CHILD-LOCK","CORE-01-GATE-CORE-REVIEW","CORE-01-GATE-CANONICAL-SCRIPT","CORE-01-GATE-NAMING"
] as const;
export type CoreGateUid = typeof CORE_GATE_UIDS[number];

export const CORE_PERMISSION_UIDS = [
  "CORE_USE","CORE_CONVERSATION","CORE_CANDIDATE_CREATE","CORE_CANDIDATE_DECIDE","CORE_PROJECT_WRITE","CORE_PROJECT_CONFIRM","CORE_STORY_WRITE","CORE_DNA_LOCK","CORE_BLUEPRINT_WRITE","CORE_BLUEPRINT_REVIEW","CORE_BLUEPRINT_APPROVE","CORE_LOCK_REQUEST","CORE_TOPIC_WRITE","CORE_SCRIPT_READ"
] as const;
export type CorePermissionUid = typeof CORE_PERMISSION_UIDS[number];

export const CORE_PORT_UIDS = [
  "CORE-01-PORT-PROJECTION","CORE-01-PORT-PROJECT-CREATE","CORE-01-PORT-PROJECT-VALIDATE","CORE-01-PORT-PROJECT-CONFIRM","CORE-01-PORT-STORY-CANDIDATE","CORE-01-PORT-THREAD-CREATE","CORE-01-PORT-MESSAGE-SEND","CORE-01-PORT-CANDIDATE-CREATE","CORE-01-PORT-CANDIDATE-COMPARE","CORE-01-PORT-CANDIDATE-DECIDE","CORE-01-PORT-DNA-LOCK","CORE-01-PORT-CORE-REVIEW","CORE-01-PORT-MOTHER-LOCK","CORE-01-PORT-TOPIC-CREATE","CORE-01-PORT-BLUEPRINT-CREATE","CORE-01-PORT-BLUEPRINT-VALIDATE","CORE-01-PORT-BLUEPRINT-APPROVE","CORE-01-PORT-CHILD-LOCK","CORE-01-PORT-CANONICAL-SCRIPT"
] as const;
export type CorePortUid = typeof CORE_PORT_UIDS[number];

export type CoreRuntimeErrorUid =
  | "CORE-01-ERR-CONTEXT-001" | "CORE-01-ERR-TOPIC-LINEAGE-001" | "CORE-01-ERR-WORK-ITEM-001"
  | "CORE-01-ERR-THREAD-001" | "CORE-01-ERR-AI-ROUTE-001" | "CORE-01-ERR-CONVERSATION-001"
  | "CORE-01-ERR-CRITERIA-001" | "CORE-01-ERR-DECISION-001" | "CORE-01-ERR-CANDIDATE-001"
  | "CORE-01-ERR-VERSION-001" | "CORE-01-ERR-DNA-LOCK-001" | "CORE-01-ERR-BLUEPRINT-001"
  | "CORE-01-ERR-LOCK-CONTRACT-001" | "CORE-01-ERR-NAMING-001" | "CORE-01-ERR-PERM-001"
  | "CORE-01-ERR-UNDEFINED-001";

export type CoreRuntimeRequest = {
  port_uid: CorePortUid;
  action_uid?: CoreActionUid;
  correlation_id: string;
  path_params?: Record<string, string>;
  query?: Record<string, string>;
  payload?: unknown;
};

export type CoreRuntimeResult =
  | { ok: true; value: unknown; correlation_id: string }
  | { ok: false; error_uid: CoreRuntimeErrorUid; reason_code: string; correlation_id: string; status: number };

export const CORE_PORT_METHOD_PATH: Record<CorePortUid, { method: "GET" | "POST"; path: string }> = {
  "CORE-01-PORT-PROJECTION": { method: "GET", path: "/v1/ui-projections/{pageUid}" },
  "CORE-01-PORT-PROJECT-CREATE": { method: "POST", path: "/v1/projects/drafts" },
  "CORE-01-PORT-PROJECT-VALIDATE": { method: "POST", path: "/v1/projects/drafts/{projectVersionId}/validate" },
  "CORE-01-PORT-PROJECT-CONFIRM": { method: "POST", path: "/v1/projects/drafts/{id}/confirm" },
  "CORE-01-PORT-STORY-CANDIDATE": { method: "POST", path: "/v1/projects/{projectId}/story-candidate-sets" },
  "CORE-01-PORT-THREAD-CREATE": { method: "POST", path: "/v1/projects/{projectId}/conversations" },
  "CORE-01-PORT-MESSAGE-SEND": { method: "POST", path: "/v1/conversations/{conversationId}/messages" },
  "CORE-01-PORT-CANDIDATE-CREATE": { method: "POST", path: "/v1/candidates" },
  "CORE-01-PORT-CANDIDATE-COMPARE": { method: "GET", path: "/v1/candidates/compare" },
  "CORE-01-PORT-CANDIDATE-DECIDE": { method: "POST", path: "/v1/candidates/{id}/decision" },
  "CORE-01-PORT-DNA-LOCK": { method: "POST", path: "/v1/state-commands/dnaversion/requestdnalock" },
  "CORE-01-PORT-CORE-REVIEW": { method: "POST", path: "/v1/state-commands/projectversion/submitcorereview" },
  "CORE-01-PORT-MOTHER-LOCK": { method: "POST", path: "/v1/locks/mother-requests" },
  "CORE-01-PORT-TOPIC-CREATE": { method: "POST", path: "/v1/projects/{projectId}/topics" },
  "CORE-01-PORT-BLUEPRINT-CREATE": { method: "POST", path: "/v1/topics/{id}/blueprints" },
  "CORE-01-PORT-BLUEPRINT-VALIDATE": { method: "POST", path: "/v1/blueprints/{id}/validate" },
  "CORE-01-PORT-BLUEPRINT-APPROVE": { method: "POST", path: "/v1/blueprints/{id}/approve" },
  "CORE-01-PORT-CHILD-LOCK": { method: "POST", path: "/v1/locks/child-requests" },
  "CORE-01-PORT-CANONICAL-SCRIPT": { method: "GET", path: "/v1/topics/{id}/scripts/canonical" },
};

export const CORE_ACTION_PORT: Partial<Record<CoreActionUid, CorePortUid>> = {
  "CORE-01-ACT-PROJECT-CREATE":"CORE-01-PORT-PROJECT-CREATE",
  "CORE-01-ACT-TOPIC-CREATE":"CORE-01-PORT-TOPIC-CREATE",
  "CORE-01-ACT-THREAD-CREATE":"CORE-01-PORT-THREAD-CREATE",
  "CORE-01-ACT-MSG-ANALYZE":"CORE-01-PORT-MESSAGE-SEND",
  "CORE-01-ACT-MSG-BRANCH":"CORE-01-PORT-THREAD-CREATE",
  "CORE-01-ACT-SEND":"CORE-01-PORT-MESSAGE-SEND",
  "CORE-01-ACT-CANDIDATE-CREATE":"CORE-01-PORT-CANDIDATE-CREATE",
  "CORE-01-ACT-CANDIDATE-ACCEPT":"CORE-01-PORT-CANDIDATE-DECIDE",
  "CORE-01-ACT-CANDIDATE-RETURN":"CORE-01-PORT-CANDIDATE-DECIDE",
  "CORE-01-ACT-CANDIDATE-COMPARE":"CORE-01-PORT-CANDIDATE-COMPARE",
  "CORE-01-ACT-PROJECT-VALIDATE":"CORE-01-PORT-PROJECT-VALIDATE",
  "CORE-01-ACT-PROJECT-CONFIRM":"CORE-01-PORT-PROJECT-CONFIRM",
  "CORE-01-ACT-STORY-CANDIDATE":"CORE-01-PORT-STORY-CANDIDATE",
  "CORE-01-ACT-DNA-LOCK-REQUEST":"CORE-01-PORT-DNA-LOCK",
  "CORE-01-ACT-CORE-REVIEW-SUBMIT":"CORE-01-PORT-CORE-REVIEW",
  "CORE-01-ACT-MOTHER-LOCK-REQUEST":"CORE-01-PORT-MOTHER-LOCK",
  "CORE-01-ACT-BLUEPRINT-CREATE":"CORE-01-PORT-BLUEPRINT-CREATE",
  "CORE-01-ACT-BLUEPRINT-VALIDATE":"CORE-01-PORT-BLUEPRINT-VALIDATE",
  "CORE-01-ACT-BLUEPRINT-APPROVE":"CORE-01-PORT-BLUEPRINT-APPROVE",
  "CORE-01-ACT-CHILD-LOCK-REQUEST":"CORE-01-PORT-CHILD-LOCK",
  "CORE-01-ACT-CANONICAL-SCRIPT-VIEW":"CORE-01-PORT-CANONICAL-SCRIPT"
};
