export const DB_PERMISSION = "database.metadata.read";
export const DB_PAGE_UID = "admin:DB-01";
export const DB_ROUTE = "/db";
export const DB_PROJECTION = "DbWorkbenchProjection";
export const DB_CHAIN = "DB-01-FWC-PAGE-01";

export const DB_VISIBLE_CONTROLS = [
  "DB-01-FLD-ENV",
  "DB-01-FLD-SCHEMA-HEAD",
  "DB-01-FLD-MIGRATION-HEAD",
  "DB-01-FLD-SCOPE",
  "DB-01-FLD-HEALTH",
  "DB-01-BTN-REFRESH",
  "DB-01-INP-SEARCH",
  "DB-01-SEL-DOMAIN",
  "DB-01-SEL-ENTITY-TYPE",
  "DB-01-LIST-ENTITIES",
  "DB-01-FLD-ENTITY",
  "DB-01-FLD-TABLE",
  "DB-01-FLD-OWNER",
  "DB-01-FLD-CLASSIFICATION",
  "DB-01-FLD-PK",
  "DB-01-FLD-VERSION-RULE",
  "DB-01-TBL-COLUMNS",
  "DB-01-TBL-CONSTRAINTS",
  "DB-01-BTN-SCHEMA-REFRESH",
  "DB-01-TOGGLE-RELATION-VIEW",
  "DB-01-GRAPH-RELATIONS",
  "DB-01-LIST-RELATIONS",
  "DB-01-SEL-TRACE-TYPE",
  "DB-01-INP-TRACE-ID",
  "DB-01-BTN-TRACE",
  "DB-01-VIEW-TRACE-PATH",
  "DB-01-FLD-REF-INTEGRITY",
  "DB-01-FLD-ORPHAN",
  "DB-01-FLD-IMMUTABLE",
  "DB-01-FLD-TRACE-COMPLETE",
  "DB-01-FLD-MIGRATION-INTEGRITY",
  "DB-01-BTN-INTEGRITY-REFRESH",
  "DB-01-INP-MIGRATION-SEARCH",
  "DB-01-TBL-MIGRATIONS",
  "DB-01-BTN-MIGRATION-REFRESH",
  "DB-01-SEL-FINDING-TYPE",
  "DB-01-LIST-FINDINGS",
  "DB-01-FLD-FINDING-REASON",
  "DB-01-FLD-FINDING-AFFECTED",
  "DB-01-FLD-FINDING-EVIDENCE",
  "DB-01-FLD-FINDING-OWNER",
  "DB-01-INP-AUDIT-ID",
  "DB-01-BTN-AUDIT",
  "DB-01-VIEW-AUDIT",
  "DB-01-FLD-PAGE-STATE",
  "DB-01-FLD-SOURCE-SYNC",
  "DB-01-FLD-DISABLED",
  "DB-01-FLD-CHANGE-OWNER",
  "DB-01-BTN-SYSTEM-LIFECYCLE",
] as const;

export const DB_CONTROL_ACTIONS: Record<string, string> = {
  "DB-01-FLD-ENV": "DB-01-ACT-NOOP",
  "DB-01-FLD-SCHEMA-HEAD": "DB-01-ACT-NOOP",
  "DB-01-FLD-MIGRATION-HEAD": "DB-01-ACT-NOOP",
  "DB-01-FLD-SCOPE": "DB-01-ACT-NOOP",
  "DB-01-FLD-HEALTH": "DB-01-ACT-NOOP",
  "DB-01-BTN-REFRESH": "DB-01-ACT-SCHEMA-REFRESH",
  "DB-01-INP-SEARCH": "DB-01-ACT-SEARCH",
  "DB-01-SEL-DOMAIN": "DB-01-ACT-FILTER",
  "DB-01-SEL-ENTITY-TYPE": "DB-01-ACT-FILTER",
  "DB-01-LIST-ENTITIES": "DB-01-ACT-ENTITY-SELECT",
  "DB-01-FLD-ENTITY": "DB-01-ACT-NOOP",
  "DB-01-FLD-TABLE": "DB-01-ACT-NOOP",
  "DB-01-FLD-OWNER": "DB-01-ACT-NOOP",
  "DB-01-FLD-CLASSIFICATION": "DB-01-ACT-NOOP",
  "DB-01-FLD-PK": "DB-01-ACT-NOOP",
  "DB-01-FLD-VERSION-RULE": "DB-01-ACT-NOOP",
  "DB-01-TBL-COLUMNS": "DB-01-ACT-NOOP",
  "DB-01-TBL-CONSTRAINTS": "DB-01-ACT-NOOP",
  "DB-01-BTN-SCHEMA-REFRESH": "DB-01-ACT-SCHEMA-REFRESH",
  "DB-01-TOGGLE-RELATION-VIEW": "DB-01-ACT-RELATION-MODE",
  "DB-01-GRAPH-RELATIONS": "DB-01-ACT-RELATION-OPEN",
  "DB-01-LIST-RELATIONS": "DB-01-ACT-RELATION-OPEN",
  "DB-01-SEL-TRACE-TYPE": "DB-01-ACT-CONTEXT",
  "DB-01-INP-TRACE-ID": "DB-01-ACT-CONTEXT",
  "DB-01-BTN-TRACE": "DB-01-ACT-TRACE",
  "DB-01-VIEW-TRACE-PATH": "DB-01-ACT-RELATION-OPEN",
  "DB-01-FLD-REF-INTEGRITY": "DB-01-ACT-NOOP",
  "DB-01-FLD-ORPHAN": "DB-01-ACT-NOOP",
  "DB-01-FLD-IMMUTABLE": "DB-01-ACT-NOOP",
  "DB-01-FLD-TRACE-COMPLETE": "DB-01-ACT-NOOP",
  "DB-01-FLD-MIGRATION-INTEGRITY": "DB-01-ACT-NOOP",
  "DB-01-BTN-INTEGRITY-REFRESH": "DB-01-ACT-INTEGRITY-REFRESH",
  "DB-01-INP-MIGRATION-SEARCH": "DB-01-ACT-MIGRATION-REFRESH",
  "DB-01-TBL-MIGRATIONS": "DB-01-ACT-MIGRATION-SELECT",
  "DB-01-BTN-MIGRATION-REFRESH": "DB-01-ACT-MIGRATION-REFRESH",
  "DB-01-SEL-FINDING-TYPE": "DB-01-ACT-FILTER",
  "DB-01-LIST-FINDINGS": "DB-01-ACT-FINDING-SELECT",
  "DB-01-FLD-FINDING-REASON": "DB-01-ACT-NOOP",
  "DB-01-FLD-FINDING-AFFECTED": "DB-01-ACT-NOOP",
  "DB-01-FLD-FINDING-EVIDENCE": "DB-01-ACT-NOOP",
  "DB-01-FLD-FINDING-OWNER": "DB-01-ACT-NOOP",
  "DB-01-INP-AUDIT-ID": "DB-01-ACT-CONTEXT",
  "DB-01-BTN-AUDIT": "DB-01-ACT-AUDIT-OPEN",
  "DB-01-VIEW-AUDIT": "DB-01-ACT-NOOP",
  "DB-01-FLD-PAGE-STATE": "DB-01-ACT-NOOP",
  "DB-01-FLD-SOURCE-SYNC": "DB-01-ACT-NOOP",
  "DB-01-FLD-DISABLED": "DB-01-ACT-NOOP",
  "DB-01-FLD-CHANGE-OWNER": "DB-01-ACT-NOOP",
  "DB-01-BTN-SYSTEM-LIFECYCLE": "DB-01-ACT-SYSTEM-LIFECYCLE",
};

export interface DbFieldValue {
  controlUid: string;
  value: string | null;
}

export interface DbReadModel {
  projectionUid: typeof DB_PROJECTION;
  pageUid: typeof DB_PAGE_UID;
  route: typeof DB_ROUTE;
  permission: typeof DB_PERMISSION;
  chainUid: typeof DB_CHAIN;
  authorized: boolean;
  fields: DbFieldValue[];
}
