export const DEV_PERMISSION = "outreach.discovery.configure";
export const DEV_PAGE_UID = "admin:DEV-01";
export const DEV_ROUTE = "/admin/dev";
export const DEV_PROJECTION = "DevWorkbenchProjection";
export const DEV_CHAIN = "DEV-01-FWC-PAGE-01";

export const DEV_VISIBLE_CONTROLS = [
  "DEV-01-BTN-STAGE-1",
  "DEV-01-BTN-STAGE-2",
  "DEV-01-BTN-STAGE-3",
  "DEV-01-BTN-STAGE-4",
  "DEV-01-BTN-STAGE-5",
  "DEV-01-BTN-DISCOVERY-START",
  "DEV-01-BTN-DISCOVERY-PAUSE",
  "DEV-01-BTN-DISCOVERY-RESUME",
  "DEV-01-BTN-DISCOVERY-STOP",
  "DEV-01-BTN-DIRECTORY-SEARCH",
  "DEV-01-BTN-MERGE-PREVIEW",
  "DEV-01-BTN-MERGE",
  "DEV-01-BTN-EXPORT",
  "DEV-01-BTN-CANDIDATE-CREATE",
  "DEV-01-BTN-CANDIDATE-DECIDE",
  "DEV-01-BTN-CR-CREATE",
  "DEV-01-BTN-CAMPAIGN-SEARCH",
  "DEV-01-BTN-CAMPAIGN-CREATE",
  "DEV-01-BTN-CAMPAIGN-APPROVE",
  "DEV-01-BTN-EMAIL-DISPATCH",
  "DEV-01-BTN-REFRESH",
  "DEV-01-BTN-KILL-SWITCH",
] as const;

export const DEV_CONTROL_ACTIONS: Record<string, string> = {
  "DEV-01-BTN-STAGE-1": "DEV-01-ACT-STAGE-1-SELECT",
  "DEV-01-BTN-STAGE-2": "DEV-01-ACT-STAGE-2-SELECT",
  "DEV-01-BTN-STAGE-3": "DEV-01-ACT-STAGE-3-SELECT",
  "DEV-01-BTN-STAGE-4": "DEV-01-ACT-STAGE-4-SELECT",
  "DEV-01-BTN-STAGE-5": "DEV-01-ACT-STAGE-5-SELECT",
  "DEV-01-BTN-DISCOVERY-START": "DEV-01-ACT-DISCOVERY-START",
  "DEV-01-BTN-DISCOVERY-PAUSE": "DEV-01-ACT-DISCOVERY-PAUSE",
  "DEV-01-BTN-DISCOVERY-RESUME": "DEV-01-ACT-DISCOVERY-RESUME",
  "DEV-01-BTN-DISCOVERY-STOP": "DEV-01-ACT-DISCOVERY-STOP",
  "DEV-01-BTN-DIRECTORY-SEARCH": "DEV-01-ACT-DIRECTORY-SEARCH",
  "DEV-01-BTN-MERGE-PREVIEW": "DEV-01-ACT-MERGE-PREVIEW",
  "DEV-01-BTN-MERGE": "DEV-01-ACT-MERGE",
  "DEV-01-BTN-EXPORT": "DEV-01-ACT-EXPORT",
  "DEV-01-BTN-CANDIDATE-CREATE": "DEV-01-ACT-CANDIDATE-CREATE",
  "DEV-01-BTN-CANDIDATE-DECIDE": "DEV-01-ACT-CANDIDATE-DECIDE",
  "DEV-01-BTN-CR-CREATE": "DEV-01-ACT-CR-CREATE",
  "DEV-01-BTN-CAMPAIGN-SEARCH": "DEV-01-ACT-CAMPAIGN-SEARCH",
  "DEV-01-BTN-CAMPAIGN-CREATE": "DEV-01-ACT-CAMPAIGN-CREATE",
  "DEV-01-BTN-CAMPAIGN-APPROVE": "DEV-01-ACT-CAMPAIGN-APPROVE",
  "DEV-01-BTN-EMAIL-DISPATCH": "DEV-01-ACT-EMAIL-DISPATCH",
  "DEV-01-BTN-REFRESH": "DEV-01-ACT-REFRESH",
  "DEV-01-BTN-KILL-SWITCH": "DEV-01-ACT-KILL-SWITCH",
};

export interface DevFieldValue {
  controlUid: string;
  value: string | null;
}

export interface DevReadModel {
  projectionUid: typeof DEV_PROJECTION;
  pageUid: typeof DEV_PAGE_UID;
  route: typeof DEV_ROUTE;
  permission: typeof DEV_PERMISSION;
  chainUid: typeof DEV_CHAIN;
  authorized: boolean;
  fields: DevFieldValue[];
}
