export const ERP_PERMISSION = "erp.connector.read";
export const ERP_PAGE_UID = "admin:ERP-01";
export const ERP_ROUTE = "/admin/erp";
export const ERP_PROJECTION = "ErpWorkbenchProjection";
export const ERP_CHAIN = "ERP-01-FWC-PAGE-01";

export const ERP_VISIBLE_CONTROLS = [
  "ERP-01-FLD-SCOPE",
  "ERP-01-FLD-SNAPSHOT",
  "ERP-01-FLD-FRESHNESS",
  "ERP-01-BTN-TAB-FINANCE",
  "ERP-01-BTN-TAB-CONNECTOR",
  "ERP-01-BTN-TAB-SYNC",
  "ERP-01-FLD-FIN-COST",
  "ERP-01-FLD-FIN-REVENUE",
  "ERP-01-FLD-FIN-CASHFLOW",
  "ERP-01-FLD-FIN-CAPACITY",
  "ERP-01-FLD-FIN-FORECAST",
  "ERP-01-FLD-FIN-GUARDRAILS",
  "ERP-01-FLD-FIN-RECOMMENDATION-BOUNDARY",
  "ERP-01-BTN-FACTPACK",
  "ERP-01-BTN-GUARDRAILS",
  "ERP-01-BTN-FORECAST",
  "ERP-01-BTN-EXPORT",
  "ERP-01-FLD-CONN-CONNECTOR-ID",
  "ERP-01-FLD-CONN-PROVIDER-KEY",
  "ERP-01-FLD-CONN-ADAPTER-KEY",
  "ERP-01-FLD-CONN-SECRET-REFERENCE-ID",
  "ERP-01-FLD-CONN-ENTITY-SCOPE",
  "ERP-01-FLD-CONN-CONNECTION-STATUS",
  "ERP-01-FLD-CONN-MAPPING-VERSION",
  "ERP-01-BTN-CONNECTOR-CREATE",
  "ERP-01-BTN-CONNECTOR-UPDATE",
  "ERP-01-BTN-CONNECTOR-VALIDATE",
  "ERP-01-BTN-MAPPING-VALIDATE",
  "ERP-01-FLD-SYNC-SNAPSHOT-ID",
  "ERP-01-FLD-SYNC-FRESHNESS-AT",
  "ERP-01-FLD-SYNC-CURRENCY-TIMEZONE",
  "ERP-01-FLD-SYNC-COMPLETENESS",
  "ERP-01-FLD-SYNC-LAST-SYNC-STATUS",
  "ERP-01-FLD-SYNC-FAILURE-ID",
  "ERP-01-BTN-SNAPSHOT-REFRESH",
  "ERP-01-BTN-SYNC-CREATE",
  "ERP-01-BTN-SYNC-STATUS",
  "ERP-01-BTN-SYNC-RETRY",
  "ERP-01-BTN-FAILURE-GET",
  "ERP-01-FLD-READINESS",
  "ERP-01-FLD-AUDIT-REF",
  "ERP-01-BTN-DETAIL",
] as const;

export const ERP_CONTROL_ACTIONS: Record<string, string> = {
  "ERP-01-FLD-SCOPE": "ERP-01-ACT-READ",
  "ERP-01-FLD-SNAPSHOT": "ERP-01-ACT-READ",
  "ERP-01-FLD-FRESHNESS": "ERP-01-ACT-READ",
  "ERP-01-BTN-TAB-FINANCE": "ERP-01-ACT-VIEW-FINANCE",
  "ERP-01-BTN-TAB-CONNECTOR": "ERP-01-ACT-VIEW-CONNECTOR",
  "ERP-01-BTN-TAB-SYNC": "ERP-01-ACT-VIEW-SYNC",
  "ERP-01-FLD-FIN-COST": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-FLD-FIN-REVENUE": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-FLD-FIN-CASHFLOW": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-FLD-FIN-CAPACITY": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-FLD-FIN-FORECAST": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-FLD-FIN-GUARDRAILS": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-FLD-FIN-RECOMMENDATION-BOUNDARY": "ERP-01-ACT-READ-FINANCE",
  "ERP-01-BTN-FACTPACK": "ERP-01-ACT-FACTPACK",
  "ERP-01-BTN-GUARDRAILS": "ERP-01-ACT-GUARDRAILS",
  "ERP-01-BTN-FORECAST": "ERP-01-ACT-FORECAST",
  "ERP-01-BTN-EXPORT": "ERP-01-ACT-EXPORT",
  "ERP-01-FLD-CONN-CONNECTOR-ID": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-FLD-CONN-PROVIDER-KEY": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-FLD-CONN-ADAPTER-KEY": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-FLD-CONN-SECRET-REFERENCE-ID": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-FLD-CONN-ENTITY-SCOPE": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-FLD-CONN-CONNECTION-STATUS": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-FLD-CONN-MAPPING-VERSION": "ERP-01-ACT-READ-CONNECTOR",
  "ERP-01-BTN-CONNECTOR-CREATE": "ERP-01-ACT-CONNECTOR-CREATE",
  "ERP-01-BTN-CONNECTOR-UPDATE": "ERP-01-ACT-CONNECTOR-UPDATE",
  "ERP-01-BTN-CONNECTOR-VALIDATE": "ERP-01-ACT-CONNECTOR-VALIDATE",
  "ERP-01-BTN-MAPPING-VALIDATE": "ERP-01-ACT-MAPPING-VALIDATE",
  "ERP-01-FLD-SYNC-SNAPSHOT-ID": "ERP-01-ACT-READ-SYNC",
  "ERP-01-FLD-SYNC-FRESHNESS-AT": "ERP-01-ACT-READ-SYNC",
  "ERP-01-FLD-SYNC-CURRENCY-TIMEZONE": "ERP-01-ACT-READ-SYNC",
  "ERP-01-FLD-SYNC-COMPLETENESS": "ERP-01-ACT-READ-SYNC",
  "ERP-01-FLD-SYNC-LAST-SYNC-STATUS": "ERP-01-ACT-READ-SYNC",
  "ERP-01-FLD-SYNC-FAILURE-ID": "ERP-01-ACT-READ-SYNC",
  "ERP-01-BTN-SNAPSHOT-REFRESH": "ERP-01-ACT-SNAPSHOT-REFRESH",
  "ERP-01-BTN-SYNC-CREATE": "ERP-01-ACT-SYNC-CREATE",
  "ERP-01-BTN-SYNC-STATUS": "ERP-01-ACT-SYNC-STATUS",
  "ERP-01-BTN-SYNC-RETRY": "ERP-01-ACT-SYNC-RETRY",
  "ERP-01-BTN-FAILURE-GET": "ERP-01-ACT-FAILURE-GET",
  "ERP-01-FLD-READINESS": "ERP-01-ACT-READ",
  "ERP-01-FLD-AUDIT-REF": "ERP-01-ACT-READ",
  "ERP-01-BTN-DETAIL": "ERP-01-ACT-DETAIL-OPEN",
};

export interface ErpFieldValue {
  controlUid: string;
  value: string | null;
}

export interface ErpReadModel {
  projectionUid: typeof ERP_PROJECTION;
  pageUid: typeof ERP_PAGE_UID;
  route: typeof ERP_ROUTE;
  permission: typeof ERP_PERMISSION;
  chainUid: typeof ERP_CHAIN;
  authorized: boolean;
  fields: ErpFieldValue[];
}
