export const SOC_PERMISSION = "social.account.configure";
export const SOC_PAGE_UID = "admin:SOC-01";
export const SOC_ROUTE = "/admin/social";
export const SOC_PROJECTION = "SocWorkbenchProjection";
export const SOC_CHAIN = "SOC-01-FWC-PAGE-01";

export const SOC_VISIBLE_CONTROLS = [
  "SOC-01-TAB-STAGE-1",
  "SOC-01-TAB-STAGE-2",
  "SOC-01-TAB-STAGE-3",
  "SOC-01-TAB-STAGE-4",
  "SOC-01-TAB-STAGE-5",
  "SOC-01-BTN-PLATFORM-CONFIG",
  "SOC-01-BTN-KILL",
  "SOC-01-BTN-ACCOUNT-BIND",
  "SOC-01-BTN-CREDENTIAL-REVEAL",
  "SOC-01-BTN-ACCOUNT-UNBIND",
  "SOC-01-BTN-TARGET-DISCOVERY",
  "SOC-01-BTN-TARGET-JOIN",
  "SOC-01-BTN-MANUAL-COMPLETE",
  "SOC-01-INP-TARGET-SEARCH",
  "SOC-01-BTN-CONTENT-SAVE",
  "SOC-01-BTN-CANDIDATE-DECIDE",
  "SOC-01-BTN-POLICY-CONFIG",
  "SOC-01-BTN-PUBLISH",
  "SOC-01-INP-RECORD-SEARCH",
  "SOC-01-BTN-REFRESH",
  "SOC-01-BTN-DETAIL",
] as const;

export const SOC_CONTROL_ACTIONS: Record<string, string> = {
  "SOC-01-TAB-STAGE-1": "SOC-01-ACT-STAGE-1-SELECT",
  "SOC-01-TAB-STAGE-2": "SOC-01-ACT-STAGE-2-SELECT",
  "SOC-01-TAB-STAGE-3": "SOC-01-ACT-STAGE-3-SELECT",
  "SOC-01-TAB-STAGE-4": "SOC-01-ACT-STAGE-4-SELECT",
  "SOC-01-TAB-STAGE-5": "SOC-01-ACT-STAGE-5-SELECT",
  "SOC-01-BTN-PLATFORM-CONFIG": "SOC-01-ACT-PLATFORM-CONFIG",
  "SOC-01-BTN-KILL": "SOC-01-ACT-KILL-SWITCH",
  "SOC-01-BTN-ACCOUNT-BIND": "SOC-01-ACT-ACCOUNT-BIND",
  "SOC-01-BTN-CREDENTIAL-REVEAL": "SOC-01-ACT-CREDENTIAL-REVEAL",
  "SOC-01-BTN-ACCOUNT-UNBIND": "SOC-01-ACT-ACCOUNT-UNBIND",
  "SOC-01-BTN-TARGET-DISCOVERY": "SOC-01-ACT-TARGET-DISCOVERY",
  "SOC-01-BTN-TARGET-JOIN": "SOC-01-ACT-TARGET-JOIN",
  "SOC-01-BTN-MANUAL-COMPLETE": "SOC-01-ACT-MANUAL-COMPLETE",
  "SOC-01-INP-TARGET-SEARCH": "SOC-01-ACT-SEARCH",
  "SOC-01-BTN-CONTENT-SAVE": "SOC-01-ACT-CONTENT-SAVE",
  "SOC-01-BTN-CANDIDATE-DECIDE": "SOC-01-ACT-CANDIDATE-DECIDE",
  "SOC-01-BTN-POLICY-CONFIG": "SOC-01-ACT-POLICY-CONFIG",
  "SOC-01-BTN-PUBLISH": "SOC-01-ACT-PUBLISH-REQUEST",
  "SOC-01-INP-RECORD-SEARCH": "SOC-01-ACT-SEARCH",
  "SOC-01-BTN-REFRESH": "SOC-01-ACT-REFRESH",
  "SOC-01-BTN-DETAIL": "SOC-01-ACT-DETAIL-OPEN",
};

export interface SocFieldValue {
  controlUid: string;
  value: string | null;
}

export interface SocReadModel {
  projectionUid: typeof SOC_PROJECTION;
  pageUid: typeof SOC_PAGE_UID;
  route: typeof SOC_ROUTE;
  permission: typeof SOC_PERMISSION;
  chainUid: typeof SOC_CHAIN;
  authorized: boolean;
  fields: SocFieldValue[];
}
