import{isControlledTestMode}from"@/domain/testing/controlledTestData";
import type{QaResolvedContext}from"@/domain/qa/qaClientState";
import type{QaRequest}from"@/server/qa/qaRuntime";
import{configureQaManualReviewRuntime}from"@/server/qa/qaManualReviewRuntime";
import{configureQaAutoOrchestrator}from"@/server/qa/qaAutoOrchestrator";
import type{DepartmentOperationRequest}from"@/server/shared/departmentOperationRuntime";

type QaTestScenario="CORRECTION"|"MANUAL_REQUIRED"|"AUTO";
const scenario=():QaTestScenario=>{const v=process.env.ACPOS_QA_TEST_SCENARIO;return v==="MANUAL_REQUIRED"||v==="AUTO"?v:"CORRECTION";};
const item=(ref:string,label:string,meta:Record<string,string|number|boolean|null>={})=>({ref,label,meta});
const baseGates=()=>({"QA-01-GATE-PAGE":true,"QA-01-GATE-CONTEXT":true,"QA-01-GATE-START":true,"QA-01-GATE-AUTO":true,"QA-01-GATE-VIEWER":false,"QA-01-GATE-COMPARE":false,"QA-01-GATE-SCRIPT":false,"QA-01-GATE-CRITERIA":false,"QA-01-GATE-EVIDENCE":false,"QA-01-GATE-SCORE":false,"QA-01-GATE-FINDING":false,"QA-01-GATE-CORRECTION":false,"QA-01-GATE-RECHECK":false,"QA-01-GATE-PASS":false,"QA-01-GATE-FAIL":false,"QA-01-GATE-RELEASE":false,"QA-01-GATE-MANUAL":false,"QA-01-GATE-EVIDENCE-CAPTURE":false,"QA-01-GATE-MANUAL-DECISION":false});
type QaControlledTestGlobal=typeof globalThis&{__ACPOS_QA_CONTROLLED_TEST_STATE__?:QaResolvedContext};
const qaControlledTestGlobal=globalThis as QaControlledTestGlobal;
function currentState(){return qaControlledTestGlobal.__ACPOS_QA_CONTROLLED_TEST_STATE__??(qaControlledTestGlobal.__ACPOS_QA_CONTROLLED_TEST_STATE__=createInitial());}
function replaceState(next:QaResolvedContext){qaControlledTestGlobal.__ACPOS_QA_CONTROLLED_TEST_STATE__=next;}
function createInitial():QaResolvedContext{return{page_state_uid:"QA-01-ST-NOT-STARTED",current_stage_uid:"QA-01-STAGE-01-RESOLVE",project_id:"TEST-QA-PROJECT-001",topic_id:"TEST-QA-TOPIC-001",qa_task_ref:"TEST-QA-TASK-001",target_output_version_id:"TEST-EDIT-OUTPUT-001",qa_review_ref:null,viewer_uri:"TEST-OUTPUT-URI-001",failed_output_version_id:null,verified_new_output_version_id:null,manual_review_case_ref:null,scorecard_ref:null,release_package_ref:null,correlation_id:null,audit_ref:"TEST-QA-AUDIT-001",gate_state:baseGates(),values:{
"QA-01-FLD-REVIEW-STATE":"NOT_STARTED","QA-01-FLD-QA-SCRIPT":"TEST-QA-VALIDATION-SCRIPT-001","QA-01-FLD-SCRIPT-HASH":"TEST-QA-SCRIPT-HASH-001","QA-01-FLD-CRITERIA-VERSION":"TEST-QA-CRITERIA-V1","QA-01-FLD-GATE-POLICY":"TEST-QA-GATE-POLICY-V1","QA-01-FLD-EVIDENCE":"TEST-QA-EVIDENCE-001","QA-01-FLD-CHECKSUM":"TEST-OUTPUT-CHECKSUM-001","QA-01-FLD-PROVENANCE":"TEST-EDIT-OUTPUT-001→QA-01","QA-01-FLD-REQUIRED-CHECKS":"TEST-REQUIRED-CHECKSET-001","QA-01-FLD-RIGHTS":"PASS:TEST-RIGHTS-POLICY-V1","QA-01-FLD-POLICY":"PASS:TEST-CONTENT-POLICY-V1","QA-01-FLD-TOTAL-SCORE":"—","QA-01-FLD-HARD-BLOCK":"—","QA-01-FLD-GATE-STATUS":"NOT_EVALUATED","QA-01-FLD-OPEN-FINDINGS":0,"QA-01-FLD-MANUAL-STATE":"—","QA-01-FLD-MANUAL-OWNER":"—","QA-01-FLD-MANUAL-BLOCKER":"—","QA-01-FLD-MANUAL-DECISION":"—","QA-01-INP-CORR-FINDINGS":"—","QA-01-INP-CORR-SCORECARDS":"—","QA-01-INP-CORR-INSTRUCTION":"TEST-QA-SOURCE-INSTRUCTION-001","QA-01-INP-CORR-SCOPE":"TEST-OUTPUT:FULL","QA-01-INP-CORR-ROOT":"EDITING","QA-01-INP-CORR-TARGET":"EDIT-01","QA-01-FLD-FAILED-VERSION":"—","QA-01-FLD-NEW-VERSION":"—","QA-01-FLD-RECHECK-STATUS":"—","QA-01-FLD-REL-QA-PASS":"NO","QA-01-FLD-REL-FINDINGS":"0 OPEN","QA-01-FLD-REL-MANUAL":"NONE","QA-01-FLD-REL-RIGHTS":"PASS","QA-01-FLD-REL-POLICY":"PASS","QA-01-FLD-REL-CHANNEL":"OPTIONAL/UNBOUND","QA-01-FLD-REL-PACKAGE":"—","QA-01-FLD-REL-OUTPUTS":"—","QA-01-FLD-REL-QA-GATE":"—","QA-01-FLD-REL-RIGHTS-GATE":"TEST-RIGHTS-GATE-PASS","QA-01-FLD-AUTO-PROGRESS":"0/2","QA-01-FLD-AUDIT":"TEST-QA-AUDIT-001","QA-01-FLD-DISABLED":"FINDING_CREATE:AUTHORITY_GAP_QA_ISSUE_CATEGORY","QA-01-FLD-ERROR":"—"},lists:{
"QA-01-LIST-REVIEWS":[item("TEST-QA-TASK-001","TEST-QA-TASK-001 · EDIT-01 · READY",{source_department:"EDIT-01",state:"READY"}),item("TEST-QA-TASK-002","TEST-QA-TASK-002 · VIDEO-01 · READY",{source_department:"VIDEO-01",state:"READY"})],"QA-01-LIST-SCORE-DIMENSIONS":[],"QA-01-LIST-FINDINGS":[],"QA-01-INP-CORR-REVALIDATE":[item("TEST-QA-CRITERIA-V1","TEST-QA-CRITERIA-V1") ]}};}
function clone():QaResolvedContext{const state=currentState();return{...state,values:{...state.values},gate_state:{...state.gate_state},lists:Object.fromEntries(Object.entries(state.lists).map(([k,v])=>[k,v.map(x=>({...x,meta:x.meta?{...x.meta}:undefined}))]))};}
function commit(next:QaResolvedContext,correlation_id?:string){next.correlation_id=correlation_id??next.correlation_id;replaceState(next);return readControlledQaTestProjection();}
function fail(correlation_id:string,error_uid:string,reason_code:string,status=409){return{ok:false as const,status,error_uid,reason_code,correlation_id};}
function pass(correlation_id:string,value:Record<string,unknown>={}){return{ok:true as const,value:{...value,projection:readControlledQaTestProjection(),test_metadata:{data_classification:"TEST_ONLY",synthetic:true,test_dataset_id:"TEST-QA-01",test_run_id:`TEST-QA-${scenario()}`,created_for_validation:true,production_eligible:false}},correlation_id};}
export function isControlledQaServerTestMode(){return isControlledTestMode();}
export function resetControlledQaTestRuntime(){replaceState(createInitial());return readControlledQaTestProjection();}
export function readControlledQaTestProjection(){return clone();}
function bindReview(next:QaResolvedContext){next.qa_review_ref="TEST-QA-REVIEW-001";next.page_state_uid="QA-01-ST-IN-REVIEW";next.current_stage_uid="QA-01-STAGE-02-VALIDATE";next.values["QA-01-FLD-REVIEW-STATE"]="IN_REVIEW";for(const g of["QA-01-GATE-VIEWER","QA-01-GATE-SCRIPT","QA-01-GATE-CRITERIA","QA-01-GATE-EVIDENCE","QA-01-GATE-SCORE","QA-01-GATE-EVIDENCE-CAPTURE"])next.gate_state[g]=true;}
function scoreCurrent(next:QaResolvedContext){const recheck=next.page_state_uid==="QA-01-ST-RECHECK";const manual=scenario()==="MANUAL_REQUIRED"&&!recheck;const score=recheck?98:manual?97:82;next.scorecard_ref=recheck?"TEST-QA-SCORECARD-RECHECK-001":"TEST-QA-SCORECARD-001";next.values["QA-01-FLD-TOTAL-SCORE"]=score;next.values["QA-01-FLD-HARD-BLOCK"]="NO";next.values["QA-01-INP-CORR-SCORECARDS"]=next.scorecard_ref;next.lists["QA-01-LIST-SCORE-DIMENSIONS"]=[item(`${next.scorecard_ref}:CANON`,"Canon / Continuity",{score}),item(`${next.scorecard_ref}:AV_SYNC`,"Audio / Visual Sync",{score}),item(`${next.scorecard_ref}:POLICY`,"Rights / Policy",{score:100})];next.gate_state["QA-01-GATE-CORRECTION"]=!recheck&&!manual;next.gate_state["QA-01-GATE-FAIL"]=!recheck&&!manual;next.gate_state["QA-01-GATE-PASS"]=recheck;
 if(manual){next.manual_review_case_ref="TEST-QA-MANUAL-CASE-001";next.values["QA-01-FLD-MANUAL-STATE"]="OPEN";next.values["QA-01-FLD-MANUAL-OWNER"]="TEST-QA-REVIEWER-POOL";next.values["QA-01-FLD-MANUAL-BLOCKER"]="GOVERNED_MANUAL_REVIEW_REQUIRED";next.values["QA-01-FLD-MANUAL-DECISION"]="PENDING";next.values["QA-01-FLD-GATE-STATUS"]="MANUAL_REVIEW_REQUIRED";next.gate_state["QA-01-GATE-MANUAL"]=true;next.gate_state["QA-01-GATE-MANUAL-DECISION"]=true;}
 else{next.values["QA-01-FLD-GATE-STATUS"]=recheck?"PASS_ELIGIBLE":"FAIL_ELIGIBLE";next.values["QA-01-FLD-MANUAL-STATE"]="NONE";}}
export async function executeControlledQaTestOperation(request:QaRequest){if(!isControlledQaServerTestMode())return fail(request.correlation_id,"QA-01-ERR-CONTEXT-001","QA_TEST_RUNTIME_DISABLED",503);const next=clone();switch(request.operation_id){
 case"startQaReview":bindReview(next);commit(next,request.correlation_id);return pass(request.correlation_id,{qa_review_id:next.qa_review_ref});
 case"startRecheck":if(!next.qa_review_ref||!next.failed_output_version_id||!next.verified_new_output_version_id)return fail(request.correlation_id,"QA-01-ERR-RECHECK-001","VERIFIED_NEW_EXACT_OUTPUT_REQUIRED");next.page_state_uid="QA-01-ST-RECHECK";next.current_stage_uid="QA-01-STAGE-04-RECHECK";next.target_output_version_id=next.verified_new_output_version_id;next.viewer_uri="TEST-OUTPUT-URI-002";next.values["QA-01-FLD-REVIEW-STATE"]="RECHECK";next.values["QA-01-FLD-RECHECK-STATUS"]="RUNNING";next.gate_state["QA-01-GATE-COMPARE"]=true;next.gate_state["QA-01-GATE-SCORE"]=true;next.gate_state["QA-01-GATE-PASS"]=false;next.gate_state["QA-01-GATE-FAIL"]=false;commit(next,request.correlation_id);return pass(request.correlation_id,{recheck_started:true});
 case"decidePass":if(!next.gate_state["QA-01-GATE-PASS"]||next.manual_review_case_ref&&next.values["QA-01-FLD-MANUAL-STATE"]==="OPEN")return fail(request.correlation_id,"QA-01-ERR-GATE-001","QA_PASS_GATE_NOT_SATISFIED");next.page_state_uid="QA-01-ST-PASS";next.current_stage_uid="QA-01-STAGE-05-GATE";next.values["QA-01-FLD-REVIEW-STATE"]="PASS";next.values["QA-01-FLD-GATE-STATUS"]="PASS";next.values["QA-01-FLD-REL-QA-PASS"]="YES";next.values["QA-01-FLD-REL-QA-GATE"]="TEST-QA-GATE-PASS-001";next.gate_state["QA-01-GATE-RELEASE"]=true;commit(next,request.correlation_id);return pass(request.correlation_id,{qa_gate_ref:"TEST-QA-GATE-PASS-001",decision:"PASS"});
 case"decideFail":if(!next.gate_state["QA-01-GATE-FAIL"])return fail(request.correlation_id,"QA-01-ERR-GATE-001","QA_FAIL_GATE_NOT_SATISFIED");next.page_state_uid="QA-01-ST-FAIL";next.current_stage_uid="QA-01-STAGE-05-GATE";next.failed_output_version_id=next.target_output_version_id;next.values["QA-01-FLD-REVIEW-STATE"]="FAIL";next.values["QA-01-FLD-GATE-STATUS"]="FAIL";next.values["QA-01-FLD-FAILED-VERSION"]=next.failed_output_version_id??"—";next.gate_state["QA-01-GATE-CORRECTION"]=true;commit(next,request.correlation_id);return pass(request.correlation_id,{qa_gate_ref:"TEST-QA-GATE-FAIL-001",decision:"FAIL"});
 case"createReleasePackage":if(next.page_state_uid!=="QA-01-ST-PASS"||!next.gate_state["QA-01-GATE-RELEASE"])return fail(request.correlation_id,"QA-01-ERR-RELEASE-001","RELEASE_GATE_NOT_SATISFIED");next.release_package_ref="TEST-RELEASE-CANDIDATE-001";next.values["QA-01-FLD-REL-PACKAGE"]=next.release_package_ref;next.values["QA-01-FLD-REL-OUTPUTS"]=next.target_output_version_id??"—";commit(next,request.correlation_id);return pass(request.correlation_id,{release_package_ref:next.release_package_ref,status:"CANDIDATE_ONLY",publish:false});
 }}
export async function executeControlledQaDepartmentOperation(request:DepartmentOperationRequest){if(!isControlledQaServerTestMode())return fail(request.correlation_id,"QA-01-ERR-CONTEXT-001","QA_TEST_RUNTIME_DISABLED",503);const next=clone();if(request.operation_id==="submitScorecard"){if(!next.qa_review_ref)return fail(request.correlation_id,"QA-01-ERR-CONTEXT-001","QA_REVIEW_REQUIRED");scoreCurrent(next);commit(next,request.correlation_id);return pass(request.correlation_id,{scorecard_ref:next.scorecard_ref,overall_score:next.values["QA-01-FLD-TOTAL-SCORE"],scorer:"SYSTEM_AI",provider_execution:"SIMULATED_EXTERNAL"});}if(request.operation_id==="createFinding")return fail(request.correlation_id,"QA-01-ERR-UNDEFINED-001","AUTHORITY_GAP_QA_ISSUE_CATEGORY_REGISTRY",409);if(request.operation_id==="createCorrectionRequest"){if(!next.scorecard_ref&&!next.lists["QA-01-LIST-FINDINGS"]?.length)return fail(request.correlation_id,"QA-01-ERR-CORRECTION-001","FINDING_OR_SCORECARD_REQUIRED");next.page_state_uid="QA-01-ST-CORRECTION";next.current_stage_uid="QA-01-STAGE-03-FINDING";next.failed_output_version_id=next.target_output_version_id;next.verified_new_output_version_id="TEST-EDIT-OUTPUT-002";next.values["QA-01-FLD-REVIEW-STATE"]="CORRECTION_REQUIRED";next.values["QA-01-FLD-FAILED-VERSION"]=next.failed_output_version_id??"—";next.values["QA-01-FLD-NEW-VERSION"]=next.verified_new_output_version_id;next.values["QA-01-FLD-RECHECK-STATUS"]="VERIFIED_NEW_EXACT_OUTPUT_RECEIVED";next.gate_state["QA-01-GATE-RECHECK"]=true;next.gate_state["QA-01-GATE-COMPARE"]=false;commit(next,request.correlation_id);return pass(request.correlation_id,{correction_request_ref:"TEST-QA-CORRECTION-001",target_department:"EDIT-01",upstream_result_source:"SIMULATED_UPSTREAM_OWNER",verified_new_output_version_id:next.verified_new_output_version_id});}return fail(request.correlation_id,"QA-01-ERR-UNDEFINED-001","CONTROLLED_QA_DEPARTMENT_OPERATION_UNREGISTERED",400);}
export function ensureControlledQaAuxBindings(){if(!isControlledQaServerTestMode())return false;configureQaManualReviewRuntime({authorize:async()=>({allowed:true}),execute:async r=>{const next=clone();if(!next.manual_review_case_ref||next.manual_review_case_ref!==r.manual_review_case_ref)throw new Error("MANUAL_CASE_MISMATCH");if(r.operation_id==="manualReview.modify"){next.values["QA-01-FLD-MANUAL-DECISION"]="MODIFY_IN_PROGRESS";commit(next,r.correlation_id);return{projection:readControlledQaTestProjection(),manual_review_case_ref:next.manual_review_case_ref,state:"OPEN",test_metadata:{data_classification:"TEST_ONLY",production_eligible:false}};}next.values["QA-01-FLD-MANUAL-STATE"]="CLOSED/PASSED";next.values["QA-01-FLD-MANUAL-DECISION"]="PASS";next.gate_state["QA-01-GATE-MANUAL-DECISION"]=false;next.gate_state["QA-01-GATE-PASS"]=true;next.values["QA-01-FLD-GATE-STATUS"]="PASS_ELIGIBLE_AFTER_MANUAL_REVIEW";commit(next,r.correlation_id);return{projection:readControlledQaTestProjection(),manual_review_case_ref:next.manual_review_case_ref,state:"CLOSED/PASSED",test_metadata:{data_classification:"TEST_ONLY",production_eligible:false}};}});
 configureQaAutoOrchestrator({resolveQueue:async()=>[{qa_task_ref:"TEST-QA-TASK-001"},{qa_task_ref:"TEST-QA-TASK-002"}],startReview:async task=>({qa_review_id:`AUTO-${task.qa_task_ref}`}),generateAndPersistScore:async task=>task.qa_task_ref.endsWith("001")?{gate_outcome:"PASS",low_score:false,decision_payload:{score:98}}:{gate_outcome:"FAIL",low_score:true,decision_payload:{score:86}},dispatchGate:async(outcome,task,payload)=>{const next=clone();const items=next.lists["QA-01-LIST-REVIEWS"]??[];next.lists["QA-01-LIST-REVIEWS"]=items.map(x=>x.ref===task.qa_task_ref?{...x,label:`${task.qa_task_ref} · ${outcome}`,meta:{...(x.meta??{}),state:outcome,score:Number((payload as{score?:number})?.score??0)}}:x);const prior=String(next.values["QA-01-FLD-AUTO-PROGRESS"]??"0/2"),done=Math.min(2,(Number.parseInt(prior.split("/")[0]??"0",10)||0)+1);next.values["QA-01-FLD-AUTO-PROGRESS"]=`${done}/2`;commit(next);return{task_ref:task.qa_task_ref,outcome};},emitLowScoreWarning:async task=>{const next=clone();next.values["QA-01-FLD-ERROR"]=`QA_LOW_SCORE_WARNING:${task.qa_task_ref}`;commit(next);}});return true;}
