import type { StrategyNormalizedProjection } from "@/domain/strategy/strategyProjectionPort";
import { isControlledTestMode } from "@/domain/testing/controlledTestData";
import type { ConversationRequest } from "@/server/shared/conversationRuntime";
import type { CandidateCompareRequest } from "@/server/shared/candidateCompareRuntime";
import type { StrategyDecisionRequest } from "@/server/strategy/strategyDecisionRuntime";

const TEST_METADATA={data_classification:"TEST_ONLY",synthetic:true,test_dataset_id:"TEST-STR-WORKSPACE-01",test_run_id:"TEST-RUN-STR-WORKSPACE-CONTROLLED-01",created_for_validation:true,production_eligible:false}as const;
type PageState="EMPTY"|"READY"|"RESPONDING"|"ANALYZING"|"CANDIDATE_READY"|"REVIEW_REQUIRED"|"ADOPTED_CONTEXT"|"FEEDBACK_AVAILABLE"|"ERROR/BLOCKED";
type CandidateState="CANDIDATE_READY"|"REVIEW_REQUIRED"|"ADOPTED_CONTEXT";
type Cached={ok:true;value:unknown}|{ok:false;status:number;reason_code:string};
const CONVERSATION_ID="TEST-STR-CONVERSATION-001",TOPIC_REF="TEST-STR-TOPIC-001",CANDIDATE_REF="TEST-STR-CANDIDATE-001",CANDIDATE_VERSION_REF="TEST-STR-CANDIDATE-V001";
const state:{page_state:PageState;candidate_state:CandidateState;conversation_lines:string[];decision_id:string|null;decision_reason:string|null;audits:string[];idempotency:Map<string,Cached>}={page_state:"READY",candidate_state:"CANDIDATE_READY",conversation_lines:["[TEST] Strategic context ready"],decision_id:null,decision_reason:null,audits:[],idempotency:new Map()};
function rec(v:unknown):Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}
function text(v:unknown){return typeof v==="string"&&v.trim()?v.trim():null;}
function list(v:unknown){return Array.isArray(v)?v.filter(x=>typeof x==="string")as string[]:[];}
function audit(event:string,corr:string){state.audits=[`${event} · ${corr}`,...state.audits].slice(0,8);}
function cacheKey(kind:string,corr:string){return `${kind}:${corr}`;}
function cached(kind:string,corr:string){return state.idempotency.get(cacheKey(kind,corr))??null;}
function save(kind:string,corr:string,value:Cached){state.idempotency.set(cacheKey(kind,corr),value);return value;}
export function isControlledStrategyWorkspaceServerTestMode(){return isControlledTestMode();}
function gates(){return{"STR-01-GATE-PAGE":true,"STR-01-GATE-TOPIC":true,"STR-01-GATE-CONTEXT":true,"STR-01-GATE-MESSAGE":true,"STR-01-GATE-MULTI":true,"STR-01-GATE-ANALYSIS":true,"STR-01-GATE-COMPARE":true,"STR-01-GATE-REVIEW":state.candidate_state==="CANDIDATE_READY","STR-01-GATE-ADOPT":state.candidate_state==="REVIEW_REQUIRED","STR-01-GATE-MEMORY":true,"STR-01-GATE-FEEDBACK":false};}
export function readControlledStrategyWorkspaceProjection():StrategyNormalizedProjection&{test_metadata:typeof TEST_METADATA}{
  const values:Record<string,string>={
    "STR-01-FLD-TOPIC":"[TEST] Market expansion strategy","STR-01-FLD-SCOPE":"TEST-PROJECT-001 / internal strategic scope","STR-01-FLD-HORIZON":"Q4 2026 · TEST_ONLY","STR-01-FLD-STATE":state.page_state,"STR-01-FLD-DECISION-STATE":state.candidate_state,
    "STR-01-FLD-CONTEXT-PRIORITY":"P0 Human Instruction > P1 Confirmed Decision > P2 Internal Data > P3 History > P4 External Intelligence","STR-01-FLD-CONTEXT-SOURCE":"TEST-ERP-COST-001 · TEST-INFO-MARKET-001 · exact refs","STR-01-FLD-CONTEXT-TIME":"TEST-ERP-COST-001@v3 · TEST-INFO-MARKET-001@2026-09-01","STR-01-FLD-CONTEXT-CONFIDENCE":"TEST_ONLY · explicit confidence 0.82",
    "STR-01-FLD-ASSISTANT-SUMMARY":"[TEST] Independent strategic viewpoints summarized; no formal decision","STR-01-FLD-OPEN-QUESTIONS":"[TEST] Validate capacity and budget with owner modules","STR-01-FLD-MEETING-RECORD":"[TEST] Human review remains required",
    "STR-01-FLD-BASIS":"[TEST] Exact market/internal/cost refs","STR-01-FLD-ASSUMPTIONS":"[TEST] Demand remains within stated scenario","STR-01-FLD-OPPORTUNITIES":"[TEST] Controlled opportunity candidate","STR-01-FLD-RISKS":"[TEST] Capacity and cost sensitivity","STR-01-FLD-UNCERTAINTY":"[TEST] External signal confidence 0.82","STR-01-FLD-PATTERN":"[TEST] Baseline comparison only",
    "STR-01-FLD-CANDIDATE-REF":`${CANDIDATE_REF} · ${CANDIDATE_VERSION_REF}`,"STR-01-FLD-REVIEW-STATE":state.candidate_state,"STR-01-FLD-DECISION-ID":state.decision_id??"—","STR-01-FLD-DECISION-RESULT":state.candidate_state==="ADOPTED_CONTEXT"?"ADOPTED_CONTEXT · TEST_ONLY":"—","STR-01-FLD-DECISION-REASON":state.decision_reason??"—","STR-01-FLD-EXECUTION-STATE":"OWNER_EXECUTION_NOT_PERFORMED",
    "STR-01-FLD-EXPECTED":"[TEST] Expected KPI only","STR-01-FLD-ACTUAL":"—","STR-01-FLD-DIFFERENCE":"—","STR-01-FLD-KPI":"—","STR-01-FLD-LEARNING":"—",
    "STR-01-FLD-PROVIDER-BRAND":"TEST_ROUTER_PROVIDER","STR-01-FLD-CORRELATION":state.audits[0]??"—","STR-01-FLD-DISABLED":"Production owner bindings are not provided by TEST_ONLY runtime","STR-01-FLD-OWNER-BOUNDARY":"Finance / Workflow / Governance / Production remain owner-controlled"
  };
  const lists={
    "STR-01-LST-TOPICS":[{ref:TOPIC_REF,label:"[TEST] Market expansion strategy"},{ref:"TEST-STR-TOPIC-002",label:"[TEST] Capacity risk strategy"}],
    "STR-01-LST-CONTEXT":[{ref:"TEST-INFO-MARKET-001",label:"[TEST] Market intelligence · confidence 0.82"},{ref:"TEST-ERP-COST-001",label:"[TEST] ERP cost context v3"}],
    "STR-01-LST-ALERTS":[{ref:"TEST-STR-ALERT-001",label:"[TEST] Capacity risk requires owner review"}],
    "STR-01-LST-PATTERNS":[{ref:"TEST-STR-PATTERN-001",label:"[TEST] Historical pattern v2"}],"STR-01-LST-EXPERIMENTS":[{ref:"TEST-STR-EXPERIMENT-001",label:"[TEST] Experiment record"}],"STR-01-LST-BASELINES":[{ref:"TEST-STR-BASELINE-001",label:"[TEST] Baseline v4"}],"STR-01-LST-LEARNING":[{ref:"TEST-STR-LEARNING-001",label:"[TEST] Learning candidate · not validated knowledge"}]
  };
  const blocks={
    "STR-01-VIEW-CONVERSATION":state.conversation_lines.join("\n"),"STR-01-TBL-COMPARE":"[TEST] Candidate A vs Candidate B · exact refs · read-only","STR-01-CARD-RECOMMENDATION":"[TEST] Recommendation candidate · assumptions/risks/evidence exposed","STR-01-CARD-ALERT":"[TEST] Risk alert candidate","STR-01-CARD-RESOURCE":"[TEST] Resource proposal only · no budget approval","STR-01-CARD-BRIEF":"[TEST] Decision brief · human decision required"
  };
  return{page_state:state.page_state,conversation_id:CONVERSATION_ID,candidate_ref:CANDIDATE_REF,candidate_version_ref:CANDIDATE_VERSION_REF,values,lists,blocks,gate_state:gates(),owner_type:"ERP",owner_context_ref:"TEST-ERP-COST-001",test_metadata:TEST_METADATA};
}
export async function executeControlledStrategyWorkspaceConversation(r:ConversationRequest){
  if(!isControlledStrategyWorkspaceServerTestMode()||r.conversation_id!==CONVERSATION_ID)return null;const kind=`conversation:${r.operation_id}`,hit=cached(kind,r.correlation_id);if(hit)return hit.ok?{ok:true as const,value:hit.value,correlation_id:r.correlation_id}:{ok:false as const,status:hit.status,reason_code:hit.reason_code,correlation_id:r.correlation_id};const p=rec(r.payload);if(text(p.page_uid)!=="workspace:STR-01")return null;
  if(r.operation_id==="sendConversationMessage"){const message=text(p.message),topic=text(p.topic_ref),mode=text(p.mode);if(!message||topic!==TOPIC_REF||!(mode==="SINGLE_AI"||mode==="MULTI_AI")){const x=save(kind,r.correlation_id,{ok:false,status:400,reason_code:"STR01_REQUIRED_FIELDS_MISSING"})as Extract<Cached,{ok:false}>;return{ok:false as const,status:x.status,reason_code:x.reason_code,correlation_id:r.correlation_id};}state.page_state="RESPONDING";state.conversation_lines.push(`[TEST USER] ${message}`,"[TEST AI] Controlled strategic response · proposal only");audit("strategy.conversation.message",r.correlation_id);const value={message_ref:`TEST-STR-MSG-${state.conversation_lines.length}`,state:state.page_state,test_metadata:TEST_METADATA};save(kind,r.correlation_id,{ok:true,value});return{ok:true as const,value,correlation_id:r.correlation_id};}
  if(state.page_state!=="RESPONDING"){const x=save(kind,r.correlation_id,{ok:false,status:409,reason_code:"STR01_NO_ACTIVE_GENERATION"})as Extract<Cached,{ok:false}>;return{ok:false as const,status:x.status,reason_code:x.reason_code,correlation_id:r.correlation_id};}state.page_state="READY";audit("strategy.conversation.stopped",r.correlation_id);const value={state:state.page_state,stopped:true,test_metadata:TEST_METADATA};save(kind,r.correlation_id,{ok:true,value});return{ok:true as const,value,correlation_id:r.correlation_id};
}
export async function executeControlledStrategyWorkspaceCompare(r:CandidateCompareRequest){
  if(!isControlledStrategyWorkspaceServerTestMode())return null;const kind="compare",hit=cached(kind,r.correlation_id);if(hit)return hit.ok?{ok:true as const,value:hit.value,correlation_id:r.correlation_id}:{ok:false as const,status:hit.status,reason_code:hit.reason_code,correlation_id:r.correlation_id};const refs=(r.query.candidate_refs??"").split(",").map(x=>x.trim()).filter(Boolean);if(refs.length<2){const x=save(kind,r.correlation_id,{ok:false,status:400,reason_code:"STR01_COMPARE_REQUIRES_TWO_EXACT_REFS"})as Extract<Cached,{ok:false}>;return{ok:false as const,status:x.status,reason_code:x.reason_code,correlation_id:r.correlation_id};}audit("strategy.candidates.compared",r.correlation_id);const value={candidate_refs:refs,comparison:"TEST_ONLY read-model comparison",mutation:false,test_metadata:TEST_METADATA};save(kind,r.correlation_id,{ok:true,value});return{ok:true as const,value,correlation_id:r.correlation_id};
}
export async function executeControlledStrategyWorkspaceDecision(r:StrategyDecisionRequest){
  if(!isControlledStrategyWorkspaceServerTestMode())return null;const p=rec(r.payload);if(text(p.page_uid)!=="workspace:STR-01")return null;const kind=`decision:${r.operation_id}`,hit=cached(kind,r.correlation_id);if(hit)return hit.ok?{ok:true as const,value:hit.value,correlation_id:r.correlation_id}:{ok:false as const,status:hit.status,reason_code:hit.reason_code,correlation_id:r.correlation_id};if(text(p.candidate_ref)!==CANDIDATE_REF||text(p.candidate_version_ref)!==CANDIDATE_VERSION_REF){const x=save(kind,r.correlation_id,{ok:false,status:409,reason_code:"STR01_EXACT_CANDIDATE_REF_REQUIRED"})as Extract<Cached,{ok:false}>;return{ok:false as const,status:x.status,reason_code:x.reason_code,correlation_id:r.correlation_id};}
  if(r.operation_id==="submitStrategyReview"){if(state.candidate_state!=="CANDIDATE_READY"||!text(p.analysis_basis)||!text(p.risk)||!text(p.uncertainty)||list(p.evidence_refs).length===0){const x=save(kind,r.correlation_id,{ok:false,status:409,reason_code:"STR01_REVIEW_GATE_REJECTED"})as Extract<Cached,{ok:false}>;return{ok:false as const,status:x.status,reason_code:x.reason_code,correlation_id:r.correlation_id};}state.candidate_state="REVIEW_REQUIRED";state.page_state="REVIEW_REQUIRED";audit("strategy.review.requested",r.correlation_id);const value={candidate_ref:CANDIDATE_REF,state:state.candidate_state,human_review_required:true,test_metadata:TEST_METADATA};save(kind,r.correlation_id,{ok:true,value});return{ok:true as const,value,correlation_id:r.correlation_id};}
  const review=rec(p.human_review);if(state.candidate_state!=="REVIEW_REQUIRED"||text(review.decision)!=="APPROVED"||!text(review.reason)||list(p.evidence_refs).length===0){const x=save(kind,r.correlation_id,{ok:false,status:409,reason_code:"STR01_ADOPT_GATE_REJECTED"})as Extract<Cached,{ok:false}>;return{ok:false as const,status:x.status,reason_code:x.reason_code,correlation_id:r.correlation_id};}state.candidate_state="ADOPTED_CONTEXT";state.page_state="ADOPTED_CONTEXT";state.decision_id="TEST-STR-DECISION-001";state.decision_reason=text(review.reason);audit("strategy.context.adopted",r.correlation_id);const value={candidate_ref:CANDIDATE_REF,state:state.candidate_state,owner_execution_performed:false,test_metadata:TEST_METADATA};save(kind,r.correlation_id,{ok:true,value});return{ok:true as const,value,correlation_id:r.correlation_id};
}
