import{isControlledTestMode}from"@/domain/testing/controlledTestData";
import{configureIamClientCommandAdapter,configureIamProjectionResolver,readIamProjection,type IamAccountProjection,type IamDepartmentPreset,type IamIdentitySchemaField,type IamImpactPreview,type IamNormalizedProjection}from"./iamClientPort";
import{isIamPageState}from"./iamRuntimeContract";
import type{IamClientState}from"./iamClientState";
const PAGE_UID="admin:IAM-01";const NEW_ACCOUNT_ID="TEST-IAM-ACCOUNT-NEW-001";const TEST_METADATA={data_classification:"TEST_ONLY",synthetic:true,test_dataset_id:"TEST-IAM-01",test_run_id:"TEST-RUN-IAM-01-CONTROLLED",created_for_validation:true,production_eligible:false}as const;let configured=false;
function rec(v:unknown):Record<string,unknown>{return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}function text(v:unknown){return typeof v==="string"?v:null;}function strings(v:unknown){return Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[];}function bools(v:unknown){const out:Record<string,boolean>={};for(const[k,x]of Object.entries(rec(v)))if(typeof x==="boolean")out[k]=x;return out;}function strmap(v:unknown){const out:Record<string,string>={};for(const[k,x]of Object.entries(rec(v)))if(typeof x==="string")out[k]=x;return out;}
function account(v:unknown):IamAccountProjection|null{const r=rec(v),account_id=text(r.account_id),label=text(r.label);if(!account_id||!label)return null;return{account_id,label,status:text(r.status)??"—",identity_source:text(r.identity_source)??"—",organization_scope:text(r.organization_scope)??"—",mfa:text(r.mfa)??"—",risk:text(r.risk)??"—",session:text(r.session)??"—",front_l1:strings(r.front_l1),admin_l1:strings(r.admin_l1)};}
function field(v:unknown):IamIdentitySchemaField|null{const r=rec(v),field_uid=text(r.field_uid),label=text(r.label);if(!field_uid||!label||r.type!=="TEXT"||typeof r.required!=="boolean")return null;return{field_uid,label,type:"TEXT",required:r.required};}
function preset(v:unknown):IamDepartmentPreset|null{const r=rec(v),ref=text(r.ref),label=text(r.label);if(!ref||!label)return null;return{ref,label,front_l1:strings(r.front_l1),admin_l1:strings(r.admin_l1)};}
function preview(v:unknown):IamImpactPreview|null{if(v===null||v===undefined)return null;const r=rec(v),preview_ref=text(r.preview_ref),account_id=text(r.account_id);if(!preview_ref||!account_id||typeof r.approval_required!=="boolean")return null;return{preview_ref,account_id,added:strings(r.added),removed:strings(r.removed),unchanged:strings(r.unchanged),blocked:strings(r.blocked),approval_required:r.approval_required};}
function resolveControlled(raw:unknown):IamNormalizedProjection{const r=rec(raw),m=rec(r.test_metadata);if(m.data_classification!=="TEST_ONLY"||m.synthetic!==true||m.production_eligible!==false)throw new Error("IAM_CONTROLLED_TEST_METADATA_REQUIRED");if(!isIamPageState(r.page_state))throw new Error("IAM_CONTROLLED_PAGE_STATE_INVALID");return{page_state:r.page_state,values:strmap(r.values),gate_state:bools(r.gate_state),authorized_account_count:typeof r.authorized_account_count==="number"?r.authorized_account_count:null,accounts:Array.isArray(r.accounts)?r.accounts.flatMap(x=>{const a=account(x);return a?[a]:[]}):[],identity_schema:Array.isArray(r.identity_schema)?r.identity_schema.flatMap(x=>{const f=field(x);return f?[f]:[]}):[],department_presets:Array.isArray(r.department_presets)?r.department_presets.flatMap(x=>{const p=preset(x);return p?[p]:[]}):[],preview:preview(r.preview),audit_entries:strings(r.audit_entries)};}
async function request(path:string,method:string,body:unknown){const correlation_id=crypto.randomUUID();let response:Response;try{response=await fetch(path,{method,cache:"no-store",headers:{"content-type":"application/json","x-correlation-id":correlation_id},body:JSON.stringify(body)});}catch{return{ok:false as const,error_uid:"IAM-01-ERR-UNDEFINED",reason_code:"IAM_CONTROLLED_REQUEST_FAILED",correlation_id};}const raw=await response.json().catch(()=>null);if(!response.ok){const r=rec(raw);return{ok:false as const,error_uid:text(r.reason_code)?.startsWith("IAM-01-ERR-")?text(r.reason_code) as string:"IAM-01-ERR-UNDEFINED",reason_code:text(r.reason_code)??"IAM_CONTROLLED_COMMAND_FAILED",correlation_id:text(r.correlation_id)??correlation_id};}return{ok:true as const,raw,correlation_id:response.headers.get("x-correlation-id")??correlation_id};}
async function after(client:IamClientState,correlation_id:string){const p=await readIamProjection();if(!p.ok)return p;return{ok:true as const,projection:p.projection,client_state:client,correlation_id};}
async function invoke(input:{action_uid:string;control_uid:string;client_state:unknown;projection:IamNormalizedProjection|null;explicit_confirmation?:boolean}){const client=input.client_state as IamClientState;const draftId=client.draft_id??"TEST-IAM-DRAFT-001",accountId=client.account_id??NEW_ACCOUNT_ID,base={page_uid:PAGE_UID,test_metadata:TEST_METADATA};
 if(input.action_uid==="IAM-01-ACT-SEARCH"){const r=await request("/v1/search","POST",{...base,query:client.search_query});if(!r.ok)return r;return after(client,r.correlation_id);}
 if(input.action_uid==="IAM-01-ACT-SAVE-DRAFT"){const r=await request("/v1/drafts","POST",{...base,draft_id:draftId,draft_type:"iam_account",basic_data:client.basic_data,front_l1:client.front_l1,admin_l1:client.admin_l1});if(!r.ok)return r;return after({...client,draft_id:draftId},r.correlation_id);}
 if(input.action_uid==="IAM-01-ACT-VALIDATE-DRAFT"){if(!client.draft_id)return{ok:false as const,error_uid:"IAM-01-ERR-UNDEFINED",reason_code:"IAM_DRAFT_REQUIRED",correlation_id:"unresolved"};const r=await request(`/v1/drafts/${encodeURIComponent(client.draft_id)}/validate`,"POST",{...base,draft_id:client.draft_id});if(!r.ok)return r;return after({...client,flow:client.mode==="EDIT"?"EDIT_PERMISSION":"CREATE_PERMISSION"},r.correlation_id);}
 if(input.action_uid==="IAM-01-ACT-PREVIEW"){const r=await request(`/v1/iam/accounts/${encodeURIComponent(accountId)}/authorization-impact`,"POST",{...base,draft_id:client.draft_id,front_l1:client.front_l1,admin_l1:client.admin_l1});if(!r.ok)return r;const p=await readIamProjection();if(!p.ok)return p;return{ok:true as const,projection:p.projection,client_state:{...client,account_id:accountId,preview_ref:p.projection.preview?.preview_ref??null,flow:client.mode==="EDIT"?"EDIT_PREVIEW":"CREATE_PREVIEW"},correlation_id:r.correlation_id};}
 if(input.action_uid==="IAM-01-ACT-COMPLETE"){if(input.explicit_confirmation!==true||!input.projection?.preview)return{ok:false as const,error_uid:"IAM-01-ERR-AUTH-DENIED",reason_code:"IAM01_EXPLICIT_CONFIRMATION_REQUIRED",correlation_id:"unresolved"};const preview=input.projection.preview;
  const save=await request("/v1/drafts","POST",{...base,draft_id:draftId,draft_type:"iam_account",basic_data:client.basic_data,front_l1:client.front_l1,admin_l1:client.admin_l1});if(!save.ok)return save;
  const validate=await request(`/v1/drafts/${encodeURIComponent(draftId)}/validate`,"POST",{...base,draft_id:draftId});if(!validate.ok)return validate;
  const rePreview=await request(`/v1/iam/accounts/${encodeURIComponent(accountId)}/authorization-impact`,"POST",{...base,draft_id:draftId,front_l1:client.front_l1,admin_l1:client.admin_l1});if(!rePreview.ok)return rePreview;
  const configure=await request(`/v1/governance/resources/${encodeURIComponent(accountId)}`,"PATCH",{...base,draft_id:draftId,explicit_confirmation:true});if(!configure.ok)return configure;
  for(const permission_ref of preview.added){const r=await request(`/v1/iam/accounts/${encodeURIComponent(accountId)}/permissions`,"POST",{...base,permission_ref,explicit_confirmation:true});if(!r.ok)return{...r,error_uid:"IAM-01-ERR-PARTIAL-APPLY",reason_code:"IAM-01-ERR-PARTIAL-APPLY"};}
  for(const permission_ref of preview.removed){const r=await request(`/v1/iam/accounts/${encodeURIComponent(accountId)}/permissions`,"DELETE",{...base,permission_ref,explicit_confirmation:true});if(!r.ok)return{...r,error_uid:"IAM-01-ERR-PARTIAL-APPLY",reason_code:"IAM-01-ERR-PARTIAL-APPLY"};}
  if(preview.approval_required){const r=await request(`/v1/governance/resources/${encodeURIComponent(accountId)}/approve`,"POST",{...base,explicit_confirmation:true});if(!r.ok)return r;}
  return after({...client,account_id:accountId,draft_id:draftId,flow:"COMPLETE"},configure.correlation_id);
 }
 return{ok:false as const,error_uid:"IAM-01-ERR-UNDEFINED",reason_code:"IAM_CONTROLLED_ACTION_UNREGISTERED",correlation_id:"unresolved"};
}
export function ensureControlledIamClientTestRuntime(){if(configured||!isControlledTestMode())return false;configureIamProjectionResolver({resolve:resolveControlled});configureIamClientCommandAdapter({invoke});configured=true;return true;}
